// ---------------------------------------------------------------------------
// Language definitions for the syntax highlighter. Pure static data with
// no runtime behavior. Adding a new language is a single-site change here.
// ---------------------------------------------------------------------------

export interface LangDef {
  keywords: Set<string>;
  aliases: string[];
}

export const SUPPORTED_LANGUAGES: ReadonlyMap<string, LangDef> = new Map<string, LangDef>([
  [
    "go",
    {
      keywords: new Set([
        "package",
        "import",
        "func",
        "var",
        "const",
        "type",
        "struct",
        "interface",
        "map",
        "chan",
        "go",
        "defer",
        "return",
        "if",
        "else",
        "for",
        "range",
        "switch",
        "case",
        "default",
        "select",
        "break",
        "continue",
        "fallthrough",
        "nil",
        "true",
        "false",
        "iota",
        "make",
        "new",
        "append",
        "len",
        "cap",
        "delete",
        "copy",
        "close",
        "panic",
        "recover",
        "error",
      ]),
      aliases: [],
    },
  ],
  [
    "ts",
    {
      keywords: new Set([
        "import",
        "export",
        "from",
        "const",
        "let",
        "var",
        "function",
        "class",
        "interface",
        "type",
        "enum",
        "return",
        "if",
        "else",
        "for",
        "while",
        "do",
        "switch",
        "case",
        "default",
        "break",
        "continue",
        "new",
        "this",
        "super",
        "extends",
        "implements",
        "async",
        "await",
        "yield",
        "throw",
        "try",
        "catch",
        "finally",
        "typeof",
        "instanceof",
        "in",
        "of",
        "void",
        "null",
        "undefined",
        "true",
        "false",
        "as",
        "is",
        "readonly",
        "abstract",
        "static",
        "private",
        "protected",
        "public",
        "declare",
        "module",
        "namespace",
      ]),
      aliases: ["typescript"],
    },
  ],
  [
    "js",
    {
      keywords: new Set([
        "import",
        "export",
        "from",
        "const",
        "let",
        "var",
        "function",
        "class",
        "return",
        "if",
        "else",
        "for",
        "while",
        "do",
        "switch",
        "case",
        "default",
        "break",
        "continue",
        "new",
        "this",
        "super",
        "extends",
        "async",
        "await",
        "yield",
        "throw",
        "try",
        "catch",
        "finally",
        "typeof",
        "instanceof",
        "in",
        "of",
        "void",
        "null",
        "undefined",
        "true",
        "false",
        "delete",
      ]),
      aliases: ["javascript"],
    },
  ],
  [
    "py",
    {
      keywords: new Set([
        "import",
        "from",
        "def",
        "class",
        "return",
        "if",
        "elif",
        "else",
        "for",
        "while",
        "break",
        "continue",
        "pass",
        "raise",
        "try",
        "except",
        "finally",
        "with",
        "as",
        "yield",
        "lambda",
        "and",
        "or",
        "not",
        "in",
        "is",
        "None",
        "True",
        "False",
        "global",
        "nonlocal",
        "del",
        "assert",
        "async",
        "await",
      ]),
      aliases: ["python"],
    },
  ],
  [
    "sh",
    {
      keywords: new Set([
        "if",
        "then",
        "else",
        "elif",
        "fi",
        "for",
        "while",
        "do",
        "done",
        "case",
        "esac",
        "in",
        "function",
        "return",
        "exit",
        "local",
        "export",
        "readonly",
        "unset",
        "shift",
        "set",
        "true",
        "false",
        "source",
      ]),
      aliases: ["shell"],
    },
  ],
  [
    "rs",
    {
      keywords: new Set([
        "fn",
        "let",
        "mut",
        "const",
        "struct",
        "enum",
        "impl",
        "trait",
        "pub",
        "use",
        "mod",
        "crate",
        "self",
        "super",
        "return",
        "if",
        "else",
        "for",
        "while",
        "loop",
        "match",
        "break",
        "continue",
        "as",
        "in",
        "ref",
        "move",
        "async",
        "await",
        "unsafe",
        "where",
        "type",
        "true",
        "false",
        "None",
        "Some",
        "Ok",
        "Err",
      ]),
      aliases: ["rust"],
    },
  ],
  [
    "rb",
    {
      keywords: new Set<string>(),
      aliases: ["ruby"],
    },
  ],
  [
    "c",
    {
      keywords: new Set<string>(),
      aliases: ["cplusplus", "c++"],
    },
  ],
]);

// Derived reverse-index: alias → internal key (built from SUPPORTED_LANGUAGES).
export const FENCED_ALIASES: Readonly<Record<string, string>> = (() => {
  const m: Record<string, string> = {};
  for (const [key, def] of SUPPORTED_LANGUAGES) {
    for (const alias of def.aliases) {
      m[alias] = key;
    }
  }
  return m;
})();

// Keyword lookup helper: returns the keyword set for a language key.
export const KEYWORDS: Readonly<Record<string, Set<string>>> = (() => {
  const m: Record<string, Set<string>> = {};
  for (const [key, def] of SUPPORTED_LANGUAGES) {
    if (def.keywords.size > 0) {
      m[key] = def.keywords;
    }
  }
  return m;
})();

// Shared keywords for languages without specific sets.
export const GENERIC_KW = new Set([
  "if",
  "else",
  "for",
  "while",
  "return",
  "function",
  "class",
  "import",
  "export",
  "const",
  "let",
  "var",
  "true",
  "false",
  "null",
  "undefined",
  "new",
  "this",
]);
