// ---------------------------------------------------------------------------
// GENERATED FILE — do not hand-edit.
//
// The named character references HTML 4.01 publishes, which is the membership
// rule for a named reference in this parser. The standard defines the set as
// three blocks, and this table is all three minus the names the parser owns
// inline:
//
//   Latin-1                     https://www.w3.org/TR/html4/HTMLlat1.ent
//   symbols, math, Greek        https://www.w3.org/TR/html4/HTMLsymbol.ent
//   markup-significant, i18n    https://www.w3.org/TR/html4/HTMLspecial.ent
//
// Index: https://www.w3.org/TR/html4/sgml/entities.html
//
// 252 names are declared across the three blocks. `amp`, `gt`, `lt` and
// `quot` are removed because smd-parser-handlers.ts decodes those inline (with
// `apos`, which HTML 4.01 does not define), leaving the 248 here. Both halves
// come from the standard: a `<!ENTITY name CDATA "&#NNN;">` declaration supplies
// the name and the code point.
//
// This set rather than WHATWG's 2,125 is a DECLINED CommonMark 6.2 conformance,
// recorded with its measurement in smd-parser.ts's divergence register.
//
// Regenerate with:
//   for f in HTMLlat1 HTMLsymbol HTMLspecial; do
//     curl -sSo /tmp/$f.ent https://www.w3.org/TR/html4/$f.ent
//   done
//   node _scratch/vibekit-md-round4/gen-entities-html4.mjs \
//     /tmp/HTMLlat1.ent /tmp/HTMLsymbol.ent /tmp/HTMLspecial.ent \
//     static-src/smd-entities.ts
//   npx prettier --write static-src/smd-entities.ts
// ---------------------------------------------------------------------------

/** The longest name in the table, which bounds how long the parser holds a
 *  candidate reference before deciding it is not one. */
export const MAX_ENTITY_NAME_LENGTH = 8;

export const NAMED_ENTITIES: Readonly<Record<string, string>> = {
  AElig: "Æ",
  Aacute: "Á",
  Acirc: "Â",
  Agrave: "À",
  Alpha: "Α",
  Aring: "Å",
  Atilde: "Ã",
  Auml: "Ä",
  Beta: "Β",
  Ccedil: "Ç",
  Chi: "Χ",
  Dagger: "‡",
  Delta: "Δ",
  ETH: "Ð",
  Eacute: "É",
  Ecirc: "Ê",
  Egrave: "È",
  Epsilon: "Ε",
  Eta: "Η",
  Euml: "Ë",
  Gamma: "Γ",
  Iacute: "Í",
  Icirc: "Î",
  Igrave: "Ì",
  Iota: "Ι",
  Iuml: "Ï",
  Kappa: "Κ",
  Lambda: "Λ",
  Mu: "Μ",
  Ntilde: "Ñ",
  Nu: "Ν",
  OElig: "Œ",
  Oacute: "Ó",
  Ocirc: "Ô",
  Ograve: "Ò",
  Omega: "Ω",
  Omicron: "Ο",
  Oslash: "Ø",
  Otilde: "Õ",
  Ouml: "Ö",
  Phi: "Φ",
  Pi: "Π",
  Prime: "″",
  Psi: "Ψ",
  Rho: "Ρ",
  Scaron: "Š",
  Sigma: "Σ",
  THORN: "Þ",
  Tau: "Τ",
  Theta: "Θ",
  Uacute: "Ú",
  Ucirc: "Û",
  Ugrave: "Ù",
  Upsilon: "Υ",
  Uuml: "Ü",
  Xi: "Ξ",
  Yacute: "Ý",
  Yuml: "Ÿ",
  Zeta: "Ζ",
  aacute: "á",
  acirc: "â",
  acute: "´",
  aelig: "æ",
  agrave: "à",
  alefsym: "ℵ",
  alpha: "α",
  and: "∧",
  ang: "∠",
  aring: "å",
  asymp: "≈",
  atilde: "ã",
  auml: "ä",
  bdquo: "„",
  beta: "β",
  brvbar: "¦",
  bull: "•",
  cap: "∩",
  ccedil: "ç",
  cedil: "¸",
  cent: "¢",
  chi: "χ",
  circ: "ˆ",
  clubs: "♣",
  cong: "≅",
  copy: "©",
  crarr: "↵",
  cup: "∪",
  curren: "¤",
  dArr: "⇓",
  dagger: "†",
  darr: "↓",
  deg: "°",
  delta: "δ",
  diams: "♦",
  divide: "÷",
  eacute: "é",
  ecirc: "ê",
  egrave: "è",
  empty: "∅",
  emsp: " ",
  ensp: " ",
  epsilon: "ε",
  equiv: "≡",
  eta: "η",
  eth: "ð",
  euml: "ë",
  euro: "€",
  exist: "∃",
  fnof: "ƒ",
  forall: "∀",
  frac12: "½",
  frac14: "¼",
  frac34: "¾",
  frasl: "⁄",
  gamma: "γ",
  ge: "≥",
  hArr: "⇔",
  harr: "↔",
  hearts: "♥",
  hellip: "…",
  iacute: "í",
  icirc: "î",
  iexcl: "¡",
  igrave: "ì",
  image: "ℑ",
  infin: "∞",
  int: "∫",
  iota: "ι",
  iquest: "¿",
  isin: "∈",
  iuml: "ï",
  kappa: "κ",
  lArr: "⇐",
  lambda: "λ",
  lang: "〈",
  laquo: "«",
  larr: "←",
  lceil: "⌈",
  ldquo: "“",
  le: "≤",
  lfloor: "⌊",
  lowast: "∗",
  loz: "◊",
  lrm: "‎",
  lsaquo: "‹",
  lsquo: "‘",
  macr: "¯",
  mdash: "—",
  micro: "µ",
  middot: "·",
  minus: "−",
  mu: "μ",
  nabla: "∇",
  nbsp: " ",
  ndash: "–",
  ne: "≠",
  ni: "∋",
  not: "¬",
  notin: "∉",
  nsub: "⊄",
  ntilde: "ñ",
  nu: "ν",
  oacute: "ó",
  ocirc: "ô",
  oelig: "œ",
  ograve: "ò",
  oline: "‾",
  omega: "ω",
  omicron: "ο",
  oplus: "⊕",
  or: "∨",
  ordf: "ª",
  ordm: "º",
  oslash: "ø",
  otilde: "õ",
  otimes: "⊗",
  ouml: "ö",
  para: "¶",
  part: "∂",
  permil: "‰",
  perp: "⊥",
  phi: "φ",
  pi: "π",
  piv: "ϖ",
  plusmn: "±",
  pound: "£",
  prime: "′",
  prod: "∏",
  prop: "∝",
  psi: "ψ",
  rArr: "⇒",
  radic: "√",
  rang: "〉",
  raquo: "»",
  rarr: "→",
  rceil: "⌉",
  rdquo: "”",
  real: "ℜ",
  reg: "®",
  rfloor: "⌋",
  rho: "ρ",
  rlm: "‏",
  rsaquo: "›",
  rsquo: "’",
  sbquo: "‚",
  scaron: "š",
  sdot: "⋅",
  sect: "§",
  shy: "­",
  sigma: "σ",
  sigmaf: "ς",
  sim: "∼",
  spades: "♠",
  sub: "⊂",
  sube: "⊆",
  sum: "∑",
  sup: "⊃",
  sup1: "¹",
  sup2: "²",
  sup3: "³",
  supe: "⊇",
  szlig: "ß",
  tau: "τ",
  there4: "∴",
  theta: "θ",
  thetasym: "ϑ",
  thinsp: " ",
  thorn: "þ",
  tilde: "˜",
  times: "×",
  trade: "™",
  uArr: "⇑",
  uacute: "ú",
  uarr: "↑",
  ucirc: "û",
  ugrave: "ù",
  uml: "¨",
  upsih: "ϒ",
  upsilon: "υ",
  uuml: "ü",
  weierp: "℘",
  xi: "ξ",
  yacute: "ý",
  yen: "¥",
  yuml: "ÿ",
  zeta: "ζ",
  zwj: "‍",
  zwnj: "‌",
};
