package vibekit

// SecretMask is the placeholder value returned for every secret on
// public reads. Clients send this unchanged on update to keep the
// stored value; any other value replaces it.
const SecretMask = "***"

// DefaultChatName is the fallback name for newly created chats when the
// client does not supply one.
const DefaultChatName = "New conversation"

// MaxDraftBytes caps a chat's persisted composer draft.
//
// Two orders of magnitude below a prompt's 512 KiB cap on purpose. A draft is
// re-saved on a 600ms debounce while the user types and is read back on every
// chat open, so its cost is paid repeatedly where a prompt's is paid once; and
// text long enough to exceed this has been pasted rather than typed, which is
// what attachments are for. Shared by the command boundary (which answers 413)
// and the store (which refuses defensively).
const MaxDraftBytes = 16 * 1024

// MaxChatNameBytes caps the byte length of chat names at creation and
// rename boundaries. All code paths that set Chat.Name should enforce
// this limit.
const MaxChatNameBytes = 512

// There is no NewChatID. Every chat id is generated by the CLIENT and arrives
// on the command envelope; the server's only chat-creating path used to be the
// rewind BRANCH, and a rewind reverts the chat it is in. Adding a server-side
// generator back would mean the server had invented a chat the client cannot
// address.

// ErrMsgUtilityUnavailable is the canonical error message returned when
// the utility bridge (LLM prompt function) is not wired. Used by both
// the git and server packages to keep the error string in one place.
const ErrMsgUtilityUnavailable = "utility bridge not available"

// ChatID is a typed wrapper for chat identifiers. The underlying string
// marshals identically to JSON, preserving the wire contract.
type ChatID string

// String implements fmt.Stringer for logging convenience.
func (c ChatID) String() string { return string(c) }

// SessionID is a typed wrapper for ACP session identifiers. Values are
// validated via ids.ValidSessionID before assignment; the type makes
// invalid-state propagation a compile-time-visible decision.
type SessionID string

// String implements fmt.Stringer for logging convenience.
func (s SessionID) String() string { return string(s) }

// ModelID is a typed wrapper for model identifiers. Values are
// validated via ids.ValidIdent before assignment; the type makes
// invalid-state propagation a compile-time-visible decision.
type ModelID string

// String implements fmt.Stringer for logging convenience.
func (m ModelID) String() string { return string(m) }
