// Package steering generates the environment.md steering file kiro-cli
// reads on every session. Regenerated at startup, before each bridge
// spawn (so every session reads fresh content), when the MCP runtime
// registry changes, and when the composition-layer forge snapshot
// cache observes a change (login/disconnect or TTL revalidation). The
// generator itself must stay fast and network-free: it runs
// synchronously on the session-start path, so anything slow (forge CLI
// repo listings) is cached upstream and handed in via snapshot
// callbacks.
package steering

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"sync"

	"github.com/cplieger/atomicfile/v3"
	"github.com/cplieger/vibekit/internal/vibekit"
	"github.com/cplieger/vibekit/internal/workspace"
)

// Read caps bound untrusted workspace input so a crafted repo can't
// OOM the container by committing a multi-GiB README or tools.json.
// The workspace hosts agent-cloned upstreams whose contents are
// attacker-controlled from our point of view; everywhere else in
// vibekit (bridge_fs, checkpoint blobs, forges, filebrowse) clamps
// reads via io.LimitReader for the same reason.
const (
	firstLineReadCap = 4 << 10 // README first non-heading line fits easily in 4 KiB
	toolsManifestCap = 1 << 20 // any realistic tools.json stays well under 1 MiB

	inclusionAlways    = "always"
	inclusionFileMatch = "fileMatch"
	inclusionManual    = "manual"
	inclusionAuto      = "auto"

	// Forge kinds, mirroring forges.Kind values without the import.
	kindGitHub   = "github"
	kindGitLab   = "gitlab"
	kindGitea    = "gitea"
	kindCodeberg = "codeberg"
)

// MCPSnapshot is the subset of the MCP runtime registry the steering
// generator uses. Returned by the snapshot function wired at construct
// time; steering has no direct dependency on agent internals.
type MCPSnapshot struct {
	Servers []vibekit.MCPSnapshotServer
}

// ForgeSnapshot describes connected forge providers for the steering file.
type ForgeSnapshot struct {
	Providers []ForgeProvider
}

// ForgeProvider is one connected forge with its repos.
type ForgeProvider struct {
	Kind  string   // "github", "gitlab", etc.
	Host  string   // "github.com", "gitlab.company.com"
	User  string   // authenticated username
	Email string   // authenticated email (best-effort, may be "")
	Repos []string // top repo names (capped for brevity)
}

// Generator produces steering files for kiro-cli.
type Generator struct {
	mcpSnapshot   func() MCPSnapshot
	forgeSnapshot func() ForgeSnapshot
	workDir       string
	configDir     string
	mu            sync.Mutex
}

// New returns a Generator that writes steering files for the given workDir and configDir.
func New(workDir, configDir string) *Generator {
	return &Generator{workDir: workDir, configDir: configDir}
}

// SetMCPSnapshot wires a snapshot callback. Called once after
// construction. If unset, the generator omits the MCP section entirely.
// The callback runs OUTSIDE the generator's mutex (so it may safely
// take agent locks without re-entry risk); only the pointer assignment
// and read are lock-guarded. Generate enforces this by snapshotting
// g.mcpSnapshot under g.mu, then releasing the lock around the call.
func (g *Generator) SetMCPSnapshot(fn func() MCPSnapshot) {
	g.mu.Lock()
	g.mcpSnapshot = fn
	g.mu.Unlock()
}

// SetForgeSnapshot wires a callback that returns connected forge info.
// Called once after construction. If unset, the forge section is omitted.
func (g *Generator) SetForgeSnapshot(fn func() ForgeSnapshot) {
	g.mu.Lock()
	g.forgeSnapshot = fn
	g.mu.Unlock()
}

// Generate renders environment.md and writes it atomically. Holds
// g.mu across the full write so concurrent Generate calls serialise
// rather than racing. Skips the write when the rendered content is
// byte-identical to the existing file (avoids mtime bumps from
// frequent MCP-event triggered regenerations).
func (g *Generator) Generate(ctx context.Context) {
	g.mu.Lock()
	defer g.mu.Unlock()

	// Snapshot the callback pointer under g.mu, then invoke it
	// outside the read-only section. Matches the contract the
	// SetMCPSnapshot doc promises: the callback may safely take
	// agent locks without re-entry risk.
	snapshotFn := g.mcpSnapshot
	forgeFn := g.forgeSnapshot
	var mcp MCPSnapshot
	var forges ForgeSnapshot
	if snapshotFn != nil || forgeFn != nil {
		g.mu.Unlock()
		if snapshotFn != nil {
			mcp = snapshotFn()
		}
		if forgeFn != nil {
			forges = forgeFn()
		}
		g.mu.Lock()
	}

	var b strings.Builder
	b.WriteString("# Environment\n\n")
	b.WriteString("Kiro Web container. Workspace: `" + g.workDir + "`\n\n")
	b.WriteString("This file is auto-generated by vibekit (at startup, on MCP changes, ")
	b.WriteString("and before each session start); edits are overwritten. Durable custom ")
	b.WriteString("instructions belong in `custom.md` (Settings → Custom instructions).\n\n")

	// tools-state.json is the tools engine's machine state: what is
	// actually installed (vs tools.json, which is intent). The agent
	// only cares about binaries that exist.
	state := filepath.Join(g.configDir, "tools-state.json")
	if data, err := readCappedFile(state, toolsManifestCap); err == nil {
		writeTools(&b, data)
	}
	if snapshotFn != nil {
		writeMCP(&b, mcp)
	}
	if forgeFn != nil {
		writeForges(&b, forges)
	}
	writeWorkspace(ctx, &b, g.workDir, connectedKinds(forges))

	b.WriteString("## Limitations\n\n")
	b.WriteString("- Shell commands run in the container, not on the host\n")
	b.WriteString("- No GUI or browser; web_fetch and web_search work\n")
	b.WriteString("- Container has no Docker socket\n\n")

	b.WriteString("## Capabilities\n\n")
	b.WriteString("- Chat history is stored in `" + g.configDir + "/chats/*.json` (one file per chat)\n")
	b.WriteString("- Conversations are searchable via the chat files\n")
	b.WriteString("- File browser and editor are available in the UI for reading and writing files\n")
	b.WriteString("- You can read, write, and edit files in the workspace directly\n")
	b.WriteString("- File edits are checkpointed server-side; the user can restore or undo them per turn\n")
	b.WriteString("- User-attached documents (pdf/csv/doc/docx/xls/xlsx) arrive embedded in the prompt; ")
	b.WriteString("every other attached file arrives as a workspace path to read with file tools\n")
	b.WriteString("- Shell commands execute in the workspace directory\n")
	b.WriteString("- Git operations are available via the Git panel\n")

	// Workflow-run recovery. The UI offers Retry only on a PARENTLESS run (one
	// the user launched from the Workflows list); a run YOU launched is parented
	// on this chat's session, so its recovery is yours and nothing surfaces a
	// button for it. Without this the agent has the verbs and no reason to think
	// of them, and a failed step in its own run reads as a dead end.
	b.WriteString("- A workflow run you launched is yours to recover: on failure you can retry it ")
	b.WriteString("(which resets only the failed and aborted steps plus their ancestors, keeping ")
	b.WriteString("completed work) rather than relaunching from step one, and you can mark a wedged ")
	b.WriteString("in-flight step completed or failed to let the run advance. Prefer retrying over ")
	b.WriteString("relaunching when steps have already succeeded, and say which you chose and why\n")

	content := []byte(b.String())
	steeringFile := workspace.KiroSteeringPath("environment.md")

	// Skip if the rendered content is byte-identical. MCP event
	// storms fire Generate multiple times per second; rewriting
	// the same bytes bumps mtime and wastes disk I/O.
	if existing, readErr := os.ReadFile(steeringFile); readErr == nil && bytes.Equal(existing, content) {
		slog.Debug("steering: content unchanged, skipping write", "path", steeringFile)
		return
	}

	// Mode 0o600 matches the narrow-by-default stance of other
	// vibekit writes: this file lists the workspace layout and
	// MCP server names which, while not secrets, are information
	// that should stay scoped to the single user that runs
	// kiro-cli. atomicfile.WriteFile is the atomic temp+rename helper so
	// a crash mid-write can't leave a truncated file. WithMkdirMode(0o700)
	// auto-creates the parent dir narrowly (the file has no group/world
	// bits), so we don't MkdirAll explicitly — that would widen it to 0o755.
	if _, wErr := atomicfile.WriteFile(ctx, steeringFile, content,
		atomicfile.WithMode(0o600), atomicfile.WithMkdirMode(0o700)); wErr != nil {
		slog.Error("steering: write", "path", steeringFile, "error", wErr)
		return
	}
	slog.Info("steering: wrote", "path", steeringFile, "bytes", len(content))
}

// readCappedFile reads at most limit bytes from path. Used for untrusted
// workspace input (README, tools.json) so a crafted large file can't
// OOM the container. Returns the (possibly truncated) bytes and any
// error from open/read; callers treat errors the same way os.ReadFile
// did (log-and-omit, not a fatal).
func readCappedFile(path string, limit int64) ([]byte, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	return io.ReadAll(io.LimitReader(f, limit))
}

// CustomPath returns the path to the custom.md steering file in the kiro home directory.
func (g *Generator) CustomPath() string {
	return workspace.KiroSteeringPath("custom.md")
}

// toolState mirrors the tools engine's per-tool machine state subset
// this generator consumes (the toolbelt engine's ToolStatus).
type toolState struct {
	InstalledVersion string   `json:"installed_version"`
	Bins             []string `json:"bins,omitempty"`
	PMBins           []string `json:"pm_bins,omitempty"`
}

func writeTools(b *strings.Builder, data []byte) {
	var state struct {
		Tools map[string]toolState `json:"tools"`
	}
	if err := json.Unmarshal(data, &state); err != nil {
		slog.Error("steering: parse tools-state.json", "error", err)
		return
	}
	type tool struct{ name, version string }
	var all []tool
	for name, st := range state.Tools {
		if st.InstalledVersion == "" {
			continue
		}
		bins := append(append([]string{}, st.Bins...), st.PMBins...)
		if len(bins) == 0 {
			bins = []string{name}
		}
		for _, bin := range bins {
			all = append(all, tool{bin, st.InstalledVersion})
		}
	}
	if len(all) == 0 {
		return
	}
	slices.SortFunc(all, func(a, b tool) int { return strings.Compare(a.name, b.name) })
	all = slices.CompactFunc(all, func(a, b tool) bool { return a.name == b.name })
	b.WriteString("## Installed tools\n\n")
	for _, t := range all {
		fmt.Fprintf(b, "- %s %s\n", t.name, t.version)
	}
	b.WriteString("\n")
}

// writeMCP emits the "Connected integrations" section listing every
// currently-connected MCP server.
func writeMCP(b *strings.Builder, snap MCPSnapshot) {
	if len(snap.Servers) == 0 {
		return
	}
	servers := slices.Clone(snap.Servers)
	slices.SortFunc(servers, func(a, b vibekit.MCPSnapshotServer) int {
		return strings.Compare(a.Name, b.Name)
	})

	b.WriteString("## Connected integrations\n\n")
	b.WriteString("External systems the user has connected via MCP. ")
	b.WriteString("Their tools appear in your toolset with the server name ")
	b.WriteString("embedded in the tool name.\n\n")
	for _, s := range servers {
		fmt.Fprintf(b, "- **%s**\n", s.Name)
	}
	b.WriteString("\n")
}

// writeForges renders the connected forge providers section with
// actionable context for the agent. The CLI hint list is scoped to the
// kinds actually connected: a forge CLI (gh/glab/tea) is installed and
// authenticated only when its forge kind is logged in, so advertising
// the full three-CLI catalog would point the agent at binaries that
// don't exist on this install.
func writeForges(w io.Writer, snap ForgeSnapshot) {
	if len(snap.Providers) == 0 {
		return
	}
	kinds := connectedKinds(snap)
	fmt.Fprintf(w, "## Connected forges\n\n")
	fmt.Fprintf(w, "Git operations (clone, push, pull, fetch) are pre-authenticated for all connected forges via git credential helpers configured at login. Just use plain `git` commands.\n\n")
	fmt.Fprintf(w, "For PRs, issues, releases, and CI status, prefer the official CLI tools — they expose the richest feature set per forge:\n\n")
	if kinds[kindGitHub] {
		fmt.Fprintf(w, "- GitHub: `gh pr|issue|release|run` (e.g. `gh pr create --title ... --body ...`)\n")
	}
	if kinds[kindGitLab] {
		fmt.Fprintf(w, "- GitLab: `glab mr|issue|release|ci`\n")
	}
	if kinds[kindGitea] || kinds[kindCodeberg] {
		fmt.Fprintf(w, "- Gitea / Codeberg: `tea pulls|issues|releases`\n")
	}
	fmt.Fprintf(w, "\nThese CLIs are pre-authenticated; no auth login or token setup needed.\n\n")
	for i := range snap.Providers {
		writeForgeProvider(w, &snap.Providers[i])
	}
}

// connectedKinds returns the set of forge kinds with a connected
// provider. Used to scope CLI hints (both the section above and the
// per-repo hints in writeRepoEntry) to CLIs that are actually
// installed and authenticated.
func connectedKinds(snap ForgeSnapshot) map[string]bool {
	kinds := make(map[string]bool, len(snap.Providers))
	for i := range snap.Providers {
		kinds[snap.Providers[i].Kind] = true
	}
	return kinds
}

// writeForgeProvider renders one connected forge: its auth line, CLI tool,
// clone hint, and (capped) accessible-repository list. p is taken by
// pointer to avoid copying the ~88-byte ForgeProvider value.
func writeForgeProvider(w io.Writer, p *ForgeProvider) {
	user := p.User
	if user == "" {
		user = "(authenticated)"
	}
	fmt.Fprintf(w, "### %s (%s)\n\n", p.Kind, p.Host)
	if p.Email != "" {
		fmt.Fprintf(w, "- Authenticated as: %s <%s>\n", user, p.Email)
	} else {
		fmt.Fprintf(w, "- Authenticated as: %s\n", user)
	}
	cli := forgeCLI(p.Kind)
	if cli != "" {
		fmt.Fprintf(w, "- CLI: `%s`\n", cli)
	}
	fmt.Fprintf(w, "- Clone via: `git clone https://%s/<owner>/<repo>.git`\n", p.Host)
	if len(p.Repos) > 0 {
		fmt.Fprintf(w, "- Accessible repositories:\n")
		n := min(len(p.Repos), 20)
		for _, r := range p.Repos[:n] {
			fmt.Fprintf(w, "  - %s\n", r)
		}
		if len(p.Repos) > 20 {
			fmt.Fprintf(w, "  - … and %d more\n", len(p.Repos)-20)
		}
	}
	fmt.Fprintln(w)
}

// forgeCLI returns the CLI tool for the kind. Mirrors forges.Kind.CLI()
// without requiring a dependency on the forges package.
func forgeCLI(kind string) string {
	switch kind {
	case kindGitHub:
		return "gh"
	case kindGitLab:
		return "glab"
	case kindGitea, kindCodeberg:
		return "tea"
	}
	return ""
}
