// Command wire-codegen generates TypeScript interfaces, validating decoders,
// and an SSE event→decoder registry from Go wire types using the wiregen
// library (AST-based; github.com/cplieger/wiregen/v2). Output lands in
// static-src/wire/ and feeds the client's typed SSE/REST decoding.
//
// Run: go run ./cmd/wire-codegen   (from the vibekit repo root)
package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/cplieger/vibekit/internal/api"
	"github.com/cplieger/vibekit/internal/auth"
	"github.com/cplieger/vibekit/internal/forges"
	"github.com/cplieger/wiregen/v2"
)

func main() {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("../validators.js"),
		// The validators module is library-owned generated output (wiregen
		// v2): Generate rewrites it next to the hand-written source on every
		// run. Never hand-edit it.
		wiregen.WithValidatorsFile("../validators.ts"),
		wiregen.WithBusImport("../bus.js"),
		wiregen.WithHeaderComment("// CODE-GENERATED by cmd/wire-codegen, DO NOT EDIT.\n\n"),
	)

	r.Types = []wiregen.WireType{
		wiregen.TypeRef[api.ToolLocation](),
		wiregen.TypeRef[api.ToolDiff](),
		wiregen.TypeRef[api.ToolCheckpoint](),
		wiregen.TypeRef[api.ToolCall](),
		wiregen.TypeRef[api.PlanEntry](),
		wiregen.TypeRef[api.Block](),
		wiregen.TypeRef[api.CodeReference](),
		wiregen.TypeRef[api.RefusalInfo](),
		wiregen.TypeRef[api.Message](),
		wiregen.TypeRef[api.MeteringItem](),
		wiregen.TypeRef[api.Usage](),
		wiregen.TypeRef[api.SessionMode](),
		wiregen.TypeRef[api.SessionModel](),
		wiregen.TypeRef[api.ChatHeader](),
		wiregen.TypeRef[api.PermissionOption](),
		wiregen.TypeRef[api.ApprovalFile](),
		wiregen.TypeRef[api.FileChange](),
		wiregen.TypeRef[api.ConnectedPayload](),
		wiregen.TypeRef[api.MessageChunkPayload](),
		wiregen.TypeRef[api.TurnEndedPayload](),
		wiregen.TypeRef[api.SteerQueuedPayload](),
		wiregen.TypeRef[api.SteerInjectedPayload](),
		wiregen.TypeRef[api.SteerClearedPayload](),
		wiregen.TypeRef[api.TurnStatePayload](),
		wiregen.TypeRef[api.PermissionNeededPayload](),
		wiregen.TypeRef[api.ErrorPayload](),
		wiregen.TypeRef[api.MCPConnectedPayload](),
		wiregen.TypeRef[api.MCPOAuthPayload](),
		wiregen.TypeRef[api.MCPFailedPayload](),
		wiregen.TypeRef[api.MCPDisconnectedPayload](),
		wiregen.TypeRef[api.ChatDeletedPayload](),
		wiregen.TypeRef[api.ToolCallPayload](),
		wiregen.TypeRef[api.ToolCallUpdatePayload](),
		wiregen.TypeRef[api.ElicitationPropertySchema](),
		wiregen.TypeRef[api.ElicitationRequestSchema](),
		wiregen.TypeRef[api.ElicitationNeededPayload](),
		wiregen.TypeRef[api.UserInputSubOption](),
		wiregen.TypeRef[api.UserInputOption](),
		wiregen.TypeRef[api.UserInputNeededPayload](),
		wiregen.TypeRef[api.DecisionSettledPayload](),
		wiregen.TypeRef[api.OpenExternalURLPayload](),
		wiregen.TypeRef[api.CodeReferencesPayload](),
		wiregen.TypeRef[api.AccountUsageBreakdown](),
		wiregen.TypeRef[api.AccountUsage](),
		wiregen.TypeRef[api.PolicyRuleCore](),
		wiregen.TypeRef[api.PolicyRule](),
		wiregen.TypeRef[api.PolicyView](),
		wiregen.TypeRef[api.PolicyExplainResult](),
		wiregen.TypeRef[api.PolicyErrorItem](),
		wiregen.TypeRef[api.PermissionsChangedPayload](),
		wiregen.TypeRef[api.PolicyErrorPayload](),
		wiregen.TypeRef[api.SafetyProperty](),
		wiregen.TypeRef[api.SafetyStatusPayload](),
		wiregen.TypeRef[api.SafetyPropertiesPayload](),
		wiregen.TypeRef[api.GovernanceFeatures](),
		wiregen.TypeRef[api.GovernanceStatePayload](),
		wiregen.TypeRef[api.ToolJob](),
		wiregen.TypeRef[api.ToolInfo](),
		wiregen.TypeRef[api.SystemTool](),
		wiregen.TypeRef[api.ToolsList](),
		wiregen.TypeRef[api.ToolCatalogHit](),
		wiregen.TypeRef[api.ToolsSearchResponse](),
		wiregen.TypeRef[api.ToolJobAccepted](),
		wiregen.TypeRef[api.ToolRemoveResponse](),
		wiregen.TypeRef[api.ToolsJobsResponse](),
		wiregen.TypeRef[api.ToolCatalogInfo](),
		wiregen.TypeRef[api.Recipe](),
		wiregen.TypeRef[api.RecipesResponse](),
		wiregen.TypeRef[api.RunLaunchRequest](),
		wiregen.TypeRef[api.RunLaunchedResponse](),
		wiregen.TypeRef[api.RunStartedPayload](),
		wiregen.TypeRef[api.RunProgressPayload](),
		wiregen.TypeRef[api.RunFinishedPayload](),
		wiregen.TypeRef[api.ToolJobChangedPayload](),
		wiregen.TypeRef[api.ToolJobOutputPayload](),
		wiregen.TypeRef[forges.ConfiguredForge](),
		wiregen.TypeRef[forges.Repo](),
		wiregen.TypeRef[forges.PR](),
		wiregen.TypeRef[forges.Issue](),
		wiregen.TypeRef[forges.Check](),
		wiregen.TypeRef[forges.Release](),
		wiregen.TypeRef[forges.Label](),
		wiregen.TypeRef[forges.User](),
		wiregen.TypeRef[forges.DeviceFlowResponse](),
		wiregen.TypeRef[forges.PollResult](),
		wiregen.TypeRef[auth.WhoamiResponse](),
	}

	// Enum values are auto-discovered from each type's const block in source.
	// Transport stays explicit: it lives in internal/mcp, which isn't a
	// registered-type (root) package, so discovery doesn't scan it.
	r.Enums = map[string]wiregen.EnumDef{
		"Role": {}, "EventKind": {}, "ToolKind": {}, "ToolStatus": {},
		"PlanStatus": {},
		"StopReason": {}, "ErrorCode": {}, "Kind": {}, // forges.Kind → ForgeKind
		"SafetyStatus":    {},
		"RunProgressKind": {},
		"DecisionKind":    {},
		"SettledBy":       {},
		"Transport":       {Values: []string{"stdio", "http", "sse"}},
	}

	r.EnumTSName = map[string]string{
		"Kind": "ForgeKind", // forges.Kind → ForgeKind in TS
	}

	// MCPOAuthPayload's acronym cluster (MCP+OAuth) can't be split
	// unambiguously, so its snake_case path is given explicitly.
	r.PathNameOverride = map[string]string{
		"MCPOAuthPayload": "mcp_oauth_payload",
		// URL acronym cluster can't be split unambiguously; pin the path.
		"OpenExternalURLPayload": "open_external_url_payload",
	}

	const typeMessage = "Message" // 3 SSE events decode to api.Message
	r.SSEEvents = []wiregen.SSERegEntry{
		{EventType: "chat_created", TypeName: "ChatHeader"},
		{EventType: "chat_deleted", TypeName: "ChatDeletedPayload"},
		{EventType: "chat_updated", TypeName: "ChatHeader"},
		{EventType: "code_references", TypeName: "CodeReferencesPayload"},
		{EventType: "connected", TypeName: "ConnectedPayload"},
		{EventType: "decision_settled", TypeName: "DecisionSettledPayload"},
		{EventType: "elicitation_needed", TypeName: "ElicitationNeededPayload"},
		{EventType: "user_input_needed", TypeName: "UserInputNeededPayload"},
		{EventType: "error", TypeName: "ErrorPayload"},
		{EventType: "governance_state", TypeName: "GovernanceStatePayload"},
		{EventType: "mcp_connected", TypeName: "MCPConnectedPayload"},
		{EventType: "mcp_disconnected", TypeName: "MCPDisconnectedPayload"},
		{EventType: "mcp_failed", TypeName: "MCPFailedPayload"},
		{EventType: "mcp_oauth_needed", TypeName: "MCPOAuthPayload"},
		{EventType: "message_appended", TypeName: typeMessage},
		{EventType: "message_chunk", TypeName: "MessageChunkPayload"},
		{EventType: "message_created", TypeName: typeMessage},
		{EventType: "message_updated", TypeName: typeMessage},
		{EventType: "open_external_url", TypeName: "OpenExternalURLPayload"},
		{EventType: "permission_needed", TypeName: "PermissionNeededPayload"},
		{EventType: "permissions_changed", TypeName: "PermissionsChangedPayload"},
		{EventType: "policy_error", TypeName: "PolicyErrorPayload"},
		{EventType: "run_started", TypeName: "RunStartedPayload"},
		{EventType: "run_progress", TypeName: "RunProgressPayload"},
		{EventType: "run_finished", TypeName: "RunFinishedPayload"},
		{EventType: "safety_properties", TypeName: "SafetyPropertiesPayload"},
		{EventType: "safety_status", TypeName: "SafetyStatusPayload"},
		{EventType: "tool_call", TypeName: "ToolCallPayload"},
		{EventType: "tool_call_update", TypeName: "ToolCallUpdatePayload"},
		{EventType: "tool_job_changed", TypeName: "ToolJobChangedPayload"},
		{EventType: "tool_job_output", TypeName: "ToolJobOutputPayload"},
		{EventType: "steer_queued", TypeName: "SteerQueuedPayload"},
		{EventType: "steer_injected", TypeName: "SteerInjectedPayload"},
		{EventType: "steer_cleared", TypeName: "SteerClearedPayload"},
		{EventType: "turn_ended", TypeName: "TurnEndedPayload"},
		{EventType: "turn_state", TypeName: "TurnStatePayload"},
	}

	outDir := filepath.Join("static-src", "wire")
	if err := r.Generate(outDir); err != nil {
		fmt.Fprintf(os.Stderr, "wire-codegen: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("wire-codegen: generated " + outDir + "/{types,decoders,registry}.gen.ts")
}
