// Command wire-codegen generates TypeScript interfaces, validating decoders,
// and an SSE event→decoder registry from Go wire types using the wiregen
// library (AST-based; github.com/cplieger/wiregen). Output lands in
// static-src/wire/ and feeds the client's typed SSE/REST decoding.
//
// Run: go run ./cmd/wire-codegen   (from the vibekit repo root)
package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/cplieger/vibekit/internal/api"
	"github.com/cplieger/vibekit/internal/auth"
	"github.com/cplieger/vibekit/internal/forges"
	"github.com/cplieger/wiregen"
)

func main() {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("../validators.js"),
		wiregen.WithBusImport("../bus.js"),
		wiregen.WithHeaderComment("// CODE-GENERATED by cmd/wire-codegen, DO NOT EDIT.\n\n"),
	)

	r.Types = []wiregen.WireType{
		wiregen.TypeRef[api.ToolLocation](),
		wiregen.TypeRef[api.ToolDiff](),
		wiregen.TypeRef[api.ToolCall](),
		wiregen.TypeRef[api.PlanEntry](),
		wiregen.TypeRef[api.Block](),
		wiregen.TypeRef[api.CrewSubagent](),
		wiregen.TypeRef[api.CrewPendingStage](),
		wiregen.TypeRef[api.Crew](),
		wiregen.TypeRef[api.Message](),
		wiregen.TypeRef[api.MeteringItem](),
		wiregen.TypeRef[api.Usage](),
		wiregen.TypeRef[api.SessionMode](),
		wiregen.TypeRef[api.SessionModel](),
		wiregen.TypeRef[api.ChatHeader](),
		wiregen.TypeRef[api.PermissionOption](),
		wiregen.TypeRef[api.PendingChange](),
		wiregen.TypeRef[api.FileChange](),
		wiregen.TypeRef[api.ConnectedPayload](),
		wiregen.TypeRef[api.MessageChunkPayload](),
		wiregen.TypeRef[api.TurnEndedPayload](),
		wiregen.TypeRef[api.PermissionNeededPayload](),
		wiregen.TypeRef[api.ErrorPayload](),
		wiregen.TypeRef[api.MCPConnectedPayload](),
		wiregen.TypeRef[api.MCPOAuthPayload](),
		wiregen.TypeRef[api.MCPFailedPayload](),
		wiregen.TypeRef[api.MCPDisconnectedPayload](),
		wiregen.TypeRef[api.PendingChangeAddedPayload](),
		wiregen.TypeRef[api.PendingChangeResolvedPayload](),
		wiregen.TypeRef[api.PendingChangesClearedPayload](),
		wiregen.TypeRef[api.ChatDeletedPayload](),
		wiregen.TypeRef[api.ToolCallPayload](),
		wiregen.TypeRef[api.ToolCallUpdatePayload](),
		wiregen.TypeRef[api.CommandsUpdatedPayload](),
		wiregen.TypeRef[api.AvailableCommand](),
		wiregen.TypeRef[api.ElicitationPropertySchema](),
		wiregen.TypeRef[api.ElicitationRequestSchema](),
		wiregen.TypeRef[api.ElicitationNeededPayload](),
		wiregen.TypeRef[api.ElicitationCompletePayload](),
		wiregen.TypeRef[forges.ConfiguredForge](),
		wiregen.TypeRef[forges.Repo](),
		wiregen.TypeRef[forges.PR](),
		wiregen.TypeRef[forges.Issue](),
		wiregen.TypeRef[forges.Check](),
		wiregen.TypeRef[forges.Release](),
		wiregen.TypeRef[forges.Label](),
		wiregen.TypeRef[forges.User](),
		wiregen.TypeRef[forges.DeviceFlowResponse](),
		wiregen.TypeRef[forges.PollResult](),
		wiregen.TypeRef[auth.WhoamiResponse](),
	}

	// Enum values are auto-discovered from each type's const block in source.
	// Transport stays explicit: it lives in internal/mcp, which isn't a
	// registered-type (root) package, so discovery doesn't scan it.
	r.Enums = map[string]wiregen.EnumDef{
		"Role": {}, "EventKind": {}, "ToolKind": {}, "ToolStatus": {},
		"PlanStatus": {}, "CrewStatus": {}, "PendingChangeKind": {},
		"StopReason": {}, "ErrorCode": {}, "Kind": {}, // forges.Kind → ForgeKind
		"PendingAction": {}, "ClearReason": {},
		"Transport": {Values: []string{"stdio", "http"}},
	}

	r.EnumTSName = map[string]string{
		"Kind": "ForgeKind", // forges.Kind → ForgeKind in TS
	}

	// MCPOAuthPayload's acronym cluster (MCP+OAuth) can't be split
	// unambiguously, so its snake_case path is given explicitly.
	r.PathNameOverride = map[string]string{
		"MCPOAuthPayload": "mcp_oauth_payload",
	}

	r.SSEEvents = []wiregen.SSERegEntry{
		{EventType: "chat_created", TypeName: "ChatHeader"},
		{EventType: "chat_deleted", TypeName: "ChatDeletedPayload"},
		{EventType: "chat_updated", TypeName: "ChatHeader"},
		{EventType: "commands_updated", TypeName: "CommandsUpdatedPayload"},
		{EventType: "connected", TypeName: "ConnectedPayload"},
		{EventType: "elicitation_complete", TypeName: "ElicitationCompletePayload"},
		{EventType: "elicitation_needed", TypeName: "ElicitationNeededPayload"},
		{EventType: "error", TypeName: "ErrorPayload"},
		{EventType: "mcp_connected", TypeName: "MCPConnectedPayload"},
		{EventType: "mcp_disconnected", TypeName: "MCPDisconnectedPayload"},
		{EventType: "mcp_failed", TypeName: "MCPFailedPayload"},
		{EventType: "mcp_oauth_needed", TypeName: "MCPOAuthPayload"},
		{EventType: "message_appended", TypeName: "Message"},
		{EventType: "message_chunk", TypeName: "MessageChunkPayload"},
		{EventType: "message_created", TypeName: "Message"},
		{EventType: "message_updated", TypeName: "Message"},
		{EventType: "pending_change_added", TypeName: "PendingChangeAddedPayload"},
		{EventType: "pending_change_resolved", TypeName: "PendingChangeResolvedPayload"},
		{EventType: "pending_changes_cleared", TypeName: "PendingChangesClearedPayload"},
		{EventType: "permission_needed", TypeName: "PermissionNeededPayload"},
		{EventType: "tool_call", TypeName: "ToolCallPayload"},
		{EventType: "tool_call_update", TypeName: "ToolCallUpdatePayload"},
		{EventType: "turn_ended", TypeName: "TurnEndedPayload"},
	}

	outDir := filepath.Join("static-src", "wire")
	if err := r.Generate(outDir); err != nil {
		fmt.Fprintf(os.Stderr, "wire-codegen: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("wire-codegen: generated " + outDir + "/{types,decoders,registry}.gen.ts")
}
