// CODE-GENERATED by cmd/wire-codegen, DO NOT EDIT.

export type ClearReason =
  | "turn_ended"
  | "cancelled"
  | "mode_disabled"
  | "chat_deleted"
  | "shutdown"
  | "user_cleared";

export type CrewStatus = "working" | "terminated" | "error" | "pending";

export type ErrorCode =
  | "recovery_failed"
  | "bridge_start_failed"
  | "prompt_failed"
  | "agent_not_found"
  | "model_not_found"
  | "agent_config_error"
  | "rate_limit"
  | "stream_timeout"
  | "spawn_failed"
  | "switch_failed"
  | "compaction_failed";

export type EventKind =
  | "interrupted"
  | "cancelled"
  | "model_switched"
  | "compacted"
  | "crew"
  | "agent_switched"
  | "compaction_failed"
  | "inbox";

export type ForgeKind = "github" | "gitlab" | "codeberg" | "gitea";

export type PendingAction = "accept" | "reject";

export type PendingChangeKind = "create" | "edit" | "delete";

export type PlanStatus = "pending" | "in_progress" | "completed";

export type Role = "user" | "assistant" | "event";

export type StopReason = "end_turn" | "cancelled" | "interrupted";

export type ToolKind =
  | "execute"
  | "shell"
  | "read"
  | "search"
  | "fetch"
  | "edit"
  | "think"
  | "hook"
  | "write"
  | "delete"
  | "move"
  | "command"
  | "browser"
  | "switch_mode"
  | "mcp"
  | "other";

export type ToolStatus = "pending" | "in_progress" | "completed" | "failed";

export type Transport = "stdio" | "http";

export interface AvailableCommand {
  meta?: Record<string, unknown>;
  name: string;
  description?: string;
}

export interface ChatDeletedPayload {
  id: string;
}

export interface ChatHeader {
  parent_chat_id?: string;
  name: string;
  agent?: string;
  model?: string;
  acp_session_id?: string;
  current_mode_id?: string;
  id: string;
  compaction_watermark?: string;
  oldest_checkpoint_tag?: string;
  summary?: string;
  available_models?: SessionModel[];
  available_modes?: SessionMode[];
  usage: Usage;
  created_at: number;
  updated_at: number;
  message_count: number;
  supervised_mode?: boolean;
  auto_approve_crew?: boolean;
}

export interface Check {
  name: string;
  status: string;
  conclusion: string;
  url?: string;
}

export interface CommandsUpdatedPayload {
  commands: AvailableCommand[];
  prompts?: AvailableCommand[];
}

export interface ConfiguredForge {
  id: string;
  kind: ForgeKind;
  host: string;
  username?: string;
  email?: string;
  last_error?: string;
  last_probed?: number;
  connected: boolean;
}

export interface ConnectedPayload {
  floor: number;
  head: number;
}

export interface Crew {
  group: string;
  subagents: CrewSubagent[];
  pending_stages?: CrewPendingStage[];
}

export interface CrewPendingStage {
  name: string;
  agent_name: string;
  role?: string;
  depends_on?: string[];
}

export interface CrewSubagent {
  session_id: string;
  session_name: string;
  agent_name: string;
  initial_query: string;
  status: CrewStatus;
  status_msg?: string;
  group: string;
  role?: string;
  depends_on?: string[];
}

export interface DeviceFlowResponse {
  user_code: string;
  verification_uri: string;
  device_code: string;
  interval: number;
  expires_in: number;
}

export interface ErrorPayload {
  code: ErrorCode;
  message: string;
}

export interface FileChange {
  lines_added: number;
  lines_removed: number;
  is_new_file?: boolean;
}

export interface Issue {
  title: string;
  body?: string;
  state: string;
  author?: string;
  url?: string;
  labels?: string[];
  number: number;
  created_at?: number;
  updated_at?: number;
}

export interface Label {
  name: string;
  color?: string;
  description?: string;
}

export interface MCPConnectedPayload {
  server: string;
}

export interface MCPDisconnectedPayload {
  server: string;
}

export interface MCPFailedPayload {
  server: string;
  error: string;
}

export interface MCPOAuthPayload {
  server: string;
  url: string;
}

export interface Message {
  crew?: Crew;
  id: string;
  role: Role;
  content?: string;
  reasoning?: string;
  event_kind?: EventKind;
  tool_calls?: ToolCall[];
  plan?: PlanEntry[];
  ts: number;
}

export interface MessageChunkPayload {
  message_id: string;
  delta: string;
  is_reasoning?: boolean;
}

export interface MeteringItem {
  unit_singular: string;
  unit_plural: string;
  value: number;
}

export interface PR {
  title: string;
  body?: string;
  state: string;
  author?: string;
  source_branch: string;
  target_branch: string;
  url?: string;
  number: number;
  created_at?: number;
  updated_at?: number;
  mergeable?: boolean;
  draft?: boolean;
}

export interface PendingChange {
  tool_call_id: string;
  chat_id: string;
  path: string;
  kind: PendingChangeKind;
  old_text?: string;
  new_text?: string;
  created_at: number;
  truncated?: boolean;
}

export interface PendingChangeAddedPayload {
  change: PendingChange;
}

export interface PendingChangeResolvedPayload {
  tool_call_id: string;
  action: PendingAction;
  path?: string;
}

export interface PendingChangesClearedPayload {
  reason?: ClearReason;
}

export interface PermissionNeededPayload {
  tool_call_id?: string;
  title?: string;
  kind?: ToolKind;
  sub_session_id?: string;
  options: PermissionOption[];
  request_id: number;
}

export interface PermissionOption {
  option_id: string;
  name: string;
  kind: string;
}

export interface PlanEntry {
  content: string;
  priority: string;
  status: PlanStatus;
}

export interface PollResult {
  status: string;
  error?: string;
}

export interface Release {
  tag_name: string;
  name?: string;
  body?: string;
  url?: string;
  published_at?: number;
  draft?: boolean;
  prerelease?: boolean;
}

export interface Repo {
  owner: string;
  name: string;
  full_name: string;
  default_branch?: string;
  url?: string;
  clone_url?: string;
  description?: string;
  private?: boolean;
  archived?: boolean;
  fork?: boolean;
  updated_at?: number;
}

export interface SessionMode {
  id: string;
  name: string;
  description?: string;
}

export interface SessionModel {
  id: string;
  name: string;
  description?: string;
  rate_multiplier?: number;
}

export interface ToolCall {
  id: string;
  title: string;
  kind: ToolKind;
  status: ToolStatus;
  output?: string;
  sub_session_id?: string;
  input?: unknown;
  locations?: ToolLocation[];
  diffs?: ToolDiff[];
  duration_ms?: number;
  ts: number;
}

export interface ToolCallPayload {
  message_id: string;
  tool_call: ToolCall;
}

export interface ToolCallUpdatePayload {
  message_id: string;
  tool_call: ToolCall;
}

export interface ToolDiff {
  path: string;
  old_text?: string;
  new_text: string;
}

export interface ToolLocation {
  path: string;
  line?: number;
}

export interface TurnEndedPayload {
  changed_files?: Record<string, FileChange>;
  stop_reason?: StopReason;
  credits_delta?: number;
  elapsed_ms?: number;
}

export interface Usage {
  metering_items?: MeteringItem[];
  context_pct: number;
  context_size: number;
  credits: number;
  turn_count: number;
  last_turn_ms: number;
  has_real_data: boolean;
}

export interface User {
  login: string;
  name?: string;
  email?: string;
  url?: string;
}

export interface WhoamiResponse {
  email?: string;
  auth?: string;
  accountType?: string;
  startUrl?: string;
  region?: string;
  error?: string;
}
