// CODE-GENERATED by cmd/wire-codegen, DO NOT EDIT.

import { asObject, reqStr, reqNum, reqBool, optStr, optNum, optBool, reqOneOf, decodeArray, decodeRecord, type Decoder } from "../validators.js";
import type { AccountUsage, AccountUsageBreakdown, ApprovalFile, Block, CatalogInfo, ChatDeletedPayload, ChatHeader, Check, CodeReference, CodeReferencesPayload, ConfiguredForge, ConnectedPayload, DeviceFlowResponse, ElicitationNeededPayload, ElicitationPropertySchema, ElicitationRequestSchema, ErrorPayload, FileChange, GovernanceFeatures, GovernanceStatePayload, Inventory, Issue, Job, JobResponse, JobsResponse, Label, MCPConnectedPayload, MCPDisconnectedPayload, MCPFailedPayload, MCPOAuthPayload, Message, MessageChunkPayload, MeteringItem, OpenExternalURLPayload, PR, PermissionNeededPayload, PermissionOption, PermissionsChangedPayload, PlanEntry, PolicyErrorItem, PolicyErrorPayload, PolicyExplainResult, PolicyRule, PolicyRuleCore, PolicyView, PollResult, RefusalInfo, Release, RemoveResponse, Repo, RunFinishedPayload, RunProgressPayload, RunStartedPayload, SafetyPropertiesPayload, SafetyProperty, SafetyStatusPayload, SearchHit, SearchResponse, SessionMode, SessionModel, SystemTool, ToolCall, ToolCallPayload, ToolCallUpdatePayload, ToolCheckpoint, ToolDiff, ToolInfo, ToolJobChangedPayload, ToolJobOutputPayload, ToolLocation, TurnEndedPayload, TurnStatePayload, Usage, User, UserInputNeededPayload, UserInputOption, UserInputSubOption, WhoamiResponse } from "./types.gen.js";

const ERROR_CODES = ["recovery_failed", "bridge_start_failed", "prompt_failed", "agent_not_found", "agent_config_error", "rate_limit", "stream_timeout", "spawn_failed", "switch_failed", "compaction_failed"] as const;
const EVENT_KINDS = ["interrupted", "cancelled", "model_switched", "compacted", "compaction_failed", "infra_safety_blocked"] as const;
const FORGE_KINDS = ["github", "gitlab", "gitea", "codeberg"] as const;
const PLAN_STATUSS = ["pending", "in_progress", "completed"] as const;
const ROLES = ["user", "assistant", "event"] as const;
const RUN_PROGRESS_KINDS = ["node_start", "node_complete", "node_paused", "loop_iteration", "watch_poll", "paused", "steps_queued"] as const;
const SAFETY_STATUSS = ["idle", "formalizing", "evaluating", "blocked", "error"] as const;
const STOP_REASONS = ["end_turn", "cancelled", "interrupted", "refusal"] as const;
const TOOL_KINDS = ["execute", "shell", "read", "search", "fetch", "edit", "think", "hook", "write", "delete", "move", "command", "browser", "switch_mode", "mcp", "other"] as const;
const TOOL_STATUSS = ["pending", "in_progress", "completed", "failed"] as const;

export const decodeAccountUsage: Decoder<AccountUsage> = (v) => {
  const o = asObject(v, "$.account_usage");
  const out: AccountUsage = {
    breakdowns: o["breakdowns"] === null ? [] : decodeArray(o["breakdowns"], decodeAccountUsageBreakdown, "$.account_usage.breakdowns"),
  };
  const planName = o["plan_name"] === null ? undefined : optStr(o, "plan_name", "$.account_usage");
  if (planName !== undefined) out.plan_name = planName;
  const billingCycleReset = o["billing_cycle_reset"] === null ? undefined : optStr(o, "billing_cycle_reset", "$.account_usage");
  if (billingCycleReset !== undefined) out.billing_cycle_reset = billingCycleReset;
  const fetchedAt = o["fetched_at"] === null ? undefined : optStr(o, "fetched_at", "$.account_usage");
  if (fetchedAt !== undefined) out.fetched_at = fetchedAt;
  const note = o["note"] === null ? undefined : optStr(o, "note", "$.account_usage");
  if (note !== undefined) out.note = note;
  const isEnterprise = o["is_enterprise"] === null ? undefined : optBool(o, "is_enterprise", "$.account_usage");
  if (isEnterprise !== undefined) out.is_enterprise = isEnterprise;
  const overagesEnabled = o["overages_enabled"] === null ? undefined : optBool(o, "overages_enabled", "$.account_usage");
  if (overagesEnabled !== undefined) out.overages_enabled = overagesEnabled;
  const stale = o["stale"] === null ? undefined : optBool(o, "stale", "$.account_usage");
  if (stale !== undefined) out.stale = stale;
  return out;
};

export const decodeAccountUsageBreakdown: Decoder<AccountUsageBreakdown> = (v) => {
  const o = asObject(v, "$.account_usage_breakdown");
  const out: AccountUsageBreakdown = {
    used: reqNum(o, "used", "$.account_usage_breakdown"),
    limit: reqNum(o, "limit", "$.account_usage_breakdown"),
    percentage: reqNum(o, "percentage", "$.account_usage_breakdown"),
  };
  const resourceType = o["resource_type"] === null ? undefined : optStr(o, "resource_type", "$.account_usage_breakdown");
  if (resourceType !== undefined) out.resource_type = resourceType;
  const displayName = o["display_name"] === null ? undefined : optStr(o, "display_name", "$.account_usage_breakdown");
  if (displayName !== undefined) out.display_name = displayName;
  const currency = o["currency"] === null ? undefined : optStr(o, "currency", "$.account_usage_breakdown");
  if (currency !== undefined) out.currency = currency;
  const currentOverages = o["current_overages"] === null ? undefined : optNum(o, "current_overages", "$.account_usage_breakdown");
  if (currentOverages !== undefined) out.current_overages = currentOverages;
  const overageCharges = o["overage_charges"] === null ? undefined : optNum(o, "overage_charges", "$.account_usage_breakdown");
  if (overageCharges !== undefined) out.overage_charges = overageCharges;
  const hasLimit = o["has_limit"] === null ? undefined : optBool(o, "has_limit", "$.account_usage_breakdown");
  if (hasLimit !== undefined) out.has_limit = hasLimit;
  return out;
};

export const decodeApprovalFile: Decoder<ApprovalFile> = (v) => {
  const o = asObject(v, "$.approval_file");
  const out: ApprovalFile = {
    path: reqStr(o, "path", "$.approval_file"),
    action_id: reqStr(o, "action_id", "$.approval_file"),
  };
  const snapshotUri = o["snapshot_uri"] === null ? undefined : optStr(o, "snapshot_uri", "$.approval_file");
  if (snapshotUri !== undefined) out.snapshot_uri = snapshotUri;
  return out;
};

export const decodeBlock: Decoder<Block> = (v) => {
  const o = asObject(v, "$.block");
  const out: Block = {
    type: reqStr(o, "type", "$.block"),
  };
  const text = o["text"] === null ? undefined : optStr(o, "text", "$.block");
  if (text !== undefined) out.text = text;
  const thinking = o["thinking"] === null ? undefined : optStr(o, "thinking", "$.block");
  if (thinking !== undefined) out.thinking = thinking;
  const toolCallId = o["tool_call_id"] === null ? undefined : optStr(o, "tool_call_id", "$.block");
  if (toolCallId !== undefined) out.tool_call_id = toolCallId;
  const agentSubtaskId = o["agent_subtask_id"] === null ? undefined : optStr(o, "agent_subtask_id", "$.block");
  if (agentSubtaskId !== undefined) out.agent_subtask_id = agentSubtaskId;
  return out;
};

export const decodeCatalogInfo: Decoder<CatalogInfo> = (v) => {
  const o = asObject(v, "$.catalog_info");
  const out: CatalogInfo = {
    source: reqStr(o, "source", "$.catalog_info"),
    entries: reqNum(o, "entries", "$.catalog_info"),
    scheduled: reqBool(o, "scheduled", "$.catalog_info"),
  };
  if (o["refs"] !== undefined && o["refs"] !== null) out.refs = decodeRecord(o["refs"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.catalog_info.refs");
  const generated = o["generated"] === null ? undefined : optStr(o, "generated", "$.catalog_info");
  if (generated !== undefined) out.generated = generated;
  const url = o["url"] === null ? undefined : optStr(o, "url", "$.catalog_info");
  if (url !== undefined) out.url = url;
  const lastError = o["last_error"] === null ? undefined : optStr(o, "last_error", "$.catalog_info");
  if (lastError !== undefined) out.last_error = lastError;
  const fetchedAt = o["fetched_at"] === null ? undefined : optNum(o, "fetched_at", "$.catalog_info");
  if (fetchedAt !== undefined) out.fetched_at = fetchedAt;
  return out;
};

export const decodeChatDeletedPayload: Decoder<ChatDeletedPayload> = (v) => {
  const o = asObject(v, "$.chat_deleted_payload");
  const out: ChatDeletedPayload = {
    id: reqStr(o, "id", "$.chat_deleted_payload"),
  };
  return out;
};

export const decodeChatHeader: Decoder<ChatHeader> = (v) => {
  const o = asObject(v, "$.chat_header");
  const out: ChatHeader = {
    name: reqStr(o, "name", "$.chat_header"),
    id: reqStr(o, "id", "$.chat_header"),
    usage: decodeUsage(o["usage"]),
    created_at: reqNum(o, "created_at", "$.chat_header"),
    updated_at: reqNum(o, "updated_at", "$.chat_header"),
    message_count: reqNum(o, "message_count", "$.chat_header"),
  };
  const model = o["model"] === null ? undefined : optStr(o, "model", "$.chat_header");
  if (model !== undefined) out.model = model;
  const acpSessionId = o["acp_session_id"] === null ? undefined : optStr(o, "acp_session_id", "$.chat_header");
  if (acpSessionId !== undefined) out.acp_session_id = acpSessionId;
  const currentModeId = o["current_mode_id"] === null ? undefined : optStr(o, "current_mode_id", "$.chat_header");
  if (currentModeId !== undefined) out.current_mode_id = currentModeId;
  const compactionWatermark = o["compaction_watermark"] === null ? undefined : optStr(o, "compaction_watermark", "$.chat_header");
  if (compactionWatermark !== undefined) out.compaction_watermark = compactionWatermark;
  if (o["available_models"] !== undefined && o["available_models"] !== null) out.available_models = decodeArray(o["available_models"], decodeSessionModel, "$.chat_header.available_models");
  if (o["available_modes"] !== undefined && o["available_modes"] !== null) out.available_modes = decodeArray(o["available_modes"], decodeSessionMode, "$.chat_header.available_modes");
  if (o["prior_acp_session_ids"] !== undefined && o["prior_acp_session_ids"] !== null) out.prior_acp_session_ids = decodeArray(o["prior_acp_session_ids"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.chat_header.prior_acp_session_ids");
  const supervisedMode = o["supervised_mode"] === null ? undefined : optBool(o, "supervised_mode", "$.chat_header");
  if (supervisedMode !== undefined) out.supervised_mode = supervisedMode;
  return out;
};

export const decodeCheck: Decoder<Check> = (v) => {
  const o = asObject(v, "$.check");
  const out: Check = {
    name: reqStr(o, "name", "$.check"),
    status: reqStr(o, "status", "$.check"),
    conclusion: reqStr(o, "conclusion", "$.check"),
  };
  const url = o["url"] === null ? undefined : optStr(o, "url", "$.check");
  if (url !== undefined) out.url = url;
  return out;
};

export const decodeCodeReference: Decoder<CodeReference> = (v) => {
  const o = asObject(v, "$.code_reference");
  const out: CodeReference = {
    license_name: reqStr(o, "license_name", "$.code_reference"),
  };
  const repository = o["repository"] === null ? undefined : optStr(o, "repository", "$.code_reference");
  if (repository !== undefined) out.repository = repository;
  const url = o["url"] === null ? undefined : optStr(o, "url", "$.code_reference");
  if (url !== undefined) out.url = url;
  return out;
};

export const decodeCodeReferencesPayload: Decoder<CodeReferencesPayload> = (v) => {
  const o = asObject(v, "$.code_references_payload");
  const out: CodeReferencesPayload = {
    message_id: reqStr(o, "message_id", "$.code_references_payload"),
    references: o["references"] === null ? [] : decodeArray(o["references"], decodeCodeReference, "$.code_references_payload.references"),
  };
  return out;
};

export const decodeConfiguredForge: Decoder<ConfiguredForge> = (v) => {
  const o = asObject(v, "$.configured_forge");
  const out: ConfiguredForge = {
    id: reqStr(o, "id", "$.configured_forge"),
    kind: reqOneOf(o, "kind", FORGE_KINDS, "$.configured_forge"),
    host: reqStr(o, "host", "$.configured_forge"),
    connected: reqBool(o, "connected", "$.configured_forge"),
  };
  const username = o["username"] === null ? undefined : optStr(o, "username", "$.configured_forge");
  if (username !== undefined) out.username = username;
  const email = o["email"] === null ? undefined : optStr(o, "email", "$.configured_forge");
  if (email !== undefined) out.email = email;
  const lastError = o["last_error"] === null ? undefined : optStr(o, "last_error", "$.configured_forge");
  if (lastError !== undefined) out.last_error = lastError;
  const lastProbed = o["last_probed"] === null ? undefined : optNum(o, "last_probed", "$.configured_forge");
  if (lastProbed !== undefined) out.last_probed = lastProbed;
  const cliMissing = o["cli_missing"] === null ? undefined : optBool(o, "cli_missing", "$.configured_forge");
  if (cliMissing !== undefined) out.cli_missing = cliMissing;
  return out;
};

export const decodeConnectedPayload: Decoder<ConnectedPayload> = (v) => {
  const o = asObject(v, "$.connected_payload");
  const out: ConnectedPayload = {
    floor: reqNum(o, "floor", "$.connected_payload"),
    head: reqNum(o, "head", "$.connected_payload"),
  };
  return out;
};

export const decodeDeviceFlowResponse: Decoder<DeviceFlowResponse> = (v) => {
  const o = asObject(v, "$.device_flow_response");
  const out: DeviceFlowResponse = {
    user_code: reqStr(o, "user_code", "$.device_flow_response"),
    verification_uri: reqStr(o, "verification_uri", "$.device_flow_response"),
    device_code: reqStr(o, "device_code", "$.device_flow_response"),
    interval: reqNum(o, "interval", "$.device_flow_response"),
    expires_in: reqNum(o, "expires_in", "$.device_flow_response"),
  };
  return out;
};

export const decodeElicitationNeededPayload: Decoder<ElicitationNeededPayload> = (v) => {
  const o = asObject(v, "$.elicitation_needed_payload");
  const out: ElicitationNeededPayload = {
    request_id: reqNum(o, "request_id", "$.elicitation_needed_payload"),
  };
  if (o["requested_schema"] !== undefined && o["requested_schema"] !== null) out.requested_schema = decodeElicitationRequestSchema(o["requested_schema"]);
  const mode = o["mode"] === null ? undefined : optStr(o, "mode", "$.elicitation_needed_payload");
  if (mode !== undefined) out.mode = mode;
  const message = o["message"] === null ? undefined : optStr(o, "message", "$.elicitation_needed_payload");
  if (message !== undefined) out.message = message;
  const url = o["url"] === null ? undefined : optStr(o, "url", "$.elicitation_needed_payload");
  if (url !== undefined) out.url = url;
  const toolCallId = o["tool_call_id"] === null ? undefined : optStr(o, "tool_call_id", "$.elicitation_needed_payload");
  if (toolCallId !== undefined) out.tool_call_id = toolCallId;
  const subSessionId = o["sub_session_id"] === null ? undefined : optStr(o, "sub_session_id", "$.elicitation_needed_payload");
  if (subSessionId !== undefined) out.sub_session_id = subSessionId;
  return out;
};

export const decodeElicitationPropertySchema: Decoder<ElicitationPropertySchema> = (v) => {
  const o = asObject(v, "$.elicitation_property_schema");
  const out: ElicitationPropertySchema = {
    type: reqStr(o, "type", "$.elicitation_property_schema"),
  };
  if (o["default"] !== undefined) out.default = o["default"] as unknown;
  const minLength = o["minLength"] === null ? undefined : optNum(o, "minLength", "$.elicitation_property_schema");
  if (minLength !== undefined) out.minLength = minLength;
  const maxLength = o["maxLength"] === null ? undefined : optNum(o, "maxLength", "$.elicitation_property_schema");
  if (maxLength !== undefined) out.maxLength = maxLength;
  const title = o["title"] === null ? undefined : optStr(o, "title", "$.elicitation_property_schema");
  if (title !== undefined) out.title = title;
  const description = o["description"] === null ? undefined : optStr(o, "description", "$.elicitation_property_schema");
  if (description !== undefined) out.description = description;
  const format = o["format"] === null ? undefined : optStr(o, "format", "$.elicitation_property_schema");
  if (format !== undefined) out.format = format;
  const pattern = o["pattern"] === null ? undefined : optStr(o, "pattern", "$.elicitation_property_schema");
  if (pattern !== undefined) out.pattern = pattern;
  if (o["enum"] !== undefined && o["enum"] !== null) out.enum = decodeArray(o["enum"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.elicitation_property_schema.enum");
  return out;
};

export const decodeElicitationRequestSchema: Decoder<ElicitationRequestSchema> = (v) => {
  const o = asObject(v, "$.elicitation_request_schema");
  const out: ElicitationRequestSchema = {
  };
  const type = o["type"] === null ? undefined : optStr(o, "type", "$.elicitation_request_schema");
  if (type !== undefined) out.type = type;
  const title = o["title"] === null ? undefined : optStr(o, "title", "$.elicitation_request_schema");
  if (title !== undefined) out.title = title;
  const description = o["description"] === null ? undefined : optStr(o, "description", "$.elicitation_request_schema");
  if (description !== undefined) out.description = description;
  if (o["properties"] !== undefined && o["properties"] !== null) out.properties = decodeRecord(o["properties"], decodeElicitationPropertySchema, "$.elicitation_request_schema.properties");
  if (o["required"] !== undefined && o["required"] !== null) out.required = decodeArray(o["required"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.elicitation_request_schema.required");
  return out;
};

export const decodeErrorPayload: Decoder<ErrorPayload> = (v) => {
  const o = asObject(v, "$.error_payload");
  const out: ErrorPayload = {
    code: reqOneOf(o, "code", ERROR_CODES, "$.error_payload"),
    message: reqStr(o, "message", "$.error_payload"),
  };
  return out;
};

export const decodeFileChange: Decoder<FileChange> = (v) => {
  const o = asObject(v, "$.file_change");
  const out: FileChange = {
    lines_added: reqNum(o, "lines_added", "$.file_change"),
    lines_removed: reqNum(o, "lines_removed", "$.file_change"),
  };
  const isNewFile = o["is_new_file"] === null ? undefined : optBool(o, "is_new_file", "$.file_change");
  if (isNewFile !== undefined) out.is_new_file = isNewFile;
  return out;
};

export const decodeGovernanceFeatures: Decoder<GovernanceFeatures> = (v) => {
  const o = asObject(v, "$.governance_features");
  const out: GovernanceFeatures = {
    mcp_enabled: reqBool(o, "mcp_enabled", "$.governance_features"),
    web_tools_enabled: reqBool(o, "web_tools_enabled", "$.governance_features"),
    usage_analytics: reqBool(o, "usage_analytics", "$.governance_features"),
    content_collection: reqBool(o, "content_collection", "$.governance_features"),
    prompt_logging: reqBool(o, "prompt_logging", "$.governance_features"),
    code_reference_tracker: reqBool(o, "code_reference_tracker", "$.governance_features"),
    autonomous_agents: reqBool(o, "autonomous_agents", "$.governance_features"),
  };
  return out;
};

export const decodeGovernanceStatePayload: Decoder<GovernanceStatePayload> = (v) => {
  const o = asObject(v, "$.governance_state_payload");
  const out: GovernanceStatePayload = {
    features: decodeGovernanceFeatures(o["features"]),
    known: reqBool(o, "known", "$.governance_state_payload"),
  };
  const disabledReason = o["disabled_reason"] === null ? undefined : optStr(o, "disabled_reason", "$.governance_state_payload");
  if (disabledReason !== undefined) out.disabled_reason = disabledReason;
  const isEnterprise = o["is_enterprise"] === null ? undefined : optBool(o, "is_enterprise", "$.governance_state_payload");
  if (isEnterprise !== undefined) out.is_enterprise = isEnterprise;
  return out;
};

export const decodeInventory: Decoder<Inventory> = (v) => {
  const o = asObject(v, "$.inventory");
  const out: Inventory = {
    tools: o["tools"] === null ? [] : decodeArray(o["tools"], decodeToolInfo, "$.inventory.tools"),
    system: o["system"] === null ? [] : decodeArray(o["system"], decodeSystemTool, "$.inventory.system"),
  };
  if (o["job"] !== undefined && o["job"] !== null) out.job = decodeJob(o["job"]);
  return out;
};

export const decodeIssue: Decoder<Issue> = (v) => {
  const o = asObject(v, "$.issue");
  const out: Issue = {
    title: reqStr(o, "title", "$.issue"),
    state: reqStr(o, "state", "$.issue"),
    number: reqNum(o, "number", "$.issue"),
  };
  const body = o["body"] === null ? undefined : optStr(o, "body", "$.issue");
  if (body !== undefined) out.body = body;
  const author = o["author"] === null ? undefined : optStr(o, "author", "$.issue");
  if (author !== undefined) out.author = author;
  const url = o["url"] === null ? undefined : optStr(o, "url", "$.issue");
  if (url !== undefined) out.url = url;
  if (o["labels"] !== undefined && o["labels"] !== null) out.labels = decodeArray(o["labels"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.issue.labels");
  const createdAt = o["created_at"] === null ? undefined : optNum(o, "created_at", "$.issue");
  if (createdAt !== undefined) out.created_at = createdAt;
  const updatedAt = o["updated_at"] === null ? undefined : optNum(o, "updated_at", "$.issue");
  if (updatedAt !== undefined) out.updated_at = updatedAt;
  return out;
};

export const decodeJob: Decoder<Job> = (v) => {
  const o = asObject(v, "$.job");
  const out: Job = {
    id: reqStr(o, "id", "$.job"),
    kind: reqStr(o, "kind", "$.job"),
    state: reqStr(o, "state", "$.job"),
    created_at: reqNum(o, "created_at", "$.job"),
  };
  const error = o["error"] === null ? undefined : optStr(o, "error", "$.job");
  if (error !== undefined) out.error = error;
  if (o["names"] !== undefined && o["names"] !== null) out.names = decodeArray(o["names"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.job.names");
  if (o["output_tail"] !== undefined && o["output_tail"] !== null) out.output_tail = decodeArray(o["output_tail"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.job.output_tail");
  const startedAt = o["started_at"] === null ? undefined : optNum(o, "started_at", "$.job");
  if (startedAt !== undefined) out.started_at = startedAt;
  const endedAt = o["ended_at"] === null ? undefined : optNum(o, "ended_at", "$.job");
  if (endedAt !== undefined) out.ended_at = endedAt;
  return out;
};

export const decodeJobResponse: Decoder<JobResponse> = (v) => {
  const o = asObject(v, "$.job_response");
  const out: JobResponse = {
  };
  if (o["job"] !== undefined && o["job"] !== null) out.job = decodeJob(o["job"]);
  return out;
};

export const decodeJobsResponse: Decoder<JobsResponse> = (v) => {
  const o = asObject(v, "$.jobs_response");
  const out: JobsResponse = {
    recent: o["recent"] === null ? [] : decodeArray(o["recent"], decodeJob, "$.jobs_response.recent"),
  };
  if (o["active"] !== undefined && o["active"] !== null) out.active = decodeJob(o["active"]);
  return out;
};

export const decodeLabel: Decoder<Label> = (v) => {
  const o = asObject(v, "$.label");
  const out: Label = {
    name: reqStr(o, "name", "$.label"),
  };
  const color = o["color"] === null ? undefined : optStr(o, "color", "$.label");
  if (color !== undefined) out.color = color;
  const description = o["description"] === null ? undefined : optStr(o, "description", "$.label");
  if (description !== undefined) out.description = description;
  return out;
};

export const decodeMCPConnectedPayload: Decoder<MCPConnectedPayload> = (v) => {
  const o = asObject(v, "$.mcp_connected_payload");
  const out: MCPConnectedPayload = {
    server: reqStr(o, "server", "$.mcp_connected_payload"),
  };
  return out;
};

export const decodeMCPDisconnectedPayload: Decoder<MCPDisconnectedPayload> = (v) => {
  const o = asObject(v, "$.mcp_disconnected_payload");
  const out: MCPDisconnectedPayload = {
    server: reqStr(o, "server", "$.mcp_disconnected_payload"),
  };
  return out;
};

export const decodeMCPFailedPayload: Decoder<MCPFailedPayload> = (v) => {
  const o = asObject(v, "$.mcp_failed_payload");
  const out: MCPFailedPayload = {
    server: reqStr(o, "server", "$.mcp_failed_payload"),
    error: reqStr(o, "error", "$.mcp_failed_payload"),
  };
  return out;
};

export const decodeMCPOAuthPayload: Decoder<MCPOAuthPayload> = (v) => {
  const o = asObject(v, "$.mcp_oauth_payload");
  const out: MCPOAuthPayload = {
    server: reqStr(o, "server", "$.mcp_oauth_payload"),
    url: reqStr(o, "url", "$.mcp_oauth_payload"),
  };
  return out;
};

export const decodeMessage: Decoder<Message> = (v) => {
  const o = asObject(v, "$.message");
  const out: Message = {
    role: reqOneOf(o, "role", ROLES, "$.message"),
    id: reqStr(o, "id", "$.message"),
    ts: reqNum(o, "ts", "$.message"),
  };
  if (o["changed_files"] !== undefined && o["changed_files"] !== null) out.changed_files = decodeRecord(o["changed_files"], decodeFileChange, "$.message.changed_files");
  const content = o["content"] === null ? undefined : optStr(o, "content", "$.message");
  if (content !== undefined) out.content = content;
  const reasoning = o["reasoning"] === null ? undefined : optStr(o, "reasoning", "$.message");
  if (reasoning !== undefined) out.reasoning = reasoning;
  if (o["event_kind"] !== undefined && o["event_kind"] !== null) out.event_kind = reqOneOf(o, "event_kind", EVENT_KINDS, "$.message");
  if (o["tool_calls"] !== undefined && o["tool_calls"] !== null) out.tool_calls = decodeArray(o["tool_calls"], decodeToolCall, "$.message.tool_calls");
  if (o["blocks"] !== undefined && o["blocks"] !== null) out.blocks = decodeArray(o["blocks"], decodeBlock, "$.message.blocks");
  if (o["code_references"] !== undefined && o["code_references"] !== null) out.code_references = decodeArray(o["code_references"], decodeCodeReference, "$.message.code_references");
  if (o["refusal"] !== undefined && o["refusal"] !== null) out.refusal = decodeRefusalInfo(o["refusal"]);
  if (o["plan"] !== undefined && o["plan"] !== null) out.plan = decodeArray(o["plan"], decodePlanEntry, "$.message.plan");
  const turnCredits = o["turn_credits"] === null ? undefined : optNum(o, "turn_credits", "$.message");
  if (turnCredits !== undefined) out.turn_credits = turnCredits;
  const turnElapsedMs = o["turn_elapsed_ms"] === null ? undefined : optNum(o, "turn_elapsed_ms", "$.message");
  if (turnElapsedMs !== undefined) out.turn_elapsed_ms = turnElapsedMs;
  return out;
};

export const decodeMessageChunkPayload: Decoder<MessageChunkPayload> = (v) => {
  const o = asObject(v, "$.message_chunk_payload");
  const out: MessageChunkPayload = {
    message_id: reqStr(o, "message_id", "$.message_chunk_payload"),
    delta: reqStr(o, "delta", "$.message_chunk_payload"),
    block_index: reqNum(o, "block_index", "$.message_chunk_payload"),
  };
  if (o["refusal"] !== undefined && o["refusal"] !== null) out.refusal = decodeRefusalInfo(o["refusal"]);
  const agentSubtaskId = o["agent_subtask_id"] === null ? undefined : optStr(o, "agent_subtask_id", "$.message_chunk_payload");
  if (agentSubtaskId !== undefined) out.agent_subtask_id = agentSubtaskId;
  const seq = o["seq"] === null ? undefined : optNum(o, "seq", "$.message_chunk_payload");
  if (seq !== undefined) out.seq = seq;
  const isReasoning = o["is_reasoning"] === null ? undefined : optBool(o, "is_reasoning", "$.message_chunk_payload");
  if (isReasoning !== undefined) out.is_reasoning = isReasoning;
  return out;
};

export const decodeMeteringItem: Decoder<MeteringItem> = (v) => {
  const o = asObject(v, "$.metering_item");
  const out: MeteringItem = {
    unit_singular: reqStr(o, "unit_singular", "$.metering_item"),
    unit_plural: reqStr(o, "unit_plural", "$.metering_item"),
    value: reqNum(o, "value", "$.metering_item"),
  };
  return out;
};

export const decodeOpenExternalURLPayload: Decoder<OpenExternalURLPayload> = (v) => {
  const o = asObject(v, "$.open_external_url_payload");
  const out: OpenExternalURLPayload = {
    url: reqStr(o, "url", "$.open_external_url_payload"),
  };
  return out;
};

export const decodePR: Decoder<PR> = (v) => {
  const o = asObject(v, "$.pr");
  const out: PR = {
    title: reqStr(o, "title", "$.pr"),
    state: reqStr(o, "state", "$.pr"),
    source_branch: reqStr(o, "source_branch", "$.pr"),
    target_branch: reqStr(o, "target_branch", "$.pr"),
    number: reqNum(o, "number", "$.pr"),
  };
  const body = o["body"] === null ? undefined : optStr(o, "body", "$.pr");
  if (body !== undefined) out.body = body;
  const author = o["author"] === null ? undefined : optStr(o, "author", "$.pr");
  if (author !== undefined) out.author = author;
  const url = o["url"] === null ? undefined : optStr(o, "url", "$.pr");
  if (url !== undefined) out.url = url;
  const createdAt = o["created_at"] === null ? undefined : optNum(o, "created_at", "$.pr");
  if (createdAt !== undefined) out.created_at = createdAt;
  const updatedAt = o["updated_at"] === null ? undefined : optNum(o, "updated_at", "$.pr");
  if (updatedAt !== undefined) out.updated_at = updatedAt;
  const mergeable = o["mergeable"] === null ? undefined : optBool(o, "mergeable", "$.pr");
  if (mergeable !== undefined) out.mergeable = mergeable;
  const draft = o["draft"] === null ? undefined : optBool(o, "draft", "$.pr");
  if (draft !== undefined) out.draft = draft;
  return out;
};

export const decodePermissionNeededPayload: Decoder<PermissionNeededPayload> = (v) => {
  const o = asObject(v, "$.permission_needed_payload");
  const out: PermissionNeededPayload = {
    options: o["options"] === null ? [] : decodeArray(o["options"], decodePermissionOption, "$.permission_needed_payload.options"),
    request_id: reqNum(o, "request_id", "$.permission_needed_payload"),
  };
  const toolCallId = o["tool_call_id"] === null ? undefined : optStr(o, "tool_call_id", "$.permission_needed_payload");
  if (toolCallId !== undefined) out.tool_call_id = toolCallId;
  const title = o["title"] === null ? undefined : optStr(o, "title", "$.permission_needed_payload");
  if (title !== undefined) out.title = title;
  if (o["kind"] !== undefined && o["kind"] !== null) out.kind = reqOneOf(o, "kind", TOOL_KINDS, "$.permission_needed_payload");
  const subSessionId = o["sub_session_id"] === null ? undefined : optStr(o, "sub_session_id", "$.permission_needed_payload");
  if (subSessionId !== undefined) out.sub_session_id = subSessionId;
  if (o["files"] !== undefined && o["files"] !== null) out.files = decodeArray(o["files"], decodeApprovalFile, "$.permission_needed_payload.files");
  return out;
};

export const decodePermissionOption: Decoder<PermissionOption> = (v) => {
  const o = asObject(v, "$.permission_option");
  const out: PermissionOption = {
    option_id: reqStr(o, "option_id", "$.permission_option"),
    name: reqStr(o, "name", "$.permission_option"),
    kind: reqStr(o, "kind", "$.permission_option"),
  };
  return out;
};

export const decodePermissionsChangedPayload: Decoder<PermissionsChangedPayload> = (v) => {
  const o = asObject(v, "$.permissions_changed_payload");
  const out: PermissionsChangedPayload = {
  };
  const status = o["status"] === null ? undefined : optStr(o, "status", "$.permissions_changed_payload");
  if (status !== undefined) out.status = status;
  if (o["errors"] !== undefined && o["errors"] !== null) out.errors = decodeArray(o["errors"], decodePolicyErrorItem, "$.permissions_changed_payload.errors");
  return out;
};

export const decodePlanEntry: Decoder<PlanEntry> = (v) => {
  const o = asObject(v, "$.plan_entry");
  const out: PlanEntry = {
    content: reqStr(o, "content", "$.plan_entry"),
    priority: reqStr(o, "priority", "$.plan_entry"),
    status: reqOneOf(o, "status", PLAN_STATUSS, "$.plan_entry"),
  };
  return out;
};

export const decodePolicyErrorItem: Decoder<PolicyErrorItem> = (v) => {
  const o = asObject(v, "$.policy_error_item");
  const out: PolicyErrorItem = {
    message: reqStr(o, "message", "$.policy_error_item"),
  };
  const scope = o["scope"] === null ? undefined : optStr(o, "scope", "$.policy_error_item");
  if (scope !== undefined) out.scope = scope;
  const source = o["source"] === null ? undefined : optStr(o, "source", "$.policy_error_item");
  if (source !== undefined) out.source = source;
  const fatal = o["fatal"] === null ? undefined : optBool(o, "fatal", "$.policy_error_item");
  if (fatal !== undefined) out.fatal = fatal;
  return out;
};

export const decodePolicyErrorPayload: Decoder<PolicyErrorPayload> = (v) => {
  const o = asObject(v, "$.policy_error_payload");
  const out: PolicyErrorPayload = {
  };
  if (o["errors"] !== undefined && o["errors"] !== null) out.errors = decodeArray(o["errors"], decodePolicyErrorItem, "$.policy_error_payload.errors");
  return out;
};

export const decodePolicyExplainResult: Decoder<PolicyExplainResult> = (v) => {
  const o = asObject(v, "$.policy_explain_result");
  const out: PolicyExplainResult = {
    capability: reqStr(o, "capability", "$.policy_explain_result"),
    effect: reqStr(o, "effect", "$.policy_explain_result"),
    is_explicit_ask: reqBool(o, "is_explicit_ask", "$.policy_explain_result"),
  };
  const resource = o["resource"] === null ? undefined : optStr(o, "resource", "$.policy_explain_result");
  if (resource !== undefined) out.resource = resource;
  if (o["matched_rule"] !== undefined && o["matched_rule"] !== null) out.matched_rule = decodePolicyRuleCore(o["matched_rule"]);
  const scope = o["scope"] === null ? undefined : optStr(o, "scope", "$.policy_explain_result");
  if (scope !== undefined) out.scope = scope;
  const source = o["source"] === null ? undefined : optStr(o, "source", "$.policy_explain_result");
  if (source !== undefined) out.source = source;
  return out;
};

export const decodePolicyRule: Decoder<PolicyRule> = (v) => {
  const o = asObject(v, "$.policy_rule");
  const out: PolicyRule = {
    capability: reqStr(o, "capability", "$.policy_rule"),
    effect: reqStr(o, "effect", "$.policy_rule"),
    scope: reqStr(o, "scope", "$.policy_rule"),
    source: reqStr(o, "source", "$.policy_rule"),
  };
  if (o["match"] !== undefined && o["match"] !== null) out.match = decodeArray(o["match"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.policy_rule.match");
  if (o["exclude"] !== undefined && o["exclude"] !== null) out.exclude = decodeArray(o["exclude"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.policy_rule.exclude");
  return out;
};

export const decodePolicyRuleCore: Decoder<PolicyRuleCore> = (v) => {
  const o = asObject(v, "$.policy_rule_core");
  const out: PolicyRuleCore = {
    capability: reqStr(o, "capability", "$.policy_rule_core"),
    effect: reqStr(o, "effect", "$.policy_rule_core"),
  };
  if (o["match"] !== undefined && o["match"] !== null) out.match = decodeArray(o["match"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.policy_rule_core.match");
  if (o["exclude"] !== undefined && o["exclude"] !== null) out.exclude = decodeArray(o["exclude"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.policy_rule_core.exclude");
  return out;
};

export const decodePolicyView: Decoder<PolicyView> = (v) => {
  const o = asObject(v, "$.policy_view");
  const out: PolicyView = {
    rules: o["rules"] === null ? [] : decodeArray(o["rules"], decodePolicyRule, "$.policy_view.rules"),
    writable_scopes: o["writable_scopes"] === null ? [] : decodeArray(o["writable_scopes"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.policy_view.writable_scopes"),
    capabilities: o["capabilities"] === null ? [] : decodeArray(o["capabilities"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.policy_view.capabilities"),
    available: reqBool(o, "available", "$.policy_view"),
  };
  return out;
};

export const decodePollResult: Decoder<PollResult> = (v) => {
  const o = asObject(v, "$.poll_result");
  const out: PollResult = {
    status: reqStr(o, "status", "$.poll_result"),
  };
  const error = o["error"] === null ? undefined : optStr(o, "error", "$.poll_result");
  if (error !== undefined) out.error = error;
  return out;
};

export const decodeRefusalInfo: Decoder<RefusalInfo> = (v) => {
  const o = asObject(v, "$.refusal_info");
  const out: RefusalInfo = {
  };
  const category = o["category"] === null ? undefined : optStr(o, "category", "$.refusal_info");
  if (category !== undefined) out.category = category;
  const recommendedModel = o["recommended_model"] === null ? undefined : optStr(o, "recommended_model", "$.refusal_info");
  if (recommendedModel !== undefined) out.recommended_model = recommendedModel;
  return out;
};

export const decodeRelease: Decoder<Release> = (v) => {
  const o = asObject(v, "$.release");
  const out: Release = {
    tag_name: reqStr(o, "tag_name", "$.release"),
  };
  const name = o["name"] === null ? undefined : optStr(o, "name", "$.release");
  if (name !== undefined) out.name = name;
  const body = o["body"] === null ? undefined : optStr(o, "body", "$.release");
  if (body !== undefined) out.body = body;
  const url = o["url"] === null ? undefined : optStr(o, "url", "$.release");
  if (url !== undefined) out.url = url;
  const publishedAt = o["published_at"] === null ? undefined : optNum(o, "published_at", "$.release");
  if (publishedAt !== undefined) out.published_at = publishedAt;
  const draft = o["draft"] === null ? undefined : optBool(o, "draft", "$.release");
  if (draft !== undefined) out.draft = draft;
  const prerelease = o["prerelease"] === null ? undefined : optBool(o, "prerelease", "$.release");
  if (prerelease !== undefined) out.prerelease = prerelease;
  return out;
};

export const decodeRemoveResponse: Decoder<RemoveResponse> = (v) => {
  const o = asObject(v, "$.remove_response");
  const out: RemoveResponse = {
  };
  if (o["job"] !== undefined && o["job"] !== null) out.job = decodeJob(o["job"]);
  if (o["dependents"] !== undefined && o["dependents"] !== null) out.dependents = decodeArray(o["dependents"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.remove_response.dependents");
  return out;
};

export const decodeRepo: Decoder<Repo> = (v) => {
  const o = asObject(v, "$.repo");
  const out: Repo = {
    owner: reqStr(o, "owner", "$.repo"),
    name: reqStr(o, "name", "$.repo"),
    full_name: reqStr(o, "full_name", "$.repo"),
  };
  const defaultBranch = o["default_branch"] === null ? undefined : optStr(o, "default_branch", "$.repo");
  if (defaultBranch !== undefined) out.default_branch = defaultBranch;
  const url = o["url"] === null ? undefined : optStr(o, "url", "$.repo");
  if (url !== undefined) out.url = url;
  const cloneUrl = o["clone_url"] === null ? undefined : optStr(o, "clone_url", "$.repo");
  if (cloneUrl !== undefined) out.clone_url = cloneUrl;
  const description = o["description"] === null ? undefined : optStr(o, "description", "$.repo");
  if (description !== undefined) out.description = description;
  const privateVal = o["private"] === null ? undefined : optBool(o, "private", "$.repo");
  if (privateVal !== undefined) out.private = privateVal;
  const archived = o["archived"] === null ? undefined : optBool(o, "archived", "$.repo");
  if (archived !== undefined) out.archived = archived;
  const fork = o["fork"] === null ? undefined : optBool(o, "fork", "$.repo");
  if (fork !== undefined) out.fork = fork;
  const updatedAt = o["updated_at"] === null ? undefined : optNum(o, "updated_at", "$.repo");
  if (updatedAt !== undefined) out.updated_at = updatedAt;
  return out;
};

export const decodeRunFinishedPayload: Decoder<RunFinishedPayload> = (v) => {
  const o = asObject(v, "$.run_finished_payload");
  const out: RunFinishedPayload = {
    workflow_id: reqStr(o, "workflow_id", "$.run_finished_payload"),
    status: reqStr(o, "status", "$.run_finished_payload"),
  };
  return out;
};

export const decodeRunProgressPayload: Decoder<RunProgressPayload> = (v) => {
  const o = asObject(v, "$.run_progress_payload");
  const out: RunProgressPayload = {
    workflow_id: reqStr(o, "workflow_id", "$.run_progress_payload"),
    kind: reqOneOf(o, "kind", RUN_PROGRESS_KINDS, "$.run_progress_payload"),
  };
  const nodeId = o["node_id"] === null ? undefined : optStr(o, "node_id", "$.run_progress_payload");
  if (nodeId !== undefined) out.node_id = nodeId;
  return out;
};

export const decodeRunStartedPayload: Decoder<RunStartedPayload> = (v) => {
  const o = asObject(v, "$.run_started_payload");
  const out: RunStartedPayload = {
    workflow_id: reqStr(o, "workflow_id", "$.run_started_payload"),
  };
  const name = o["name"] === null ? undefined : optStr(o, "name", "$.run_started_payload");
  if (name !== undefined) out.name = name;
  return out;
};

export const decodeSafetyPropertiesPayload: Decoder<SafetyPropertiesPayload> = (v) => {
  const o = asObject(v, "$.safety_properties_payload");
  const out: SafetyPropertiesPayload = {
    properties: o["properties"] === null ? [] : decodeArray(o["properties"], decodeSafetyProperty, "$.safety_properties_payload.properties"),
  };
  const reason = o["reason"] === null ? undefined : optStr(o, "reason", "$.safety_properties_payload");
  if (reason !== undefined) out.reason = reason;
  return out;
};

export const decodeSafetyProperty: Decoder<SafetyProperty> = (v) => {
  const o = asObject(v, "$.safety_property");
  const out: SafetyProperty = {
    description: reqStr(o, "description", "$.safety_property"),
  };
  const index = o["index"] === null ? undefined : optNum(o, "index", "$.safety_property");
  if (index !== undefined) out.index = index;
  const enabled = o["enabled"] === null ? undefined : optBool(o, "enabled", "$.safety_property");
  if (enabled !== undefined) out.enabled = enabled;
  return out;
};

export const decodeSafetyStatusPayload: Decoder<SafetyStatusPayload> = (v) => {
  const o = asObject(v, "$.safety_status_payload");
  const out: SafetyStatusPayload = {
    status: reqOneOf(o, "status", SAFETY_STATUSS, "$.safety_status_payload"),
  };
  const detail = o["detail"] === null ? undefined : optStr(o, "detail", "$.safety_status_payload");
  if (detail !== undefined) out.detail = detail;
  const toolId = o["tool_id"] === null ? undefined : optStr(o, "tool_id", "$.safety_status_payload");
  if (toolId !== undefined) out.tool_id = toolId;
  if (o["blocked_properties"] !== undefined && o["blocked_properties"] !== null) out.blocked_properties = decodeArray(o["blocked_properties"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.safety_status_payload.blocked_properties");
  return out;
};

export const decodeSearchHit: Decoder<SearchHit> = (v) => {
  const o = asObject(v, "$.search_hit");
  const out: SearchHit = {
    name: reqStr(o, "name", "$.search_hit"),
    source: reqStr(o, "source", "$.search_hit"),
  };
  const description = o["description"] === null ? undefined : optStr(o, "description", "$.search_hit");
  if (description !== undefined) out.description = description;
  const version = o["version"] === null ? undefined : optStr(o, "version", "$.search_hit");
  if (version !== undefined) out.version = version;
  const featured = o["featured"] === null ? undefined : optBool(o, "featured", "$.search_hit");
  if (featured !== undefined) out.featured = featured;
  const lsp = o["lsp"] === null ? undefined : optBool(o, "lsp", "$.search_hit");
  if (lsp !== undefined) out.lsp = lsp;
  return out;
};

export const decodeSearchResponse: Decoder<SearchResponse> = (v) => {
  const o = asObject(v, "$.search_response");
  const out: SearchResponse = {
    results: o["results"] === null ? [] : decodeArray(o["results"], decodeSearchHit, "$.search_response.results"),
  };
  return out;
};

export const decodeSessionMode: Decoder<SessionMode> = (v) => {
  const o = asObject(v, "$.session_mode");
  const out: SessionMode = {
    id: reqStr(o, "id", "$.session_mode"),
    name: reqStr(o, "name", "$.session_mode"),
  };
  const description = o["description"] === null ? undefined : optStr(o, "description", "$.session_mode");
  if (description !== undefined) out.description = description;
  const source = o["source"] === null ? undefined : optStr(o, "source", "$.session_mode");
  if (source !== undefined) out.source = source;
  return out;
};

export const decodeSessionModel: Decoder<SessionModel> = (v) => {
  const o = asObject(v, "$.session_model");
  const out: SessionModel = {
    id: reqStr(o, "id", "$.session_model"),
    name: reqStr(o, "name", "$.session_model"),
  };
  const description = o["description"] === null ? undefined : optStr(o, "description", "$.session_model");
  if (description !== undefined) out.description = description;
  const rateMultiplier = o["rate_multiplier"] === null ? undefined : optNum(o, "rate_multiplier", "$.session_model");
  if (rateMultiplier !== undefined) out.rate_multiplier = rateMultiplier;
  const hasEffort = o["has_effort"] === null ? undefined : optBool(o, "has_effort", "$.session_model");
  if (hasEffort !== undefined) out.has_effort = hasEffort;
  return out;
};

export const decodeSystemTool: Decoder<SystemTool> = (v) => {
  const o = asObject(v, "$.system_tool");
  const out: SystemTool = {
    name: reqStr(o, "name", "$.system_tool"),
    installed: reqBool(o, "installed", "$.system_tool"),
  };
  return out;
};

export const decodeToolCall: Decoder<ToolCall> = (v) => {
  const o = asObject(v, "$.tool_call");
  const out: ToolCall = {
    id: reqStr(o, "id", "$.tool_call"),
    title: reqStr(o, "title", "$.tool_call"),
    kind: reqOneOf(o, "kind", TOOL_KINDS, "$.tool_call"),
    status: reqOneOf(o, "status", TOOL_STATUSS, "$.tool_call"),
    ts: reqNum(o, "ts", "$.tool_call"),
  };
  const output = o["output"] === null ? undefined : optStr(o, "output", "$.tool_call");
  if (output !== undefined) out.output = output;
  const subSessionId = o["sub_session_id"] === null ? undefined : optStr(o, "sub_session_id", "$.tool_call");
  if (subSessionId !== undefined) out.sub_session_id = subSessionId;
  const agentSubtaskId = o["agent_subtask_id"] === null ? undefined : optStr(o, "agent_subtask_id", "$.tool_call");
  if (agentSubtaskId !== undefined) out.agent_subtask_id = agentSubtaskId;
  if (o["checkpoint"] !== undefined && o["checkpoint"] !== null) out.checkpoint = decodeToolCheckpoint(o["checkpoint"]);
  if (o["input"] !== undefined) out.input = o["input"] as unknown;
  if (o["locations"] !== undefined && o["locations"] !== null) out.locations = decodeArray(o["locations"], decodeToolLocation, "$.tool_call.locations");
  if (o["diffs"] !== undefined && o["diffs"] !== null) out.diffs = decodeArray(o["diffs"], decodeToolDiff, "$.tool_call.diffs");
  const durationMs = o["duration_ms"] === null ? undefined : optNum(o, "duration_ms", "$.tool_call");
  if (durationMs !== undefined) out.duration_ms = durationMs;
  return out;
};

export const decodeToolCallPayload: Decoder<ToolCallPayload> = (v) => {
  const o = asObject(v, "$.tool_call_payload");
  const out: ToolCallPayload = {
    message_id: reqStr(o, "message_id", "$.tool_call_payload"),
    tool_call: decodeToolCall(o["tool_call"]),
    block_index: reqNum(o, "block_index", "$.tool_call_payload"),
  };
  return out;
};

export const decodeToolCallUpdatePayload: Decoder<ToolCallUpdatePayload> = (v) => {
  const o = asObject(v, "$.tool_call_update_payload");
  const out: ToolCallUpdatePayload = {
    message_id: reqStr(o, "message_id", "$.tool_call_update_payload"),
    tool_call: decodeToolCall(o["tool_call"]),
  };
  return out;
};

export const decodeToolCheckpoint: Decoder<ToolCheckpoint> = (v) => {
  const o = asObject(v, "$.tool_checkpoint");
  const out: ToolCheckpoint = {
  };
  const original = o["original"] === null ? undefined : optStr(o, "original", "$.tool_checkpoint");
  if (original !== undefined) out.original = original;
  const modified = o["modified"] === null ? undefined : optStr(o, "modified", "$.tool_checkpoint");
  if (modified !== undefined) out.modified = modified;
  const local = o["local"] === null ? undefined : optStr(o, "local", "$.tool_checkpoint");
  if (local !== undefined) out.local = local;
  return out;
};

export const decodeToolDiff: Decoder<ToolDiff> = (v) => {
  const o = asObject(v, "$.tool_diff");
  const out: ToolDiff = {
    path: reqStr(o, "path", "$.tool_diff"),
    new_text: reqStr(o, "new_text", "$.tool_diff"),
  };
  const oldText = o["old_text"] === null ? undefined : optStr(o, "old_text", "$.tool_diff");
  if (oldText !== undefined) out.old_text = oldText;
  return out;
};

export const decodeToolInfo: Decoder<ToolInfo> = (v) => {
  const o = asObject(v, "$.tool_info");
  const out: ToolInfo = {
    name: reqStr(o, "name", "$.tool_info"),
    installed: reqBool(o, "installed", "$.tool_info"),
    installing: reqBool(o, "installing", "$.tool_info"),
  };
  const source = o["source"] === null ? undefined : optStr(o, "source", "$.tool_info");
  if (source !== undefined) out.source = source;
  const version = o["version"] === null ? undefined : optStr(o, "version", "$.tool_info");
  if (version !== undefined) out.version = version;
  const description = o["description"] === null ? undefined : optStr(o, "description", "$.tool_info");
  if (description !== undefined) out.description = description;
  const origin = o["origin"] === null ? undefined : optStr(o, "origin", "$.tool_info");
  if (origin !== undefined) out.origin = origin;
  const installedVersion = o["installed_version"] === null ? undefined : optStr(o, "installed_version", "$.tool_info");
  if (installedVersion !== undefined) out.installed_version = installedVersion;
  const latest = o["latest"] === null ? undefined : optStr(o, "latest", "$.tool_info");
  if (latest !== undefined) out.latest = latest;
  const lastError = o["last_error"] === null ? undefined : optStr(o, "last_error", "$.tool_info");
  if (lastError !== undefined) out.last_error = lastError;
  if (o["requires"] !== undefined && o["requires"] !== null) out.requires = decodeArray(o["requires"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.tool_info.requires");
  const pin = o["pin"] === null ? undefined : optBool(o, "pin", "$.tool_info");
  if (pin !== undefined) out.pin = pin;
  const disabled = o["disabled"] === null ? undefined : optBool(o, "disabled", "$.tool_info");
  if (disabled !== undefined) out.disabled = disabled;
  const lsp = o["lsp"] === null ? undefined : optBool(o, "lsp", "$.tool_info");
  if (lsp !== undefined) out.lsp = lsp;
  return out;
};

export const decodeToolJobChangedPayload: Decoder<ToolJobChangedPayload> = (v) => {
  const o = asObject(v, "$.tool_job_changed_payload");
  const out: ToolJobChangedPayload = {
  };
  if (o["job"] !== undefined && o["job"] !== null) out.job = decodeJob(o["job"]);
  return out;
};

export const decodeToolJobOutputPayload: Decoder<ToolJobOutputPayload> = (v) => {
  const o = asObject(v, "$.tool_job_output_payload");
  const out: ToolJobOutputPayload = {
    job_id: reqStr(o, "job_id", "$.tool_job_output_payload"),
    lines: o["lines"] === null ? [] : decodeArray(o["lines"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.tool_job_output_payload.lines"),
  };
  return out;
};

export const decodeToolLocation: Decoder<ToolLocation> = (v) => {
  const o = asObject(v, "$.tool_location");
  const out: ToolLocation = {
    path: reqStr(o, "path", "$.tool_location"),
  };
  const line = o["line"] === null ? undefined : optNum(o, "line", "$.tool_location");
  if (line !== undefined) out.line = line;
  return out;
};

export const decodeTurnEndedPayload: Decoder<TurnEndedPayload> = (v) => {
  const o = asObject(v, "$.turn_ended_payload");
  const out: TurnEndedPayload = {
  };
  if (o["changed_files"] !== undefined && o["changed_files"] !== null) out.changed_files = decodeRecord(o["changed_files"], decodeFileChange, "$.turn_ended_payload.changed_files");
  if (o["refusal"] !== undefined && o["refusal"] !== null) out.refusal = decodeRefusalInfo(o["refusal"]);
  if (o["stop_reason"] !== undefined && o["stop_reason"] !== null) out.stop_reason = reqOneOf(o, "stop_reason", STOP_REASONS, "$.turn_ended_payload");
  const creditsDelta = o["credits_delta"] === null ? undefined : optNum(o, "credits_delta", "$.turn_ended_payload");
  if (creditsDelta !== undefined) out.credits_delta = creditsDelta;
  const elapsedMs = o["elapsed_ms"] === null ? undefined : optNum(o, "elapsed_ms", "$.turn_ended_payload");
  if (elapsedMs !== undefined) out.elapsed_ms = elapsedMs;
  return out;
};

export const decodeTurnStatePayload: Decoder<TurnStatePayload> = (v) => {
  const o = asObject(v, "$.turn_state_payload");
  const out: TurnStatePayload = {
  };
  if (o["message"] !== undefined && o["message"] !== null) out.message = decodeMessage(o["message"]);
  const status = o["status"] === null ? undefined : optStr(o, "status", "$.turn_state_payload");
  if (status !== undefined) out.status = status;
  const description = o["description"] === null ? undefined : optStr(o, "description", "$.turn_state_payload");
  if (description !== undefined) out.description = description;
  const chunkSeq = o["chunk_seq"] === null ? undefined : optNum(o, "chunk_seq", "$.turn_state_payload");
  if (chunkSeq !== undefined) out.chunk_seq = chunkSeq;
  return out;
};

export const decodeUsage: Decoder<Usage> = (v) => {
  const o = asObject(v, "$.usage");
  const out: Usage = {
    context_pct: reqNum(o, "context_pct", "$.usage"),
    context_size: reqNum(o, "context_size", "$.usage"),
    credits: reqNum(o, "credits", "$.usage"),
    turn_count: reqNum(o, "turn_count", "$.usage"),
    last_turn_ms: reqNum(o, "last_turn_ms", "$.usage"),
    has_real_data: reqBool(o, "has_real_data", "$.usage"),
  };
  if (o["metering_items"] !== undefined && o["metering_items"] !== null) out.metering_items = decodeArray(o["metering_items"], decodeMeteringItem, "$.usage.metering_items");
  return out;
};

export const decodeUser: Decoder<User> = (v) => {
  const o = asObject(v, "$.user");
  const out: User = {
    login: reqStr(o, "login", "$.user"),
  };
  const name = o["name"] === null ? undefined : optStr(o, "name", "$.user");
  if (name !== undefined) out.name = name;
  const email = o["email"] === null ? undefined : optStr(o, "email", "$.user");
  if (email !== undefined) out.email = email;
  const url = o["url"] === null ? undefined : optStr(o, "url", "$.user");
  if (url !== undefined) out.url = url;
  return out;
};

export const decodeUserInputNeededPayload: Decoder<UserInputNeededPayload> = (v) => {
  const o = asObject(v, "$.user_input_needed_payload");
  const out: UserInputNeededPayload = {
    question: reqStr(o, "question", "$.user_input_needed_payload"),
    request_id: reqNum(o, "request_id", "$.user_input_needed_payload"),
  };
  const toolCallId = o["tool_call_id"] === null ? undefined : optStr(o, "tool_call_id", "$.user_input_needed_payload");
  if (toolCallId !== undefined) out.tool_call_id = toolCallId;
  const subSessionId = o["sub_session_id"] === null ? undefined : optStr(o, "sub_session_id", "$.user_input_needed_payload");
  if (subSessionId !== undefined) out.sub_session_id = subSessionId;
  if (o["options"] !== undefined && o["options"] !== null) out.options = decodeArray(o["options"], decodeUserInputOption, "$.user_input_needed_payload.options");
  return out;
};

export const decodeUserInputOption: Decoder<UserInputOption> = (v) => {
  const o = asObject(v, "$.user_input_option");
  const out: UserInputOption = {
    title: reqStr(o, "title", "$.user_input_option"),
  };
  const description = o["description"] === null ? undefined : optStr(o, "description", "$.user_input_option");
  if (description !== undefined) out.description = description;
  const subOptionsLabel = o["sub_options_label"] === null ? undefined : optStr(o, "sub_options_label", "$.user_input_option");
  if (subOptionsLabel !== undefined) out.sub_options_label = subOptionsLabel;
  if (o["sub_options"] !== undefined && o["sub_options"] !== null) out.sub_options = decodeArray(o["sub_options"], decodeUserInputSubOption, "$.user_input_option.sub_options");
  const recommended = o["recommended"] === null ? undefined : optBool(o, "recommended", "$.user_input_option");
  if (recommended !== undefined) out.recommended = recommended;
  return out;
};

export const decodeUserInputSubOption: Decoder<UserInputSubOption> = (v) => {
  const o = asObject(v, "$.user_input_sub_option");
  const out: UserInputSubOption = {
    title: reqStr(o, "title", "$.user_input_sub_option"),
  };
  const description = o["description"] === null ? undefined : optStr(o, "description", "$.user_input_sub_option");
  if (description !== undefined) out.description = description;
  return out;
};

export const decodeWhoamiResponse: Decoder<WhoamiResponse> = (v) => {
  const o = asObject(v, "$.whoami_response");
  const out: WhoamiResponse = {
  };
  const email = o["email"] === null ? undefined : optStr(o, "email", "$.whoami_response");
  if (email !== undefined) out.email = email;
  const auth = o["auth"] === null ? undefined : optStr(o, "auth", "$.whoami_response");
  if (auth !== undefined) out.auth = auth;
  const accountType = o["accountType"] === null ? undefined : optStr(o, "accountType", "$.whoami_response");
  if (accountType !== undefined) out.accountType = accountType;
  const startUrl = o["startUrl"] === null ? undefined : optStr(o, "startUrl", "$.whoami_response");
  if (startUrl !== undefined) out.startUrl = startUrl;
  const region = o["region"] === null ? undefined : optStr(o, "region", "$.whoami_response");
  if (region !== undefined) out.region = region;
  const error = o["error"] === null ? undefined : optStr(o, "error", "$.whoami_response");
  if (error !== undefined) out.error = error;
  return out;
};

