// CODE-GENERATED by cmd/wire-codegen, DO NOT EDIT.

import { asObject, reqStr, reqNum, reqBool, optStr, optNum, optBool, reqOneOf, decodeArray, decodeRecord, type Decoder } from "../validators.js";
import type { AvailableCommand, Block, ChatDeletedPayload, ChatHeader, Check, CommandsUpdatedPayload, ConfiguredForge, ConnectedPayload, Crew, CrewPendingStage, CrewSubagent, DeviceFlowResponse, ElicitationCompletePayload, ElicitationNeededPayload, ElicitationPropertySchema, ElicitationRequestSchema, ErrorPayload, FileChange, Issue, Label, MCPConnectedPayload, MCPDisconnectedPayload, MCPFailedPayload, MCPOAuthPayload, Message, MessageChunkPayload, MeteringItem, PR, PendingChange, PendingChangeAddedPayload, PendingChangeResolvedPayload, PendingChangesClearedPayload, PermissionNeededPayload, PermissionOption, PlanEntry, PollResult, Release, Repo, SessionMode, SessionModel, ToolCall, ToolCallPayload, ToolCallUpdatePayload, ToolDiff, ToolLocation, TurnEndedPayload, Usage, User, WhoamiResponse } from "./types.gen.js";

const CLEAR_REASONS = ["turn_ended", "cancelled", "mode_disabled", "chat_deleted", "shutdown", "user_cleared"] as const;
const CREW_STATUSS = ["working", "terminated", "error", "pending"] as const;
const ERROR_CODES = ["recovery_failed", "bridge_start_failed", "prompt_failed", "agent_not_found", "model_not_found", "agent_config_error", "rate_limit", "stream_timeout", "spawn_failed", "switch_failed", "compaction_failed"] as const;
const EVENT_KINDS = ["interrupted", "cancelled", "model_switched", "compacted", "crew", "agent_switched", "compaction_failed", "inbox"] as const;
const FORGE_KINDS = ["github", "gitlab", "gitea", "codeberg"] as const;
const PENDING_ACTIONS = ["accept", "reject"] as const;
const PENDING_CHANGE_KINDS = ["create", "edit", "delete"] as const;
const PLAN_STATUSS = ["pending", "in_progress", "completed"] as const;
const ROLES = ["user", "assistant", "event"] as const;
const STOP_REASONS = ["end_turn", "cancelled", "interrupted"] as const;
const TOOL_KINDS = ["execute", "shell", "read", "search", "fetch", "edit", "think", "hook", "write", "delete", "move", "command", "browser", "switch_mode", "mcp", "other"] as const;
const TOOL_STATUSS = ["pending", "in_progress", "completed", "failed"] as const;

export const decodeAvailableCommand: Decoder<AvailableCommand> = (v) => {
  const o = asObject(v, "$.available_command");
  const out: AvailableCommand = {
    name: reqStr(o, "name", "$.available_command"),
  };
  if (o["meta"] !== undefined) out.meta = decodeRecord(o["meta"], (v) => v as unknown, "$.available_command.meta");
  const description = optStr(o, "description", "$.available_command");
  if (description !== undefined) out.description = description;
  return out;
};

export const decodeBlock: Decoder<Block> = (v) => {
  const o = asObject(v, "$.block");
  const out: Block = {
    type: reqStr(o, "type", "$.block"),
  };
  const text = optStr(o, "text", "$.block");
  if (text !== undefined) out.text = text;
  const thinking = optStr(o, "thinking", "$.block");
  if (thinking !== undefined) out.thinking = thinking;
  const toolCallId = optStr(o, "tool_call_id", "$.block");
  if (toolCallId !== undefined) out.tool_call_id = toolCallId;
  return out;
};

export const decodeChatDeletedPayload: Decoder<ChatDeletedPayload> = (v) => {
  const o = asObject(v, "$.chat_deleted_payload");
  const out: ChatDeletedPayload = {
    id: reqStr(o, "id", "$.chat_deleted_payload"),
  };
  return out;
};

export const decodeChatHeader: Decoder<ChatHeader> = (v) => {
  const o = asObject(v, "$.chat_header");
  const out: ChatHeader = {
    name: reqStr(o, "name", "$.chat_header"),
    id: reqStr(o, "id", "$.chat_header"),
    usage: decodeUsage(o["usage"]),
    created_at: reqNum(o, "created_at", "$.chat_header"),
    updated_at: reqNum(o, "updated_at", "$.chat_header"),
    message_count: reqNum(o, "message_count", "$.chat_header"),
  };
  const parentChatId = optStr(o, "parent_chat_id", "$.chat_header");
  if (parentChatId !== undefined) out.parent_chat_id = parentChatId;
  const agent = optStr(o, "agent", "$.chat_header");
  if (agent !== undefined) out.agent = agent;
  const model = optStr(o, "model", "$.chat_header");
  if (model !== undefined) out.model = model;
  const acpSessionId = optStr(o, "acp_session_id", "$.chat_header");
  if (acpSessionId !== undefined) out.acp_session_id = acpSessionId;
  const currentModeId = optStr(o, "current_mode_id", "$.chat_header");
  if (currentModeId !== undefined) out.current_mode_id = currentModeId;
  const compactionWatermark = optStr(o, "compaction_watermark", "$.chat_header");
  if (compactionWatermark !== undefined) out.compaction_watermark = compactionWatermark;
  const oldestCheckpointTag = optStr(o, "oldest_checkpoint_tag", "$.chat_header");
  if (oldestCheckpointTag !== undefined) out.oldest_checkpoint_tag = oldestCheckpointTag;
  const summary = optStr(o, "summary", "$.chat_header");
  if (summary !== undefined) out.summary = summary;
  if (o["available_models"] !== undefined) out.available_models = decodeArray(o["available_models"], decodeSessionModel, "$.chat_header.available_models");
  if (o["available_modes"] !== undefined) out.available_modes = decodeArray(o["available_modes"], decodeSessionMode, "$.chat_header.available_modes");
  const supervisedMode = optBool(o, "supervised_mode", "$.chat_header");
  if (supervisedMode !== undefined) out.supervised_mode = supervisedMode;
  const autoApproveCrew = optBool(o, "auto_approve_crew", "$.chat_header");
  if (autoApproveCrew !== undefined) out.auto_approve_crew = autoApproveCrew;
  return out;
};

export const decodeCheck: Decoder<Check> = (v) => {
  const o = asObject(v, "$.check");
  const out: Check = {
    name: reqStr(o, "name", "$.check"),
    status: reqStr(o, "status", "$.check"),
    conclusion: reqStr(o, "conclusion", "$.check"),
  };
  const url = optStr(o, "url", "$.check");
  if (url !== undefined) out.url = url;
  return out;
};

export const decodeCommandsUpdatedPayload: Decoder<CommandsUpdatedPayload> = (v) => {
  const o = asObject(v, "$.commands_updated_payload");
  const out: CommandsUpdatedPayload = {
    commands: decodeArray(o["commands"], decodeAvailableCommand, "$.commands_updated_payload.commands"),
  };
  if (o["prompts"] !== undefined) out.prompts = decodeArray(o["prompts"], decodeAvailableCommand, "$.commands_updated_payload.prompts");
  return out;
};

export const decodeConfiguredForge: Decoder<ConfiguredForge> = (v) => {
  const o = asObject(v, "$.configured_forge");
  const out: ConfiguredForge = {
    id: reqStr(o, "id", "$.configured_forge"),
    kind: reqOneOf(o, "kind", FORGE_KINDS, "$.configured_forge"),
    host: reqStr(o, "host", "$.configured_forge"),
    connected: reqBool(o, "connected", "$.configured_forge"),
  };
  const username = optStr(o, "username", "$.configured_forge");
  if (username !== undefined) out.username = username;
  const email = optStr(o, "email", "$.configured_forge");
  if (email !== undefined) out.email = email;
  const lastError = optStr(o, "last_error", "$.configured_forge");
  if (lastError !== undefined) out.last_error = lastError;
  const lastProbed = optNum(o, "last_probed", "$.configured_forge");
  if (lastProbed !== undefined) out.last_probed = lastProbed;
  return out;
};

export const decodeConnectedPayload: Decoder<ConnectedPayload> = (v) => {
  const o = asObject(v, "$.connected_payload");
  const out: ConnectedPayload = {
    floor: reqNum(o, "floor", "$.connected_payload"),
    head: reqNum(o, "head", "$.connected_payload"),
  };
  return out;
};

export const decodeCrew: Decoder<Crew> = (v) => {
  const o = asObject(v, "$.crew");
  const out: Crew = {
    group: reqStr(o, "group", "$.crew"),
    subagents: decodeArray(o["subagents"], decodeCrewSubagent, "$.crew.subagents"),
  };
  if (o["pending_stages"] !== undefined) out.pending_stages = decodeArray(o["pending_stages"], decodeCrewPendingStage, "$.crew.pending_stages");
  return out;
};

export const decodeCrewPendingStage: Decoder<CrewPendingStage> = (v) => {
  const o = asObject(v, "$.crew_pending_stage");
  const out: CrewPendingStage = {
    name: reqStr(o, "name", "$.crew_pending_stage"),
    agent_name: reqStr(o, "agent_name", "$.crew_pending_stage"),
  };
  const role = optStr(o, "role", "$.crew_pending_stage");
  if (role !== undefined) out.role = role;
  if (o["depends_on"] !== undefined) out.depends_on = decodeArray(o["depends_on"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.crew_pending_stage.depends_on");
  return out;
};

export const decodeCrewSubagent: Decoder<CrewSubagent> = (v) => {
  const o = asObject(v, "$.crew_subagent");
  const out: CrewSubagent = {
    session_id: reqStr(o, "session_id", "$.crew_subagent"),
    session_name: reqStr(o, "session_name", "$.crew_subagent"),
    agent_name: reqStr(o, "agent_name", "$.crew_subagent"),
    initial_query: reqStr(o, "initial_query", "$.crew_subagent"),
    status: reqOneOf(o, "status", CREW_STATUSS, "$.crew_subagent"),
    group: reqStr(o, "group", "$.crew_subagent"),
  };
  const statusMsg = optStr(o, "status_msg", "$.crew_subagent");
  if (statusMsg !== undefined) out.status_msg = statusMsg;
  const role = optStr(o, "role", "$.crew_subagent");
  if (role !== undefined) out.role = role;
  if (o["depends_on"] !== undefined) out.depends_on = decodeArray(o["depends_on"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.crew_subagent.depends_on");
  return out;
};

export const decodeDeviceFlowResponse: Decoder<DeviceFlowResponse> = (v) => {
  const o = asObject(v, "$.device_flow_response");
  const out: DeviceFlowResponse = {
    user_code: reqStr(o, "user_code", "$.device_flow_response"),
    verification_uri: reqStr(o, "verification_uri", "$.device_flow_response"),
    device_code: reqStr(o, "device_code", "$.device_flow_response"),
    interval: reqNum(o, "interval", "$.device_flow_response"),
    expires_in: reqNum(o, "expires_in", "$.device_flow_response"),
  };
  return out;
};

export const decodeElicitationCompletePayload: Decoder<ElicitationCompletePayload> = (v) => {
  const o = asObject(v, "$.elicitation_complete_payload");
  const out: ElicitationCompletePayload = {
    request_id: reqNum(o, "request_id", "$.elicitation_complete_payload"),
  };
  return out;
};

export const decodeElicitationNeededPayload: Decoder<ElicitationNeededPayload> = (v) => {
  const o = asObject(v, "$.elicitation_needed_payload");
  const out: ElicitationNeededPayload = {
    request_id: reqNum(o, "request_id", "$.elicitation_needed_payload"),
  };
  if (o["requested_schema"] !== undefined) out.requested_schema = decodeElicitationRequestSchema(o["requested_schema"]);
  const mode = optStr(o, "mode", "$.elicitation_needed_payload");
  if (mode !== undefined) out.mode = mode;
  const message = optStr(o, "message", "$.elicitation_needed_payload");
  if (message !== undefined) out.message = message;
  const url = optStr(o, "url", "$.elicitation_needed_payload");
  if (url !== undefined) out.url = url;
  const toolCallId = optStr(o, "tool_call_id", "$.elicitation_needed_payload");
  if (toolCallId !== undefined) out.tool_call_id = toolCallId;
  const subSessionId = optStr(o, "sub_session_id", "$.elicitation_needed_payload");
  if (subSessionId !== undefined) out.sub_session_id = subSessionId;
  return out;
};

export const decodeElicitationPropertySchema: Decoder<ElicitationPropertySchema> = (v) => {
  const o = asObject(v, "$.elicitation_property_schema");
  const out: ElicitationPropertySchema = {
    type: reqStr(o, "type", "$.elicitation_property_schema"),
  };
  const title = optStr(o, "title", "$.elicitation_property_schema");
  if (title !== undefined) out.title = title;
  const description = optStr(o, "description", "$.elicitation_property_schema");
  if (description !== undefined) out.description = description;
  const format = optStr(o, "format", "$.elicitation_property_schema");
  if (format !== undefined) out.format = format;
  const pattern = optStr(o, "pattern", "$.elicitation_property_schema");
  if (pattern !== undefined) out.pattern = pattern;
  if (o["enum"] !== undefined) out.enum = decodeArray(o["enum"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.elicitation_property_schema.enum");
  if (o["default"] !== undefined) out.default = o["default"] as unknown;
  const minLength = optNum(o, "minLength", "$.elicitation_property_schema");
  if (minLength !== undefined) out.minLength = minLength;
  const maxLength = optNum(o, "maxLength", "$.elicitation_property_schema");
  if (maxLength !== undefined) out.maxLength = maxLength;
  return out;
};

export const decodeElicitationRequestSchema: Decoder<ElicitationRequestSchema> = (v) => {
  const o = asObject(v, "$.elicitation_request_schema");
  const out: ElicitationRequestSchema = {
  };
  const type = optStr(o, "type", "$.elicitation_request_schema");
  if (type !== undefined) out.type = type;
  const title = optStr(o, "title", "$.elicitation_request_schema");
  if (title !== undefined) out.title = title;
  const description = optStr(o, "description", "$.elicitation_request_schema");
  if (description !== undefined) out.description = description;
  if (o["properties"] !== undefined) out.properties = decodeRecord(o["properties"], decodeElicitationPropertySchema, "$.elicitation_request_schema.properties");
  if (o["required"] !== undefined) out.required = decodeArray(o["required"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.elicitation_request_schema.required");
  return out;
};

export const decodeErrorPayload: Decoder<ErrorPayload> = (v) => {
  const o = asObject(v, "$.error_payload");
  const out: ErrorPayload = {
    code: reqOneOf(o, "code", ERROR_CODES, "$.error_payload"),
    message: reqStr(o, "message", "$.error_payload"),
  };
  return out;
};

export const decodeFileChange: Decoder<FileChange> = (v) => {
  const o = asObject(v, "$.file_change");
  const out: FileChange = {
    lines_added: reqNum(o, "lines_added", "$.file_change"),
    lines_removed: reqNum(o, "lines_removed", "$.file_change"),
  };
  const isNewFile = optBool(o, "is_new_file", "$.file_change");
  if (isNewFile !== undefined) out.is_new_file = isNewFile;
  return out;
};

export const decodeIssue: Decoder<Issue> = (v) => {
  const o = asObject(v, "$.issue");
  const out: Issue = {
    title: reqStr(o, "title", "$.issue"),
    state: reqStr(o, "state", "$.issue"),
    number: reqNum(o, "number", "$.issue"),
  };
  const body = optStr(o, "body", "$.issue");
  if (body !== undefined) out.body = body;
  const author = optStr(o, "author", "$.issue");
  if (author !== undefined) out.author = author;
  const url = optStr(o, "url", "$.issue");
  if (url !== undefined) out.url = url;
  if (o["labels"] !== undefined) out.labels = decodeArray(o["labels"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.issue.labels");
  const createdAt = optNum(o, "created_at", "$.issue");
  if (createdAt !== undefined) out.created_at = createdAt;
  const updatedAt = optNum(o, "updated_at", "$.issue");
  if (updatedAt !== undefined) out.updated_at = updatedAt;
  return out;
};

export const decodeLabel: Decoder<Label> = (v) => {
  const o = asObject(v, "$.label");
  const out: Label = {
    name: reqStr(o, "name", "$.label"),
  };
  const color = optStr(o, "color", "$.label");
  if (color !== undefined) out.color = color;
  const description = optStr(o, "description", "$.label");
  if (description !== undefined) out.description = description;
  return out;
};

export const decodeMCPConnectedPayload: Decoder<MCPConnectedPayload> = (v) => {
  const o = asObject(v, "$.mcp_connected_payload");
  const out: MCPConnectedPayload = {
    server: reqStr(o, "server", "$.mcp_connected_payload"),
  };
  return out;
};

export const decodeMCPDisconnectedPayload: Decoder<MCPDisconnectedPayload> = (v) => {
  const o = asObject(v, "$.mcp_disconnected_payload");
  const out: MCPDisconnectedPayload = {
    server: reqStr(o, "server", "$.mcp_disconnected_payload"),
  };
  return out;
};

export const decodeMCPFailedPayload: Decoder<MCPFailedPayload> = (v) => {
  const o = asObject(v, "$.mcp_failed_payload");
  const out: MCPFailedPayload = {
    server: reqStr(o, "server", "$.mcp_failed_payload"),
    error: reqStr(o, "error", "$.mcp_failed_payload"),
  };
  return out;
};

export const decodeMCPOAuthPayload: Decoder<MCPOAuthPayload> = (v) => {
  const o = asObject(v, "$.mcp_oauth_payload");
  const out: MCPOAuthPayload = {
    server: reqStr(o, "server", "$.mcp_oauth_payload"),
    url: reqStr(o, "url", "$.mcp_oauth_payload"),
  };
  return out;
};

export const decodeMessage: Decoder<Message> = (v) => {
  const o = asObject(v, "$.message");
  const out: Message = {
    id: reqStr(o, "id", "$.message"),
    role: reqOneOf(o, "role", ROLES, "$.message"),
    ts: reqNum(o, "ts", "$.message"),
  };
  if (o["crew"] !== undefined) out.crew = decodeCrew(o["crew"]);
  const content = optStr(o, "content", "$.message");
  if (content !== undefined) out.content = content;
  const reasoning = optStr(o, "reasoning", "$.message");
  if (reasoning !== undefined) out.reasoning = reasoning;
  if (o["event_kind"] !== undefined) out.event_kind = reqOneOf(o, "event_kind", EVENT_KINDS, "$.message");
  if (o["tool_calls"] !== undefined) out.tool_calls = decodeArray(o["tool_calls"], decodeToolCall, "$.message.tool_calls");
  if (o["plan"] !== undefined) out.plan = decodeArray(o["plan"], decodePlanEntry, "$.message.plan");
  if (o["blocks"] !== undefined) out.blocks = decodeArray(o["blocks"], decodeBlock, "$.message.blocks");
  return out;
};

export const decodeMessageChunkPayload: Decoder<MessageChunkPayload> = (v) => {
  const o = asObject(v, "$.message_chunk_payload");
  const out: MessageChunkPayload = {
    message_id: reqStr(o, "message_id", "$.message_chunk_payload"),
    delta: reqStr(o, "delta", "$.message_chunk_payload"),
    block_index: reqNum(o, "block_index", "$.message_chunk_payload"),
  };
  const isReasoning = optBool(o, "is_reasoning", "$.message_chunk_payload");
  if (isReasoning !== undefined) out.is_reasoning = isReasoning;
  return out;
};

export const decodeMeteringItem: Decoder<MeteringItem> = (v) => {
  const o = asObject(v, "$.metering_item");
  const out: MeteringItem = {
    unit_singular: reqStr(o, "unit_singular", "$.metering_item"),
    unit_plural: reqStr(o, "unit_plural", "$.metering_item"),
    value: reqNum(o, "value", "$.metering_item"),
  };
  return out;
};

export const decodePR: Decoder<PR> = (v) => {
  const o = asObject(v, "$.pr");
  const out: PR = {
    title: reqStr(o, "title", "$.pr"),
    state: reqStr(o, "state", "$.pr"),
    source_branch: reqStr(o, "source_branch", "$.pr"),
    target_branch: reqStr(o, "target_branch", "$.pr"),
    number: reqNum(o, "number", "$.pr"),
  };
  const body = optStr(o, "body", "$.pr");
  if (body !== undefined) out.body = body;
  const author = optStr(o, "author", "$.pr");
  if (author !== undefined) out.author = author;
  const url = optStr(o, "url", "$.pr");
  if (url !== undefined) out.url = url;
  const createdAt = optNum(o, "created_at", "$.pr");
  if (createdAt !== undefined) out.created_at = createdAt;
  const updatedAt = optNum(o, "updated_at", "$.pr");
  if (updatedAt !== undefined) out.updated_at = updatedAt;
  const mergeable = optBool(o, "mergeable", "$.pr");
  if (mergeable !== undefined) out.mergeable = mergeable;
  const draft = optBool(o, "draft", "$.pr");
  if (draft !== undefined) out.draft = draft;
  return out;
};

export const decodePendingChange: Decoder<PendingChange> = (v) => {
  const o = asObject(v, "$.pending_change");
  const out: PendingChange = {
    tool_call_id: reqStr(o, "tool_call_id", "$.pending_change"),
    chat_id: reqStr(o, "chat_id", "$.pending_change"),
    path: reqStr(o, "path", "$.pending_change"),
    kind: reqOneOf(o, "kind", PENDING_CHANGE_KINDS, "$.pending_change"),
    created_at: reqNum(o, "created_at", "$.pending_change"),
  };
  const oldText = optStr(o, "old_text", "$.pending_change");
  if (oldText !== undefined) out.old_text = oldText;
  const newText = optStr(o, "new_text", "$.pending_change");
  if (newText !== undefined) out.new_text = newText;
  const truncated = optBool(o, "truncated", "$.pending_change");
  if (truncated !== undefined) out.truncated = truncated;
  return out;
};

export const decodePendingChangeAddedPayload: Decoder<PendingChangeAddedPayload> = (v) => {
  const o = asObject(v, "$.pending_change_added_payload");
  const out: PendingChangeAddedPayload = {
    change: decodePendingChange(o["change"]),
  };
  return out;
};

export const decodePendingChangeResolvedPayload: Decoder<PendingChangeResolvedPayload> = (v) => {
  const o = asObject(v, "$.pending_change_resolved_payload");
  const out: PendingChangeResolvedPayload = {
    tool_call_id: reqStr(o, "tool_call_id", "$.pending_change_resolved_payload"),
    action: reqOneOf(o, "action", PENDING_ACTIONS, "$.pending_change_resolved_payload"),
  };
  const path = optStr(o, "path", "$.pending_change_resolved_payload");
  if (path !== undefined) out.path = path;
  return out;
};

export const decodePendingChangesClearedPayload: Decoder<PendingChangesClearedPayload> = (v) => {
  const o = asObject(v, "$.pending_changes_cleared_payload");
  const out: PendingChangesClearedPayload = {
  };
  if (o["reason"] !== undefined) out.reason = reqOneOf(o, "reason", CLEAR_REASONS, "$.pending_changes_cleared_payload");
  return out;
};

export const decodePermissionNeededPayload: Decoder<PermissionNeededPayload> = (v) => {
  const o = asObject(v, "$.permission_needed_payload");
  const out: PermissionNeededPayload = {
    options: decodeArray(o["options"], decodePermissionOption, "$.permission_needed_payload.options"),
    request_id: reqNum(o, "request_id", "$.permission_needed_payload"),
  };
  const toolCallId = optStr(o, "tool_call_id", "$.permission_needed_payload");
  if (toolCallId !== undefined) out.tool_call_id = toolCallId;
  const title = optStr(o, "title", "$.permission_needed_payload");
  if (title !== undefined) out.title = title;
  if (o["kind"] !== undefined) out.kind = reqOneOf(o, "kind", TOOL_KINDS, "$.permission_needed_payload");
  const subSessionId = optStr(o, "sub_session_id", "$.permission_needed_payload");
  if (subSessionId !== undefined) out.sub_session_id = subSessionId;
  return out;
};

export const decodePermissionOption: Decoder<PermissionOption> = (v) => {
  const o = asObject(v, "$.permission_option");
  const out: PermissionOption = {
    option_id: reqStr(o, "option_id", "$.permission_option"),
    name: reqStr(o, "name", "$.permission_option"),
    kind: reqStr(o, "kind", "$.permission_option"),
  };
  return out;
};

export const decodePlanEntry: Decoder<PlanEntry> = (v) => {
  const o = asObject(v, "$.plan_entry");
  const out: PlanEntry = {
    content: reqStr(o, "content", "$.plan_entry"),
    priority: reqStr(o, "priority", "$.plan_entry"),
    status: reqOneOf(o, "status", PLAN_STATUSS, "$.plan_entry"),
  };
  return out;
};

export const decodePollResult: Decoder<PollResult> = (v) => {
  const o = asObject(v, "$.poll_result");
  const out: PollResult = {
    status: reqStr(o, "status", "$.poll_result"),
  };
  const error = optStr(o, "error", "$.poll_result");
  if (error !== undefined) out.error = error;
  return out;
};

export const decodeRelease: Decoder<Release> = (v) => {
  const o = asObject(v, "$.release");
  const out: Release = {
    tag_name: reqStr(o, "tag_name", "$.release"),
  };
  const name = optStr(o, "name", "$.release");
  if (name !== undefined) out.name = name;
  const body = optStr(o, "body", "$.release");
  if (body !== undefined) out.body = body;
  const url = optStr(o, "url", "$.release");
  if (url !== undefined) out.url = url;
  const publishedAt = optNum(o, "published_at", "$.release");
  if (publishedAt !== undefined) out.published_at = publishedAt;
  const draft = optBool(o, "draft", "$.release");
  if (draft !== undefined) out.draft = draft;
  const prerelease = optBool(o, "prerelease", "$.release");
  if (prerelease !== undefined) out.prerelease = prerelease;
  return out;
};

export const decodeRepo: Decoder<Repo> = (v) => {
  const o = asObject(v, "$.repo");
  const out: Repo = {
    owner: reqStr(o, "owner", "$.repo"),
    name: reqStr(o, "name", "$.repo"),
    full_name: reqStr(o, "full_name", "$.repo"),
  };
  const defaultBranch = optStr(o, "default_branch", "$.repo");
  if (defaultBranch !== undefined) out.default_branch = defaultBranch;
  const url = optStr(o, "url", "$.repo");
  if (url !== undefined) out.url = url;
  const cloneUrl = optStr(o, "clone_url", "$.repo");
  if (cloneUrl !== undefined) out.clone_url = cloneUrl;
  const description = optStr(o, "description", "$.repo");
  if (description !== undefined) out.description = description;
  const privateVal = optBool(o, "private", "$.repo");
  if (privateVal !== undefined) out.private = privateVal;
  const archived = optBool(o, "archived", "$.repo");
  if (archived !== undefined) out.archived = archived;
  const fork = optBool(o, "fork", "$.repo");
  if (fork !== undefined) out.fork = fork;
  const updatedAt = optNum(o, "updated_at", "$.repo");
  if (updatedAt !== undefined) out.updated_at = updatedAt;
  return out;
};

export const decodeSessionMode: Decoder<SessionMode> = (v) => {
  const o = asObject(v, "$.session_mode");
  const out: SessionMode = {
    id: reqStr(o, "id", "$.session_mode"),
    name: reqStr(o, "name", "$.session_mode"),
  };
  const description = optStr(o, "description", "$.session_mode");
  if (description !== undefined) out.description = description;
  return out;
};

export const decodeSessionModel: Decoder<SessionModel> = (v) => {
  const o = asObject(v, "$.session_model");
  const out: SessionModel = {
    id: reqStr(o, "id", "$.session_model"),
    name: reqStr(o, "name", "$.session_model"),
  };
  const description = optStr(o, "description", "$.session_model");
  if (description !== undefined) out.description = description;
  const rateMultiplier = optNum(o, "rate_multiplier", "$.session_model");
  if (rateMultiplier !== undefined) out.rate_multiplier = rateMultiplier;
  return out;
};

export const decodeToolCall: Decoder<ToolCall> = (v) => {
  const o = asObject(v, "$.tool_call");
  const out: ToolCall = {
    id: reqStr(o, "id", "$.tool_call"),
    title: reqStr(o, "title", "$.tool_call"),
    kind: reqOneOf(o, "kind", TOOL_KINDS, "$.tool_call"),
    status: reqOneOf(o, "status", TOOL_STATUSS, "$.tool_call"),
    ts: reqNum(o, "ts", "$.tool_call"),
  };
  const output = optStr(o, "output", "$.tool_call");
  if (output !== undefined) out.output = output;
  const subSessionId = optStr(o, "sub_session_id", "$.tool_call");
  if (subSessionId !== undefined) out.sub_session_id = subSessionId;
  if (o["input"] !== undefined) out.input = o["input"] as unknown;
  if (o["locations"] !== undefined) out.locations = decodeArray(o["locations"], decodeToolLocation, "$.tool_call.locations");
  if (o["diffs"] !== undefined) out.diffs = decodeArray(o["diffs"], decodeToolDiff, "$.tool_call.diffs");
  const durationMs = optNum(o, "duration_ms", "$.tool_call");
  if (durationMs !== undefined) out.duration_ms = durationMs;
  return out;
};

export const decodeToolCallPayload: Decoder<ToolCallPayload> = (v) => {
  const o = asObject(v, "$.tool_call_payload");
  const out: ToolCallPayload = {
    message_id: reqStr(o, "message_id", "$.tool_call_payload"),
    tool_call: decodeToolCall(o["tool_call"]),
    block_index: reqNum(o, "block_index", "$.tool_call_payload"),
  };
  return out;
};

export const decodeToolCallUpdatePayload: Decoder<ToolCallUpdatePayload> = (v) => {
  const o = asObject(v, "$.tool_call_update_payload");
  const out: ToolCallUpdatePayload = {
    message_id: reqStr(o, "message_id", "$.tool_call_update_payload"),
    tool_call: decodeToolCall(o["tool_call"]),
  };
  return out;
};

export const decodeToolDiff: Decoder<ToolDiff> = (v) => {
  const o = asObject(v, "$.tool_diff");
  const out: ToolDiff = {
    path: reqStr(o, "path", "$.tool_diff"),
    new_text: reqStr(o, "new_text", "$.tool_diff"),
  };
  const oldText = optStr(o, "old_text", "$.tool_diff");
  if (oldText !== undefined) out.old_text = oldText;
  return out;
};

export const decodeToolLocation: Decoder<ToolLocation> = (v) => {
  const o = asObject(v, "$.tool_location");
  const out: ToolLocation = {
    path: reqStr(o, "path", "$.tool_location"),
  };
  const line = optNum(o, "line", "$.tool_location");
  if (line !== undefined) out.line = line;
  return out;
};

export const decodeTurnEndedPayload: Decoder<TurnEndedPayload> = (v) => {
  const o = asObject(v, "$.turn_ended_payload");
  const out: TurnEndedPayload = {
  };
  if (o["changed_files"] !== undefined) out.changed_files = decodeRecord(o["changed_files"], decodeFileChange, "$.turn_ended_payload.changed_files");
  if (o["stop_reason"] !== undefined) out.stop_reason = reqOneOf(o, "stop_reason", STOP_REASONS, "$.turn_ended_payload");
  const creditsDelta = optNum(o, "credits_delta", "$.turn_ended_payload");
  if (creditsDelta !== undefined) out.credits_delta = creditsDelta;
  const elapsedMs = optNum(o, "elapsed_ms", "$.turn_ended_payload");
  if (elapsedMs !== undefined) out.elapsed_ms = elapsedMs;
  return out;
};

export const decodeUsage: Decoder<Usage> = (v) => {
  const o = asObject(v, "$.usage");
  const out: Usage = {
    context_pct: reqNum(o, "context_pct", "$.usage"),
    context_size: reqNum(o, "context_size", "$.usage"),
    credits: reqNum(o, "credits", "$.usage"),
    turn_count: reqNum(o, "turn_count", "$.usage"),
    last_turn_ms: reqNum(o, "last_turn_ms", "$.usage"),
    has_real_data: reqBool(o, "has_real_data", "$.usage"),
  };
  if (o["metering_items"] !== undefined) out.metering_items = decodeArray(o["metering_items"], decodeMeteringItem, "$.usage.metering_items");
  return out;
};

export const decodeUser: Decoder<User> = (v) => {
  const o = asObject(v, "$.user");
  const out: User = {
    login: reqStr(o, "login", "$.user"),
  };
  const name = optStr(o, "name", "$.user");
  if (name !== undefined) out.name = name;
  const email = optStr(o, "email", "$.user");
  if (email !== undefined) out.email = email;
  const url = optStr(o, "url", "$.user");
  if (url !== undefined) out.url = url;
  return out;
};

export const decodeWhoamiResponse: Decoder<WhoamiResponse> = (v) => {
  const o = asObject(v, "$.whoami_response");
  const out: WhoamiResponse = {
  };
  const email = optStr(o, "email", "$.whoami_response");
  if (email !== undefined) out.email = email;
  const auth = optStr(o, "auth", "$.whoami_response");
  if (auth !== undefined) out.auth = auth;
  const accountType = optStr(o, "accountType", "$.whoami_response");
  if (accountType !== undefined) out.accountType = accountType;
  const startUrl = optStr(o, "startUrl", "$.whoami_response");
  if (startUrl !== undefined) out.startUrl = startUrl;
  const region = optStr(o, "region", "$.whoami_response");
  if (region !== undefined) out.region = region;
  const error = optStr(o, "error", "$.whoami_response");
  if (error !== undefined) out.error = error;
  return out;
};

