// CODE-GENERATED by cmd/wire-codegen, DO NOT EDIT.

import { registerSSEDecoder } from "../bus.js";
import { decodeChatDeletedPayload, decodeChatHeader, decodeCommandsUpdatedPayload, decodeConnectedPayload, decodeErrorPayload, decodeMCPConnectedPayload, decodeMCPDisconnectedPayload, decodeMCPFailedPayload, decodeMCPOAuthPayload, decodeMessage, decodeMessageChunkPayload, decodePendingChangeAddedPayload, decodePendingChangeResolvedPayload, decodePendingChangesClearedPayload, decodePermissionNeededPayload, decodeToolCallPayload, decodeToolCallUpdatePayload, decodeTurnEndedPayload } from "./decoders.gen.js";

export function registerAllSSEDecoders(): void {
  registerSSEDecoder("chat_created", decodeChatHeader);
  registerSSEDecoder("chat_deleted", decodeChatDeletedPayload);
  registerSSEDecoder("chat_updated", decodeChatHeader);
  registerSSEDecoder("commands_updated", decodeCommandsUpdatedPayload);
  registerSSEDecoder("connected", decodeConnectedPayload);
  registerSSEDecoder("error", decodeErrorPayload);
  registerSSEDecoder("mcp_connected", decodeMCPConnectedPayload);
  registerSSEDecoder("mcp_disconnected", decodeMCPDisconnectedPayload);
  registerSSEDecoder("mcp_failed", decodeMCPFailedPayload);
  registerSSEDecoder("mcp_oauth_needed", decodeMCPOAuthPayload);
  registerSSEDecoder("message_appended", decodeMessage);
  registerSSEDecoder("message_chunk", decodeMessageChunkPayload);
  registerSSEDecoder("message_created", decodeMessage);
  registerSSEDecoder("message_updated", decodeMessage);
  registerSSEDecoder("pending_change_added", decodePendingChangeAddedPayload);
  registerSSEDecoder("pending_change_resolved", decodePendingChangeResolvedPayload);
  registerSSEDecoder("pending_changes_cleared", decodePendingChangesClearedPayload);
  registerSSEDecoder("permission_needed", decodePermissionNeededPayload);
  registerSSEDecoder("tool_call", decodeToolCallPayload);
  registerSSEDecoder("tool_call_update", decodeToolCallUpdatePayload);
  registerSSEDecoder("turn_ended", decodeTurnEndedPayload);
}
