// CODE-GENERATED by cmd/wire-codegen, DO NOT EDIT.

import { registerSSEDecoder } from "../bus.js";
import { decodeChatDeletedPayload, decodeChatHeader, decodeCodeReferencesPayload, decodeCommandsUpdatedPayload, decodeConnectedPayload, decodeElicitationNeededPayload, decodeErrorPayload, decodeGovernanceStatePayload, decodeKnowledgeIndexingPayload, decodeMCPConnectedPayload, decodeMCPDisconnectedPayload, decodeMCPFailedPayload, decodeMCPOAuthPayload, decodeMessage, decodeMessageChunkPayload, decodeOpenExternalURLPayload, decodePendingChangeAddedPayload, decodePendingChangeResolvedPayload, decodePendingChangesClearedPayload, decodePermissionNeededPayload, decodePermissionsChangedPayload, decodePolicyErrorPayload, decodeSafetyPropertiesPayload, decodeSafetyStatusPayload, decodeSpecTaskChangedPayload, decodeToolCallPayload, decodeToolCallUpdatePayload, decodeToolJobChangedPayload, decodeToolJobOutputPayload, decodeTurnEndedPayload } from "./decoders.gen.js";

export function registerAllSSEDecoders(): void {
  registerSSEDecoder("chat_created", decodeChatHeader);
  registerSSEDecoder("chat_deleted", decodeChatDeletedPayload);
  registerSSEDecoder("chat_updated", decodeChatHeader);
  registerSSEDecoder("code_references", decodeCodeReferencesPayload);
  registerSSEDecoder("commands_updated", decodeCommandsUpdatedPayload);
  registerSSEDecoder("connected", decodeConnectedPayload);
  registerSSEDecoder("elicitation_needed", decodeElicitationNeededPayload);
  registerSSEDecoder("error", decodeErrorPayload);
  registerSSEDecoder("governance_state", decodeGovernanceStatePayload);
  registerSSEDecoder("knowledge_indexing", decodeKnowledgeIndexingPayload);
  registerSSEDecoder("mcp_connected", decodeMCPConnectedPayload);
  registerSSEDecoder("mcp_disconnected", decodeMCPDisconnectedPayload);
  registerSSEDecoder("mcp_failed", decodeMCPFailedPayload);
  registerSSEDecoder("mcp_oauth_needed", decodeMCPOAuthPayload);
  registerSSEDecoder("message_appended", decodeMessage);
  registerSSEDecoder("message_chunk", decodeMessageChunkPayload);
  registerSSEDecoder("message_created", decodeMessage);
  registerSSEDecoder("message_updated", decodeMessage);
  registerSSEDecoder("open_external_url", decodeOpenExternalURLPayload);
  registerSSEDecoder("pending_change_added", decodePendingChangeAddedPayload);
  registerSSEDecoder("pending_change_resolved", decodePendingChangeResolvedPayload);
  registerSSEDecoder("pending_changes_cleared", decodePendingChangesClearedPayload);
  registerSSEDecoder("permission_needed", decodePermissionNeededPayload);
  registerSSEDecoder("permissions_changed", decodePermissionsChangedPayload);
  registerSSEDecoder("policy_error", decodePolicyErrorPayload);
  registerSSEDecoder("safety_properties", decodeSafetyPropertiesPayload);
  registerSSEDecoder("safety_status", decodeSafetyStatusPayload);
  registerSSEDecoder("spec_task_changed", decodeSpecTaskChangedPayload);
  registerSSEDecoder("tool_call", decodeToolCallPayload);
  registerSSEDecoder("tool_call_update", decodeToolCallUpdatePayload);
  registerSSEDecoder("tool_job_changed", decodeToolJobChangedPayload);
  registerSSEDecoder("tool_job_output", decodeToolJobOutputPayload);
  registerSSEDecoder("turn_ended", decodeTurnEndedPayload);
}
