// CODE-GENERATED by cmd/wire-codegen, DO NOT EDIT.

import { registerSSEDecoder } from "../bus.js";
import { decodeChatDeletedPayload, decodeChatHeader, decodeCodeReferencesPayload, decodeConnectedPayload, decodeElicitationNeededPayload, decodeErrorPayload, decodeGovernanceStatePayload, decodeMCPConnectedPayload, decodeMCPDisconnectedPayload, decodeMCPFailedPayload, decodeMCPOAuthPayload, decodeMessage, decodeMessageChunkPayload, decodeOpenExternalURLPayload, decodePermissionNeededPayload, decodePermissionsChangedPayload, decodePolicyErrorPayload, decodeRunFinishedPayload, decodeRunProgressPayload, decodeRunStartedPayload, decodeSafetyPropertiesPayload, decodeSafetyStatusPayload, decodeSteerClearedPayload, decodeSteerInjectedPayload, decodeSteerQueuedPayload, decodeToolCallPayload, decodeToolCallUpdatePayload, decodeToolJobChangedPayload, decodeToolJobOutputPayload, decodeTurnEndedPayload, decodeTurnStatePayload, decodeUserInputNeededPayload } from "./decoders.gen.js";

export function registerAllSSEDecoders(): void {
  registerSSEDecoder("chat_created", decodeChatHeader);
  registerSSEDecoder("chat_deleted", decodeChatDeletedPayload);
  registerSSEDecoder("chat_updated", decodeChatHeader);
  registerSSEDecoder("code_references", decodeCodeReferencesPayload);
  registerSSEDecoder("connected", decodeConnectedPayload);
  registerSSEDecoder("elicitation_needed", decodeElicitationNeededPayload);
  registerSSEDecoder("user_input_needed", decodeUserInputNeededPayload);
  registerSSEDecoder("error", decodeErrorPayload);
  registerSSEDecoder("governance_state", decodeGovernanceStatePayload);
  registerSSEDecoder("mcp_connected", decodeMCPConnectedPayload);
  registerSSEDecoder("mcp_disconnected", decodeMCPDisconnectedPayload);
  registerSSEDecoder("mcp_failed", decodeMCPFailedPayload);
  registerSSEDecoder("mcp_oauth_needed", decodeMCPOAuthPayload);
  registerSSEDecoder("message_appended", decodeMessage);
  registerSSEDecoder("message_chunk", decodeMessageChunkPayload);
  registerSSEDecoder("message_created", decodeMessage);
  registerSSEDecoder("message_updated", decodeMessage);
  registerSSEDecoder("open_external_url", decodeOpenExternalURLPayload);
  registerSSEDecoder("permission_needed", decodePermissionNeededPayload);
  registerSSEDecoder("permissions_changed", decodePermissionsChangedPayload);
  registerSSEDecoder("policy_error", decodePolicyErrorPayload);
  registerSSEDecoder("run_started", decodeRunStartedPayload);
  registerSSEDecoder("run_progress", decodeRunProgressPayload);
  registerSSEDecoder("run_finished", decodeRunFinishedPayload);
  registerSSEDecoder("safety_properties", decodeSafetyPropertiesPayload);
  registerSSEDecoder("safety_status", decodeSafetyStatusPayload);
  registerSSEDecoder("tool_call", decodeToolCallPayload);
  registerSSEDecoder("tool_call_update", decodeToolCallUpdatePayload);
  registerSSEDecoder("tool_job_changed", decodeToolJobChangedPayload);
  registerSSEDecoder("tool_job_output", decodeToolJobOutputPayload);
  registerSSEDecoder("steer_queued", decodeSteerQueuedPayload);
  registerSSEDecoder("steer_injected", decodeSteerInjectedPayload);
  registerSSEDecoder("steer_cleared", decodeSteerClearedPayload);
  registerSSEDecoder("turn_ended", decodeTurnEndedPayload);
  registerSSEDecoder("turn_state", decodeTurnStatePayload);
}
