// CODE-GENERATED by cmd/wire-codegen, DO NOT EDIT.

export type AlwaysAllowBlock = "unparseable";

export type CatalogReason = "rpc" | "decode";

export type CatalogState = "ready" | "empty" | "unavailable";

export type DecisionKind = "permission" | "elicitation" | "user_input";

export type ErrorCode = "recovery_failed" | "bridge_start_failed" | "prompt_failed" | "agent_not_found" | "agent_config_error" | "rate_limit" | "switch_failed" | "compaction_failed" | "mode_not_applied" | "model_not_served" | "auth_token_unavailable";

export type EventKind = "interrupted" | "cancelled" | "model_switched" | "compacted" | "compaction_failed" | "infra_safety_blocked" | "turn_outcome" | "step_notice";

export type ForgeKind = "github" | "gitlab" | "gitea" | "codeberg";

export type PlanStatus = "pending" | "in_progress" | "completed";

export type ReadState = "ready" | "unavailable";

export type Role = "user" | "assistant" | "event";

export type RunNodeStatus = "pending" | "running" | "paused" | "completed" | "failed" | "aborted" | "skipped";

export type RunProgressKind = "node_start" | "node_complete" | "node_paused" | "loop_iteration" | "watch_poll" | "paused" | "steps_queued";

export type RunStatus = "running" | "paused" | "completed" | "failed" | "aborted" | "cancelled";

export type RunStepTranscriptState = "ready" | "gone" | "unavailable";

export type SafetyStatus = "idle" | "formalizing" | "evaluating" | "blocked" | "error";

export type SettledBy = "user" | "unattended" | "moot";

export type SteerOrigin = "user" | "agent";

export type SteerState = "read" | "dropped";

export type StopReason = "end_turn" | "cancelled" | "interrupted" | "refusal" | "unknown" | "error" | "content_filtered" | "max_tokens" | "max_turn_requests";

export type TabKind = "chat" | "editor" | "run" | "subagent" | "settings" | "git" | "files" | "history" | "docs";

export type ToolKind = "execute" | "shell" | "read" | "search" | "fetch" | "edit" | "think" | "hook" | "write" | "delete" | "move" | "command" | "browser" | "switch_mode" | "mcp" | "other";

export type ToolStatus = "pending" | "in_progress" | "completed" | "failed" | "aborted";

export type Transport = "stdio" | "http" | "sse";

export type TurnOutcome = "running" | "completed" | "cancelled" | "interrupted" | "failed" | "refused" | "unknown";

export type TurnSeverity = "running" | "clean" | "stopped" | "broken";

export type UserKind = "prompt" | "steer";

export type WhoamiState = "signed_in" | "signed_out" | "unavailable";

/**
 * AccountUsage is the account/subscription usage snapshot for the
 * signed-in identity.
 */
export interface AccountUsage {
  /** PlanName is the subscription title (e.g. "KIRO POWER"). */
  plan_name?: string;
  /** BillingCycleReset is the YYYY-MM-DD reset date, or "" when unknown. */
  billing_cycle_reset?: string;
  /**
 * FetchedAt is the RFC3339 timestamp of the fetch that produced this
 * snapshot, so the client can show freshness.
 */
  fetched_at?: string;
  /**
 * Note carries a human-readable status for degraded states (e.g. an
 * admin-managed plan that returns no breakdowns).
 */
  note?: string;
  /**
 * Breakdowns is the per-resource usage list (typically a single
 * CREDIT entry).
 */
  breakdowns: AccountUsageBreakdown[];
  /** IsEnterprise reports whether the plan is an enterprise/managed plan. */
  is_enterprise?: boolean;
  /** OveragesEnabled reports whether overage billing is enabled. */
  overages_enabled?: boolean;
  /**
 * Stale is true when this snapshot was served from the last-known
 * cache because a fresh fetch failed (no live bridge, rate limit).
 */
  stale?: boolean;
}

/**
 * AccountUsageBreakdown is one resource line of an AccountUsage (e.g.
 * credits). Used/Limit are precision floats as reported by KAS.
 */
export interface AccountUsageBreakdown {
  /** ResourceType is the KAS resource key (e.g. "CREDIT"). */
  resource_type?: string;
  /** DisplayName is the human label (e.g. "Credits"). */
  display_name?: string;
  /** Currency is the ISO currency for monetary fields (e.g. "USD"). */
  currency?: string;
  /** Used is the amount consumed this cycle. */
  used: number;
  /** Limit is the plan allowance; meaningful only when HasLimit is true. */
  limit: number;
  /** CurrentOverages is the amount consumed beyond Limit. */
  current_overages?: number;
  /** OverageCharges is the monetary overage charge in Currency. */
  overage_charges?: number;
  /** Percentage is floor(Used/Limit*100); can exceed 100 on overage. */
  percentage: number;
  /** HasLimit reports whether Limit is a real cap (false = unlimited). */
  has_limit?: boolean;
}

/**
 * AgentNoticePayload is the payload for type="agent_notice": a progress notice a workflow step
 * or subagent reported into the session that launched it. KAS decides this by sniffing the text
 * for a `[notification/<severity>]` prefix and delivers it through the steering buffer, and
 * vibekit refuses to SEND that shape, so a notice here is never the user's words. Severity
 * (info/success/warning/error) is why this is its own event rather than a field on a steer: a
 * consumer never has to decide whose voice a message is in. There is no id — a notice has no
 * later state to address.
 */
export interface AgentNoticePayload {
  severity: string;
  text: string;
}

/** ApprovalFile is one file a turn wants to write, as offered for review. */
export interface ApprovalFile {
  /** Path is workspace-relative (KAS sends it absolute; translate normalizes). */
  path: string;
  /** SnapshotURI addresses the pre-image, so a diff is a snapshot read. */
  snapshot_uri?: string;
  /**
 * ActionID is KAS's pending-action id and THE KEY the decision map must use. KAS
 * restores every id the response omits, so omission counts as a REJECT.
 */
  action_id: string;
}

/**
 * AptPackage is one installed Debian package this engine does not
 * manage: something a user or an agent installed in the shell.
 * Read-only, with no manifest row behind it. Reported so a consumer's
 * tools surface can answer "what is on this box" without pretending the
 * engine installed it.
 */
export interface AptPackage {
  name: string;
  version?: string;
}

/**
 * Attachment is a file staged beside a prompt; its extension decides whether it
 * travels as a document content block or as a text path reference.
 */
export interface Attachment {
  path: string;
  name: string;
}

/**
 * Block is one entry in an assistant message's chronological content array. Within
 * ONE agent's stream, position IS emission order, so the client renders inline.
 * //
 * ACROSS streams it is NOT a global chronology: a parent and its delegates share
 * one array and internal/buffer extends the newest block of the delta's OWN
 * subtask, so a parent delta can land BEHIND a delegate's block. Order is per
 * AgentSubtaskID; Content carries arrival order. Nil on a message persisted
 * before the field existed, where a renderer falls back to Content + ToolCalls.
 */
export interface Block {
  /** Type is the discriminator: text | tool_use | thinking. */
  type: string;
  /**
 * Text is the markdown for Type=BlockText, accumulated across the
 * MessageChunkPayload events targeting this block index.
 */
  text?: string;
  /** Thinking carries the reasoning text for Type=BlockThinking. */
  thinking?: string;
  /** ToolCallID references a Message.ToolCalls entry for Type=BlockToolUse. */
  tool_call_id?: string;
  /**
 * AgentSubtaskID is the subtask id of the agent that produced this block, ""
 * for the top-level one. It is what lets the client nest a subagent's blocks.
 */
  agent_subtask_id?: string;
}

/**
 * CatalogInfo reports the live catalog's provenance and freshness (the
 * Engine.CatalogInfo return and the httpapi GET catalog body).
 */
export interface CatalogInfo {
  /**
 * Refs are the upstream registry refs the catalog was compiled
 * from; Generated its compile timestamp (RFC 3339 UTC). Both are
 * informational pass-throughs of the catalog document.
 */
  refs?: Record<string, string>;
  generated?: string;
  /**
 * Source is where the live catalog came from: baked (the image
 * file), cached (the refresh cache, reloaded at boot), remote
 * (fetched this process lifetime), or none (degraded, no catalog).
 */
  source: string;
  /**
 * URL is the configured refresh source (empty when refresh is not
 * configured).
 */
  url?: string;
  /**
 * LastError is the most recent refresh failure ("" after a
 * successful refresh).
 */
  last_error?: string;
  entries: number;
  /**
 * Unavailable counts the entries the catalog knows about and cannot
 * install. Beside Entries it is the operator's read on whether a
 * registry bump changed what is reachable: a jump in this number with
 * Entries falling is upstream moving tools onto a backend the
 * compiler does not support.
 */
  unavailable: number;
  /**
 * FetchedAt is the last successful refresh (Unix milliseconds; 0
 * before the first).
 */
  fetched_at?: number;
  /**
 * Scheduled reports whether the engine-owned background refresh
 * loop is running.
 */
  scheduled: boolean;
}

/** ChatDeletedPayload is the payload for type="chat_deleted". */
export interface ChatDeletedPayload {
  id: string;
}

/**
 * ChatHeader is the metadata-only view of a Chat. Field order is fieldalignment's,
 * not Chat's; the two serialise independently, so the mismatch is harmless.
 */
export interface ChatHeader {
  name: string;
  model?: string;
  acp_session_id?: string;
  current_mode_id?: string;
  /**
 * Effort mirrors Chat's, because the effort control reads the ACTIVE chat's
 * level and an empty chat never fetches its full record, so the header is the
 * only path that reaches every chat. Chat.Draft is deliberately NOT mirrored.
 */
  effort?: string;
  /**
 * LastTurnOutcome is how this chat's NEWEST finished turn ended, DERIVED on
 * every read from the last message carrying a TurnOutcome — a second copy
 * would be a second thing that can be wrong. Here because the header is the
 * only projection reaching every chat, which is what the tab dot needs.
 * //
 * Empty for a chat with no finished turn and for older records (invariant 5
 * forbids the backfill). Never `running`.
 */
  last_turn_outcome?: TurnOutcome;
  /**
 * EffortActive + EffortLevels mirror Chat's, for the same reason Effort does:
 * the control renders from the ACTIVE chat's header.
 */
  effort_active?: string;
  effort_levels?: SessionEffortLevel[];
  /**
 * The model and mode vocabulary is a WORKSPACE fact served once by
 * agent.Catalog, never mirrored per header.
 */
  id: string;
  compaction_watermark?: string;
  /**
 * PriorACPSessionIDs mirrors Chat's, because the retention sweep derives its
 * keep-list from header reads rather than loading every chat in full.
 */
  prior_acp_session_ids?: string[];
  usage: Usage;
  created_at: number;
  updated_at: number;
  message_count: number;
  supervised_mode?: boolean;
}

/** Check is a single CI status check for a commit. */
export interface Check {
  name: string;
  status: string;
  conclusion: string;
  url?: string;
}

/**
 * CodeReference is one licensed-code attribution, emitted when a completion
 * reproduces a recognizable chunk of a referenced open-source file.
 * //
 * KAS drops CodeWhisperer's recommendationContentSpan upstream, so there is no span
 * to map a reference to a message region: attributions are TURN-scoped.
 */
export interface CodeReference {
  license_name: string;
  repository?: string;
  url?: string;
}

/**
 * CodeReferencesPayload is the payload for type="code_references": the licensed-code
 * attributions on the in-flight assistant turn. References is the full deduped list, so a
 * later notification REPLACES rather than appends. Also persisted on the Message.
 */
export interface CodeReferencesPayload {
  message_id: string;
  references: CodeReference[];
}

/**
 * ConfigTemplateResponse is the GET /api/config-template reply: the pre-session
 * mode + model catalog, plus the verdict that says which outcome produced it.
 * //
 * Named …Response rather than …Payload because it is bound to no SSE event;
 * internal/wirespec's binding tests key on the Payload suffix, and
 * auth.WhoamiResponse is the precedent.
 */
export interface ConfigTemplateResponse {
  default_model?: string;
  /**
 * EffortActive is the `effortLevel` option's currentValue: the tier a
 * fresh session would run at. Pre-session, this is the only evidence of
 * a live level.
 */
  effort_active?: string;
  /**
 * Catalog carries NO omitempty deliberately: wiregen emits a required
 * TypeScript field for a field without it, so a client cannot invent a
 * fallback for the one value the whole retry policy reads.
 */
  catalog: CatalogState;
  catalog_reason?: CatalogReason;
  /**
 * The three lists are non-null on every path, degrade branches included, so a
 * generated decoder requiring an array cannot fail on a failure body.
 */
  modes: SessionMode[];
  models: SessionModel[];
  effort_levels: SessionEffortLevel[];
}

/**
 * ConfiguredForge is one connected forge backend, discovered through
 * the CLIs' own status subcommands (see discover.go).
 */
export interface ConfiguredForge {
  id: string;
  kind: ForgeKind;
  host: string;
  username?: string;
  email?: string;
  last_error?: string;
  last_probed?: number;
  connected: boolean;
  /**
 * CLIMissing marks a connection whose backing CLI binary is absent
 * (uninstalled/disabled in Settings → Tools, or a fresh tools volume
 * against a kept config volume) while a configuration for it still
 * exists. The row renders as a warning with a reinstall pointer; it
 * is never probed and cannot be disconnected until the CLI returns.
 */
  cli_missing?: boolean;
}

/**
 * ConnectedPayload is the payload for type="connected", the SSE handshake. Floor is the
 * oldest event ID still in the replay ring, Head the newest; a client whose last-seen id
 * is below Floor missed events and must refetch authoritative state.
 */
export interface ConnectedPayload {
  /**
 * Workspace is the absolute workspace root, needed from the first frame because the
 * client cannot derive it: ACP-supplied paths arrive workspace-RELATIVE while the
 * /api/file* surface is container-ABSOLUTE, and opening a changed file rejoins them.
 */
  workspace?: string;
  /**
 * BusyChats is every chat with a turn in flight of its OWN at connect: an open
 * turn that is not a workflow step, or an admitted prompt whose Turn is not
 * minted yet — and it is a NEGATIVE statement about every chat it does
 * not name, the half no other frame carries: a chat whose turn died with the
 * previous process gets no turn_state, and nothing else ever tells this client to
 * stop believing its own `thinking`.
 * //
 * The reservation term is what makes the negative statement COMPLETE for the
 * admission window; see busyChatIDs, which walks the lifecycle rather than the open
 * turns for exactly that reason.
 * //
 * CAPPED at maxBusyChats, with the overflow reported through BusyStated rather than
 * as a truncated list: a partial list read as complete would clear a live turn.
 */
  busy_chats?: string[];
  /**
 * LiveRuns is every run vibekit's lease registry says is in flight, the same
 * projection GET /api/runs/live serves. Here because every connect wants it and the
 * client's own fetch was three serialized round trips behind whoami; costs no KAS
 * call, because the projection is a lease-store read.
 * //
 * Emitted for a topic-filtered connect too: the inventory is workspace-global, so
 * there is nothing to scope. CAPPED at maxConnectLiveRuns — see LiveRunsStated.
 */
  live_runs?: LiveRun[];
  floor: number;
  head: number;
  /**
 * BusyStated says whether BusyChats is the COMPLETE set, and it is the ONE flag two
 * conditions clear: a topic-filtered connect (the list is scoped) and an over-cap
 * workspace (the list is withheld). No omitempty, so wiregen emits a REQUIRED field
 * and an absent marker can never read as "stated" — the discipline
 * TurnStatePayload.Truncated already follows.
 */
  busy_stated: boolean;
  /**
 * LiveRunsStated says whether LiveRuns is the COMPLETE inventory. False only when
 * the lease store holds more than maxConnectLiveRuns rows, in which case the list
 * is WITHHELD and the client falls back to its own GET /api/runs/live.
 * //
 * It exists because the client CLEARS its inventory before repopulating it, so a
 * truncated list would silently drop runs — and an empty LiveRuns is otherwise
 * indistinguishable from "no runs are live". No omitempty, for BusyStated's reason.
 */
  live_runs_stated: boolean;
}

/**
 * DecisionSettledPayload is the payload for type="decision_settled": the request named
 * here was answered, and not by the surface reading this. A decision is offered on EVERY
 * surface at once while only one answer is accepted, so without this event the losers keep
 * a live-looking card for a closed question.
 */
export interface DecisionSettledPayload {
  kind: DecisionKind;
  settled_by: SettledBy;
  request_id: number;
}

/** DeviceFlowResponse describes a started OAuth device flow. */
export interface DeviceFlowResponse {
  user_code: string;
  verification_uri: string;
  device_code: string;
  interval: number;
  expires_in: number;
}

/**
 * DraftChangedPayload is the payload for type="draft_changed": the composer state one chat
 * now holds, sent so an idle device converges on a draft it is not typing. Both halves travel
 * on every frame and BOTH writers fill both, because the event describes the COMPOSER rather
 * than the field that moved. The set_draft reply carries only a byte count, which is not a
 * contradiction: that goes back to the device that already has the words.
 */
export interface DraftChangedPayload {
  text: string;
  attachments?: string[];
}

/**
 * EffectiveSettings is what GET /api/settings answers: the value in force for
 * every vibekit-owned preference the client renders, resolved against the stored
 * config.json rather than echoed from it.
 * //
 * NO FIELD CARRIES omitempty, and that is the contract rather than a style
 * choice. wiregen emits a REQUIRED TypeScript field for a Go field without
 * omitempty and an optional one for a field with it, so this struct generates an
 * interface whose every member is present. That is what lets the client delete
 * its own copies of these defaults: a reader cannot supply a fallback for a field
 * the type says is always there, so the drift class stops being representable
 * instead of being tested for.
 * //
 * It is a STRUCT rather than the map the handler used to emit, for two reasons.
 * A struct cannot omit a field, so completeness is a property of the type instead
 * of a property of whichever builder ran; and a struct is what wiregen can carry
 * into TypeScript, which is what stops the client's copy being hand-maintained.
 * The cost is that an unknown key in config.json does not reach the client — see
 * the handler for why that loses nothing.
 * //
 * The PATCH body is the PARTIAL of this type. Full shape to read, partial to
 * write, which is exactly what the two verbs mean.
 * //
 * FIELD ORDER IS ALIGNMENT-DRIVEN, not narrative: the strings precede the slice
 * (a slice's pointer is its first word, its len and cap are not) and both precede
 * every non-pointer field, which is what govet's fieldalignment demands. Grouping
 * these by topic instead costs 16 bytes of GC scan prefix and fails the gate.
 */
export interface EffectiveSettings {
  /**
 * Theme is "", "dark", "light" or "system". The empty string is a REAL value
 * meaning nothing has been chosen, which the client resolves to the OS
 * preference; it is deliberately not normalised to "system" here, because the
 * client's one-time paint-cache carry-across is reachable only while the
 * server says nothing.
 */
  theme: string;
  /** FBPath is the file-browser path to restore, "" to list the granted mounts. */
  fb_path: string;
  /**
 * LastModel and LastEffort are what a NEW chat opens on. Both are pure memory:
 * the value in force for an existing chat lives on that chat's record.
 */
  last_model: string;
  last_effort: string;
  /**
 * LastEffortModel is the model LastEffort was picked under; the seed applies
 * only to a chat running that model (settings.KeyLastEffortModel).
 */
  last_effort_model: string;
  /**
 * LastMergeMethod is the PR merge method picked last ("squash" or "rebase"),
 * the merge dialog's default. Empty means nothing picked yet.
 */
  last_merge_method: string;
  /**
 * AgentIgnoreFiles is the ignore-file basename list the agent read filter
 * applies. Its default is non-empty (settings.DefaultAgentIgnoreFiles), which
 * is why an absent key must not read as the zero value: the client rendered an
 * empty chip row while the filter was applying two patterns, and the first
 * edit persisted that emptiness.
 */
  agent_ignore_files: string[];
  /**
 * ChatRetentionDays is -1 (keep forever), 0 (delete on close) or a day count.
 * Zero is the most destructive value in the document, so absent must never
 * resolve to it.
 */
  chat_retention_days: number;
  /**
 * KnowledgeEnabled defaults TRUE, so it is the other key whose zero value is
 * the wrong answer: the index, its REST surface and its UI all predate the
 * switch, so an absent key read as false takes the knowledge tool away from
 * every existing install.
 */
  knowledge_enabled: boolean;
  /**
 * ToolSearchEnabled and MemoryEnabled both default off, matching kiro-cli and
 * the standing memory veto respectively.
 */
  tool_search_enabled: boolean;
  memory_enabled: boolean;
  /**
 * NotificationsEnabled is the push master switch, default off. The three per-kind
 * switches below default ON, mirroring push.kindRegistry — the polarity differs
 * between the master and the kinds on purpose, and that asymmetry is exactly
 * why the client must not guess either of them.
 */
  notifications_enabled: boolean;
  notify_agent_finished: boolean;
  notify_pr_status: boolean;
  notify_run_outcome: boolean;
  /**
 * SupervisedDefault seeds newly created chats; ScheduledAutoApprove decides an
 * unattended run's permission ask at its deadline and is fail-closed by
 * decision. DebugLogs raises the log level. All three default off.
 */
  supervised_default: boolean;
  scheduled_auto_approve: boolean;
  debug_logs: boolean;
}

/**
 * ElicitationNeededPayload is the SSE payload for type="elicitation_needed".
 * Mirrors PermissionNeededPayload's role: it carries everything the
 * client needs to render the dialog plus the RequestID to echo back in
 * the elicitation_response command. Mode is "form" or "url"; URL-mode
 * elicitations carry URL and no RequestedSchema.
 */
export interface ElicitationNeededPayload {
  requested_schema?: ElicitationRequestSchema;
  mode?: string;
  message?: string;
  url?: string;
  tool_call_id?: string;
  sub_session_id?: string;
  /**
 * RunID/NodeID: as on PermissionNeededPayload — a workflow step's ask,
 * attributed to its run and node from the step-session registry.
 */
  run_id?: string;
  node_id?: string;
  request_id: number;
}

/**
 * ElicitationPropertySchema describes one field in an elicitation form.
 * Type is the discriminator ("string" | "number" | "integer" |
 * "boolean" | "array"); the other fields are populated as relevant to
 * that type. Unset fields are omitted on the wire.
 */
export interface ElicitationPropertySchema {
  default?: unknown;
  minLength?: number;
  maxLength?: number;
  type: string;
  title?: string;
  description?: string;
  format?: string;
  pattern?: string;
  enum?: string[];
}

/**
 * ElicitationRequestSchema is the JSON-schema-shaped object describing a
 * form: a map of property name to its schema, plus the required set.
 */
export interface ElicitationRequestSchema {
  type?: string;
  title?: string;
  description?: string;
  properties?: Record<string, ElicitationPropertySchema>;
  required?: string[];
}

/** ErrorPayload is the payload for type="error"; Code lets clients react per-class. */
export interface ErrorPayload {
  code: ErrorCode;
  message: string;
  /**
 * TurnScoped reports that this failure finalized a turn now carrying the same Message
 * durably, so the reason is already in that turn's card. A property of the EMISSION,
 * not of the Code: three of the five emitters behind ErrCodePromptFailed and
 * ErrCodeRecoveryFailed never open a turn, so no per-code answer fits both groups.
 * Absent means NO, the safe direction — report the failure rather than trust an inline
 * row that may not exist.
 */
  turn_scoped?: boolean;
}

/** FileChange tracks per-file change stats during a turn. */
export interface FileChange {
  lines_added: number;
  lines_removed: number;
  is_new_file?: boolean;
}

/**
 * GovernanceFeatures is the org/account feature-flag set carried by the v3 (KAS)
 * _kiro/governance/state notification. Every field is the RESOLVED effective value, so a
 * Builder-ID login reads permissive with isEnterprise=false and no disabledReason.
 * Infrastructure-Safety is NOT here: it rides a separate isFeatureEnabled channel, so the
 * safety banner is gated by KAS's own emission rather than by any field here.
 */
export interface GovernanceFeatures {
  /**
 * MCPEnabled reports whether the MCP subsystem is permitted; false means enterprise
 * governance suppressed MCP entirely.
 */
  mcp_enabled: boolean;
  /** WebToolsEnabled reports whether built-in web tools are permitted. */
  web_tools_enabled: boolean;
  /** UsageAnalytics reports whether usage analytics collection is enabled. */
  usage_analytics: boolean;
  /** ContentCollection reports whether content collection is enabled. */
  content_collection: boolean;
  /** PromptLogging reports whether prompt logging is enabled. */
  prompt_logging: boolean;
  /**
 * CodeReferenceTracker governs whether KAS emits _kiro/code_references at all, so the
 * attribution chip is dormant unless this is true.
 */
  code_reference_tracker: boolean;
  /** AutonomousAgents reports whether autonomous agent runs are permitted. */
  autonomous_agents: boolean;
}

/**
 * GovernanceStatePayload is the payload for type="governance_state". Governance is
 * account-global, so the wire sessionId is dropped and the SSE is broadcast with an empty
 * chat id; GET /api/governance serves the cached copy so a fresh page load can read it with
 * no chat open. Clients MUST gate affordances only when Known is true — the all-false zero
 * value otherwise reads as "everything disabled" when the policy is simply unobserved.
 */
export interface GovernanceStatePayload {
  /**
 * DisabledReason is a human-readable reason from enterprise governance (e.g. why
 * MCP is off); empty on a normal account.
 */
  disabled_reason?: string;
  /** Features is the resolved effective feature-flag set. */
  features: GovernanceFeatures;
  /**
 * Known is true once the real policy has been observed. Clients MUST only gate
 * affordances when it is true: the all-false zero value means "not yet known".
 */
  known: boolean;
  /** IsEnterprise reports whether this is an enterprise/managed account. */
  is_enterprise?: boolean;
}

/**
 * Inventory is the full read-side snapshot: every manifest entry joined
 * with state, the system group, and the active job.
 */
export interface Inventory {
  job?: Job;
  tools: ToolInfo[];
  system: SystemTool[];
  /**
 * AptPackages are installed Debian packages with no manifest row: the
 * ones a user or an agent installed themselves. Absent when apt is not
 * this host's package manager, or when the enumeration failed — an
 * inventory that cannot answer says nothing rather than reporting an
 * empty box as a fact.
 */
  apt_packages?: AptPackage[];
}

/** Issue represents a forge issue. */
export interface Issue {
  title: string;
  body?: string;
  state: string;
  author?: string;
  url?: string;
  labels?: string[];
  number: number;
  created_at?: number;
  updated_at?: number;
}

/** Job is one queued/running/finished unit of engine work. */
export interface Job {
  id: string;
  kind: string;
  state: string;
  error?: string;
  names?: string[];
  /**
 * CancelCause names who cancelled the job (State JobCancelled only).
 * Additive on the wire: omitted whenever the cause is unknown, so a
 * consumer that ignores the field sees exactly the payload it saw
 * before — JobCancelled keeps its meaning and value.
 */
  cancel_cause?: string;
  /**
 * OutputTail carries the job's most recent output lines; populated
 * by Jobs() snapshots only (live output streams via the
 * Config.OnJobOutput callback).
 */
  output_tail?: string[];
  /** Timestamps are Unix milliseconds. */
  created_at: number;
  started_at?: number;
  ended_at?: number;
}

/** JobResponse is the 202 body of every mutating route. */
export interface JobResponse {
  job?: Job;
}

/**
 * JobsResponse is the jobs route's body: the active job (with output
 * tail) and recent history.
 */
export interface JobsResponse {
  active?: Job;
  recent: Job[];
}

/** Label is a forge label (used on PRs and issues). */
export interface Label {
  name: string;
  color?: string;
  description?: string;
}

/**
 * LiveRun is one row of GET /api/runs/live: a run vibekit's own lease registry says
 * is in flight, named with the chat whose agent launched it. ChatID is empty for a
 * parentless run and for a lease predating the field — both mean "no chat to launch
 * a tab under". Executing is a FIELD rather than a filter applied here because
 * three consumers ask this row three different questions, and filtering for the
 * eviction sweep would take the row away from the tab dot and the tab parent.
 */
export interface LiveRun {
  workflow_id: string;
  chat_id: string;
  /**
 * Executing reports whether THIS PROCESS holds a deadline for the run. NOT
 * `status` and none of KAS's five, because serving one would mean an `inspect` per
 * lease on the client's boot path (runlease.Lease.Deadline owns the answer).
 * //
 * It can read false while KAS says running — a lease read back from disk is
 * parked, and `set_step_status` advances a step without re-arming — and both are
 * accepted: the client corrects itself on the run's next progress frame.
 */
  executing: boolean;
}

/** LiveRunsResponse is GET /api/runs/live's reply. */
export interface LiveRunsResponse {
  runs: LiveRun[];
}

/**
 * MCPConnectedPayload is the payload for type="mcp_connected", emitted
 * when kiro-cli reports _kiro.dev/mcp/server_initialized.
 */
export interface MCPConnectedPayload {
  server: string;
}

/**
 * MCPDisconnectedPayload is the payload for type="mcp_disconnected".
 * Emitted when the runtime's last bridge exits: kiro-cli's MCP subprocesses
 * shut down with it, so no configured server is currently live.
 * Clients use this to clear their runtime-state map.
 */
export interface MCPDisconnectedPayload {
  server: string;
}

/**
 * MCPFailedPayload is the payload for type="mcp_failed", emitted
 * when kiro-cli reports _kiro.dev/mcp/server_init_failure.
 */
export interface MCPFailedPayload {
  server: string;
  error: string;
}

/**
 * MCPOAuthPayload is the payload for type="mcp_oauth_needed", emitted
 * when kiro-cli reports _kiro.dev/mcp/oauth_request. URL is the
 * provider's authorisation endpoint; the user completes the flow in a
 * new tab.
 */
export interface MCPOAuthPayload {
  server: string;
  url: string;
}

/** MCPToolIdentity names the verified MCP server and tool behind a permission request. */
export interface MCPToolIdentity {
  server_name: string;
  tool_name: string;
}

/**
 * Message is one entry in a chat transcript. Tool calls are embedded in assistant
 * messages, not standalone; an event message carries an EventKind.
 */
export interface Message {
  /**
 * ChangedFiles is part of the per-turn footer summary, set on the final assistant
 * message at turn_ended so the footer survives reload. Field order in this struct
 * is govet-fieldalignment-optimal, not logical.
 */
  changed_files?: Record<string, FileChange>;
  role: Role;
  content?: string;
  /**
 * Reasoning is the agent's thinking trace, a parallel stream alongside Content.
 * On the same message so the one-message-per-turn invariant holds.
 */
  reasoning?: string;
  event_kind?: EventKind;
  /**
 * UserKind is which kind of user row this is, absent on every kind but a steer.
 * See UserKind for what absent means and why a steer carries no TurnOutcome.
 */
  user_kind?: UserKind;
  /**
 * SteerState is whether the model READ this steer, present only on a steer row.
 * Absent means not known — see SteerState, which owns what that means and how it
 * renders. It is what makes a reload able to say "the agent never saw this".
 */
  steer_state?: SteerState;
  /**
 * SteerOrigin is whose words a steer row carries, present only on a steer row.
 * On the ROW as well as on the live frames because the note's TITLE comes from
 * it, and the durable row REPLACES the live mark once it is resident (store.ts
 * resolveAnchors). Without it a workflow's report would read as something the
 * reader typed after every reload — the defect SteerOrigin exists to prevent.
 * Absent means the user's, matching what the renderer has always assumed.
 */
  steer_origin?: SteerOrigin;
  id: string;
  /**
 * TurnOutcome is how this turn ENDED, stamped on the message that finalized
 * it: the durable half of a fact otherwise carried only by the live
 * turn_ended SSE. Its presence also CLOSES a turn for both projections, so an
 * older message never closes one.
 */
  turn_outcome?: TurnOutcome;
  /**
 * TurnStopReasonRaw is the wire's stop reason verbatim, kept because the enum is
 * OPEN: an unmeasured value stays recoverable rather than flattened to `unknown`.
 * No consumer may branch on it; TurnOutcome is what they read.
 */
  turn_stop_reason_raw?: StopReason;
  /**
 * TurnFailureReason is WHY the turn ended badly, stamped by the same code that
 * stamps TurnOutcome so exactly one persisted message per turn carries both.
 * //
 * Sanitized and byte-capped at the write, because its usual source is the
 * agent's own text. Absent on older records, so the client keeps a per-outcome
 * default.
 */
  turn_failure_reason?: string;
  /**
 * TurnModel is the model that answered this turn. It belongs on the MESSAGE and
 * not only on the Chat, whose Model is the CURRENT one: rendering that would
 * relabel every historical turn the moment the user switched models.
 */
  turn_model?: string;
  tool_calls?: ToolCall[];
  /**
 * Blocks is the canonical render model, in emission order. The client normalizes
 * legacy Content/ToolCalls into Blocks on replay so there is a single render path.
 */
  blocks?: Block[];
  /**
 * CodeReferences carries licensed-code attributions the agent flagged during
 * this turn. Turn-scoped: the wire carries no span.
 */
  code_references?: CodeReference[];
  /**
 * Refusal marks this assistant turn as a model refusal (kiro-cli 2.13 contract):
 * the message content IS the refusal explanation, and this carries the category
 * and recommended model the client's refusal callout renders.
 */
  refusal?: RefusalInfo;
  plan?: PlanEntry[];
  /**
 * Attachments are the files attached to THIS prompt, on the user message so a sent
 * turn renders them as header pills. It must live on the record: each one is folded
 * into a content block on the way OUT, so a turn read back has nothing to recover
 * the list from. Absent on older records, and on a steer, which takes a plain string.
 */
  attachments?: Attachment[];
  /**
 * TurnCredits / TurnElapsedMs complete the turn footer alongside ChangedFiles.
 * omitempty drops the zero cases: a read-only turn has none.
 */
  turn_credits?: number;
  turn_elapsed_ms?: number;
  ts: number;
  /**
 * TurnTruncated marks a turn the model stopped at a bound: it completed and
 * its answer is cut off. Stored though derivable from the raw stop reason, so
 * the Go and TypeScript projections do not each re-implement the mapping.
 */
  turn_truncated?: boolean;
}

/**
 * MessageChunkPayload is the payload for type="message_chunk" (assistant streaming deltas).
 * BlockIndex addresses the content block this delta belongs to and may go BACKWARDS
 * mid-turn: a tool_call bumps its own subtask's next text chunk to a new index while an
 * interleaved OTHER subtask does not. Accumulate BY INDEX, never into the newest block.
 */
export interface MessageChunkPayload {
  /**
 * Refusal tags this delta as the model-refusal explanation, set on at most one chunk
 * per turn so the live renderer can style the callout without waiting for turn_ended.
 */
  refusal?: RefusalInfo;
  message_id: string;
  delta: string;
  agent_subtask_id?: string;
  block_index: number;
  /**
 * Seq is the delta's 1-based sequence number within the turn. A client that ingested a
 * connect-time turn_state snapshot drops chunks at or below its chunk_seq watermark —
 * they are already folded in — instead of double-appending them.
 */
  seq?: number;
  is_reasoning?: boolean;
}

/**
 * MeteringItem is one usage dimension from kiro-cli's meteringUsage array.
 * UnitPlural is the canonical identifier ("credits", "tokens", "requests").
 */
export interface MeteringItem {
  unit_singular: string;
  unit_plural: string;
  value: number;
}

/**
 * OpenExternalURLPayload is the payload for type="open_external_url". Browsers popup-block a
 * window.open() not driven by a user gesture, so the client surfaces a banner link rather
 * than auto-opening. Only http/https URLs are broadcast.
 */
export interface OpenExternalURLPayload {
  url: string;
}

/**
 * PR represents a pull/merge request. CheckStatus and MergeBlocked carry
 * no omitempty: their empty value is meaningful (the forge reported no CI
 * state / nothing blocks this merge), so the client must receive it
 * rather than infer it from an absent field.
 */
export interface PR {
  title: string;
  body?: string;
  state: string;
  author?: string;
  source_branch: string;
  target_branch: string;
  url?: string;
  /**
 * HeadSHA is the head commit of the source branch: the value a merge
 * pins itself to, so a push landing between the read and the click
 * fails the merge instead of landing unreviewed code.
 */
  head_sha?: string;
  /**
 * CheckStatus is the folded CI state of HeadSHA. One of "" (the forge
 * reported no checks), "pending", "passing", "failing".
 */
  check_status: string;
  /**
 * MergeBlocked names why the forge refuses a merge, or "" when
 * nothing does. One of "draft", "conflicts", "checks_failing",
 * "checks_running", "behind", "blocked", "unknown".
 */
  merge_blocked: string;
  number: number;
  checks_total?: number;
  checks_failing?: number;
  created_at?: number;
  updated_at?: number;
  mergeable?: boolean;
  draft?: boolean;
  /**
 * AutoMergeArmed reports that the forge will merge this PR itself
 * once its requirements are met, so the row offers a read-out
 * rather than arming it twice.
 */
  auto_merge_armed?: boolean;
}

/** PermissionNeededPayload is the payload for type="permission_needed". */
export interface PermissionNeededPayload {
  mcp_tool?: MCPToolIdentity;
  tool_call_id?: string;
  title?: string;
  /**
 * Kind forwards the ACP toolCall.kind so the client can style distinctive prompts
 * (switch_mode gets a different dialog from an execute_bash prompt).
 */
  kind?: ToolKind;
  sub_session_id?: string;
  /**
 * RunID + NodeID attribute a WORKFLOW STEP's ask to its run, stamped from the
 * step-session registry whichever bridge the ask arrived on, so a run tab can render
 * the ask of a run it is watching even though the ask is keyed to the launching chat.
 */
  run_id?: string;
  node_id?: string;
  /**
 * AlwaysAllowBlocked names why the card must not offer to persist a rule for this
 * command. Empty means the offer stands.
 */
  always_allow_blocked?: AlwaysAllowBlock;
  options: PermissionOption[];
  /**
 * Files is the turn's staged file list, present ONLY on a turn approval. Such an
 * approval arrives as an ordinary session/request_permission, so it rides this payload
 * rather than a second event; it expects per-file decisions back.
 */
  files?: ApprovalFile[];
  request_id: number;
}

/** PermissionOption is one selectable response in a permission dialog. */
export interface PermissionOption {
  option_id: string;
  name: string;
  kind: string;
}

/**
 * PermissionsChangedPayload is the SSE payload for type="permissions_changed"
 * (translated from _kiro/policy/changed). Clients refetch GET /api/permissions
 * on receipt. Status is "success" or "failed"; Errors carries any non-fatal
 * warnings or the fatal parse error.
 */
export interface PermissionsChangedPayload {
  status?: string;
  errors?: PolicyErrorItem[];
}

/** PlanEntry is one item in an agent-authored plan. */
export interface PlanEntry {
  content: string;
  priority: string;
  status: PlanStatus;
}

/**
 * PolicyErrorItem is one entry in a policy/changed or policy/error
 * notification's errors array (from KAS).
 */
export interface PolicyErrorItem {
  scope?: string;
  source?: string;
  message: string;
  fatal?: boolean;
}

/**
 * PolicyErrorPayload is the SSE payload for type="policy_error" (translated
 * from _kiro/policy/error). Surfaced as a banner so a bad hand-edit or a
 * rejected rule is visible without hunting the logs.
 */
export interface PolicyErrorPayload {
  errors?: PolicyErrorItem[];
}

/** PolicyExplainResult mirrors _kiro/permissions/explain (a pure simulation). */
export interface PolicyExplainResult {
  capability: string;
  resource?: string;
  effect: string;
  matched_rule?: PolicyRuleCore;
  scope?: string;
  source?: string;
  is_explicit_ask: boolean;
}

/**
 * PolicyRule is one native policy rule as reported by _kiro/permissions/list.
 * Capability + effect are always present; match/exclude are optional glob
 * lists; scope + source carry provenance (source is a file path for
 * user/workspace rules, or a synthetic tag like "kiro-scope"/"agent-profile").
 */
export interface PolicyRule {
  capability: string;
  effect: string;
  scope: string;
  source: string;
  match?: string[];
  exclude?: string[];
}

/**
 * PolicyRuleCore is the rule shape without provenance, used inside an
 * explain result's matched_rule.
 */
export interface PolicyRuleCore {
  capability: string;
  effect: string;
  match?: string[];
  exclude?: string[];
}

/**
 * PolicyView is the GET /api/permissions response: the native policy rule
 * set plus the metadata the editor needs. Available is false when no bridge
 * could answer (the view falls back to reading the editable files directly).
 * Capabilities and RelaxCapabilities answer different questions and neither is a
 * filter on the other. Capabilities is what the rule-adder's dropdown OFFERS —
 * the suggested set unioned with every capability the live rules already use, so
 * it can learn a name vibekit shipped without. RelaxCapabilities is the fixed
 * membership of the LOOSEST security profile's file rules, derived in policyfile
 * and deliberately not discovered: it decides what picking that rung grants, so it
 * may not grow from whatever happens to be in the returned rules. (It named the
 * Settings -> Permissions relaxation switch until the profile picker replaced it.)
 */
export interface PolicyView {
  /**
 * Profile is the posture in force; Profiles below is the ladder it comes from.
 * Split apart here only because the two have different alignments — read them
 * together.
 */
  profile: string;
  rules: PolicyRule[];
  writable_scopes: string[];
  capabilities: string[];
  relax_capabilities: string[];
  /**
 * Profiles is the security-posture ladder in picker order, loosest last, and
 * Profile above is the one in force. Both travel here rather than being derived
 * client-side for the same reason RelaxCapabilities does: the ladder decides
 * what one click grants, so policyfile owns it and the client renders it.
 * //
 * Order is part of the payload. A client that sorted these would put the
 * loosest option somewhere in the middle of a list a reader scans from
 * cautious to permissive.
 */
  profiles: SecurityProfile[];
  available: boolean;
}

/**
 * PollResult is the per-poll status of the GitHub device flow. Deliberately
 * tokenless: the access token never leaves the server. pollDeviceToken carries
 * it as far as `gh auth login --with-token` and no further.
 */
export interface PollResult {
  status: string;
  error?: string;
}

/**
 * Recipe is one launchable workflow definition, projected from
 * `_kiro/workflow/listRecipes` for GET /api/recipes.
 */
export interface Recipe {
  /** Inputs maps input name → declared type (`string`, `prompt`, `file`). */
  inputs?: Record<string, string>;
  name: string;
  description?: string;
  /**
 * Source is the launch key: `bundled://<name>` or a workspace
 * `*.workflow.json` path. Echoed back verbatim in RunLaunchRequest.
 */
  source: string;
  /**
 * Plan is KAS's node plan, forwarded VERBATIM: what the recipe will do and on
 * which model, raw for the reason at the top of this file. Last of the
 * pointer-bearing fields on purpose — a slice's len/cap words end the GC scan
 * region where a trailing string would extend it.
 */
  plan?: unknown;
  built_in?: boolean;
}

/** RecipesResponse is GET /api/recipes's reply. */
export interface RecipesResponse {
  recipes: Recipe[];
}

/**
 * RefusalInfo is the refusal metadata KAS attaches when the model declines to
 * continue a conversation, and the turn then ends with stopReason "refusal". The
 * explanation streams as ordinary assistant content, so only the classification is
 * kept here; persisted so the callout survives reload.
 */
export interface RefusalInfo {
  category?: string;
  recommended_model?: string;
}

/** Release represents a tagged release. */
export interface Release {
  tag_name: string;
  name?: string;
  body?: string;
  url?: string;
  published_at?: number;
  draft?: boolean;
  prerelease?: boolean;
}

/**
 * RemoveResponse rides a 409-free DELETE alongside the job (dependents
 * is populated on forced cascades so the client can report what else
 * was removed).
 */
export interface RemoveResponse {
  job?: Job;
  dependents?: string[];
}

/** Repo is a remote repository accessible via the authenticated forge. */
export interface Repo {
  owner: string;
  name: string;
  full_name: string;
  default_branch?: string;
  url?: string;
  clone_url?: string;
  description?: string;
  private?: boolean;
  archived?: boolean;
  fork?: boolean;
  updated_at?: number;
}

/**
 * ResumableSession is one stored KAS session offered by the previous-session
 * picker (GET /api/sessions). KAS owns the inventory and the transcript, so
 * vibekit keeps no archive of its own. Field order is fieldalignment's.
 */
export interface ResumableSession {
  session_id: string;
  title: string;
  agent_mode?: string;
  /** Status is KAS's own session status: idle | failed | waiting_on_user. */
  status?: string;
  /**
 * Description is the agent's self-declared focus for that session, present
 * on a minority of rows (88 of 399 measured).
 */
  description?: string;
  /**
 * ChatID names the vibekit chat that already owns this session, empty when none
 * does. A claimed session is one the user can simply open.
 */
  chat_id?: string;
  updated_at: number;
  created_at?: number;
}

/**
 * RunAnswerRequest is POST /api/runs/{id}/answer's body: answer one parked step.
 * //
 * Empty Text is a 400 rather than a waive. Continuing without an answer is a
 * DIFFERENT verb (POST /api/runs/{id}/step with status `running`) — it drives the
 * step with KAS's default continuation, and an empty box must not reach it.
 */
export interface RunAnswerRequest {
  ask_id: string;
  text: string;
}

/**
 * RunControlsResponse is GET /api/runs/{id}/controls's reply: what may be done to
 * one run, and why not for the rest.
 * //
 * Its own route rather than a field on GET /api/runs/{id}, a verbatim KAS
 * passthrough. The client used to decide this from a status table plus an SSE-fed
 * cache of which chat launched the run, so any reloaded client read a
 * chat-parented run as parentless. Only the server sees all three inputs.
 */
export interface RunControlsResponse {
  /**
 * Refused maps a verb this run does not offer to the one sentence a reader
 * needs, and carries only a verb whose absence would otherwise be unexplained.
 */
  refused?: Record<string, string>;
  /**
 * ParentChatID names the chat whose agent launched the run, empty for a
 * parentless one. Read from the chat store here rather than from an event-fed
 * client cache, which is empty after a reload.
 */
  parent_chat_id: string;
  /**
 * Verbs are the offered controls, in row order. Strings rather than a
 * registered enum because the client's label table is the narrowing point: an
 * unlabelled verb is dropped, so a future one degrades to a missing button.
 */
  verbs: string[];
}

/**
 * RunFinishedPayload is the payload for type="run_finished": terminal. Status is
 * KAS's own run-level status, `paused` included — a policy pause at
 * `onMaxIterations` reports through here, because KAS emits `run_complete` for it.
 * //
 * There is deliberately no aborted_by_restart flag: a restart PAUSES a run and
 * KAS's read-path reconcile has no path to aborted, so nothing would fill it.
 * Name is here for RunStartedPayload's reason, and empty when KAS sends no state.
 */
export interface RunFinishedPayload {
  workflow_id: string;
  status: string;
  name?: string;
}

/**
 * RunInputNeededPayload is the payload for type="run_input_needed": a workflow STEP
 * asked a question and the run is parked until somebody answers it. It carries its
 * payload rather than invalidating because the text is on no endpoint — KAS parks
 * with one fixed literal in `state.pauseReason` — and WorkflowID is the IDENTITY,
 * since the envelope's chat id is empty for a parentless run. Question MAY BE
 * EMPTY: the ask registry is in memory, so a restart loses the text while the run
 * stays parked. No Severity field — only `warning` parks a run.
 */
export interface RunInputNeededPayload {
  workflow_id: string;
  /**
 * AskID is composed with keyenc so a separator inside one part cannot forge it.
 * The after-restart spelling must be DETERMINISTIC, or the read path that mints it
 * on every refetch stacks duplicate cards.
 */
  ask_id: string;
  /**
 * NodeID addresses the asking step. MAY BE EMPTY — KAS sets it only for a step
 * caller, and a run blocked by an unattributable ask is still blocked. No
 * NodePath: the step-session registry holds no path, so a live ask could not.
 */
  node_id: string;
  /**
 * StepSessionID is the ANSWER ADDRESS: KAS reroutes a `session/prompt` sent to the
 * paused step's session into the run. Empty when the notify frame carried no
 * caller session, and the answer path resolves it from a fresh `inspect`.
 */
  step_session_id: string;
  agent_name: string;
  question: string;
  asked_at: string;
}

/**
 * RunInputSettledPayload is the payload for type="run_input_settled": the ask is
 * answered or waived, so every surface still showing it must retire the card.
 * //
 * Its own event rather than a member of decision_settled, which is keyed by an
 * int64 JSON-RPC request id: a run ask has no open request, so sharing that payload
 * would give one shape two mutually exclusive identity keys.
 */
export interface RunInputSettledPayload {
  workflow_id: string;
  ask_id: string;
  settled_by: SettledBy;
}

/**
 * RunLaunchRequest is POST /api/runs's body: launch one recipe, PARENTLESS.
 * //
 * Source is `_kiro/workflow/listRecipes`' own value verbatim. The server
 * re-validates it against a fresh listRecipes call rather than trusting it, so the
 * endpoint cannot be steered at an arbitrary file even though the value looks like
 * a path.
 */
export interface RunLaunchRequest {
  inputs?: Record<string, string>;
  source: string;
}

/**
 * RunLaunchedResponse is POST /api/runs's reply. Name is the recipe's, so the
 * client can label the tab it opens without waiting for the first refetch.
 */
export interface RunLaunchedResponse {
  workflow_id: string;
  name: string;
}

/**
 * RunOpenAsk is one unanswered ask of a run, as GET /api/runs/{id} reports it under
 * `open_asks`. It exists so an agent handed a deferral can READ the question it is
 * being asked to answer: the ask id is on no other endpoint, and it is far too long
 * to embed in the chat message that hands the work over.
 * //
 * Question carries no omitempty deliberately: a reconciled ask legitimately has "",
 * because the registry is in memory and a restart loses the text while the run stays
 * parked — and an ABSENT field would read as "complete" where an empty one reads as
 * "the text is gone". No node PATH is exposed because none exists to expose:
 * RunInputNeededPayload carries none and the ask registry holds none, so node_id is
 * the whole of a step's address here.
 */
export interface RunOpenAsk {
  ask_id: string;
  question: string;
  node_id?: string;
  agent_name?: string;
  asked_at?: string;
}

/**
 * RunProgressPayload is the payload for type="run_progress": an INVALIDATION
 * signal, deliberately too thin to reconstruct a run from. `run_start` re-fires on
 * every resume and `node_complete` carries neither iteration nor branchId, so an
 * accumulating client could not tell two repeat iterations apart. NodeID is absent
 * on the run-level `paused` and holds the loop id on `loop_iteration`.
 */
export interface RunProgressPayload {
  workflow_id: string;
  node_id?: string;
  /**
 * NodePath addresses ONE execution of a node, joined with "/" — the same
 * spelling RunStepPayload.NodePath uses. Empty on the run-level and
 * shape-changing kinds, which is what tells the client to refetch instead.
 */
  node_path?: string;
  /**
 * Status is the node's status after this frame, in KAS's own NodeState
 * vocabulary so it drops straight onto the cached tree.
 */
  status?: string;
  /**
 * StartedAt and EndedAt are RFC 3339, stamped by the SERVER at frame arrival:
 * KAS puts no timestamp on either lifecycle frame. A later refetch overwrites
 * both with KAS's own values.
 */
  started_at?: string;
  ended_at?: string;
  /**
 * FailureReason is KAS's own explanation for a node that failed. Empty on
 * every other outcome.
 */
  failure_reason?: string;
  kind: RunProgressKind;
}

/**
 * RunRetriedResponse is POST /api/runs/{id}/retry's reply: KAS's own outcome
 * report, forwarded rather than collapsed to `{"ok":true}`. RetriedNodeIDs is why
 * the route exists — a retry that resets five nodes and one that resets none are
 * otherwise the same HTTP result, and the second is what "nothing happened" is.
 */
export interface RunRetriedResponse {
  /** Status is the run's status after the reset, as KAS reports it. */
  status: string;
  retried_node_ids: string[];
}

/**
 * RunStartedPayload is the payload for type="run_started": a run began on this
 * chat. Name is carried because a client that has never fetched this run has
 * nothing to label the row with.
 * //
 * Scheduled marks a run the SCHEDULER launched, and it travels because only the
 * launch path knows: a manual launch is parentless too, so events cannot separate
 * the two. It drives the client's start signal — a manual launch already has the
 * user's attention, a scheduled one began with nobody looking.
 */
export interface RunStartedPayload {
  workflow_id: string;
  name?: string;
  scheduled?: boolean;
}

/**
 * RunStepPayload is the payload for type="run_step".
 * //
 * NodePath, not NodeID, because a repeat's iterations share a node id and two
 * passes of a loop body would write into each other's rows. NOT byte-identical to
 * `inspect`'s state tree: KAS spells an iteration container `iter-<n>` here and
 * `<repeatId>#<n>` there, so the client translates. ToolCall is whole because a
 * parentless run has no chat and so no buffer to fold into.
 */
export interface RunStepPayload {
  tool_call?: ToolCall;
  workflow_id: string;
  node_path: string;
  kind: string;
  delta?: string;
}

/**
 * RunStepTranscript is GET /api/runs/{id}/steps/{path...}'s reply, projected from
 * KAS's replay per request and PERSISTED BY NOTHING. It exists because a step's
 * transcript is on no other endpoint: `inspect` carries what a step DECLARED.
 * //
 * NO `omitempty` on ANY field, deliberately: the generator emits a REQUIRED
 * TypeScript field without it, which stops a client inventing a fallback for the
 * verdict. An optional `state` would read as "assume ready".
 */
export interface RunStepTranscript {
  /**
 * WorkflowID and NodePath echo the request, so a client holding several reads in
 * flight tells the answers apart without correlating.
 */
  workflow_id: string;
  node_path: string;
  state: RunStepTranscriptState;
  /**
 * Messages is the step's transcript, filtered to the ASSISTANT rows. Empty on any
 * state but ready, and legitimately empty on ready.
 */
  messages: Message[];
}

/**
 * SafetyPropertiesPayload is the payload for type="safety_properties". Reason is the KAS
 * PropertyChangeReason (formalized/toggled/expired). Same gating and authoring caveats as
 * SafetyStatusPayload.
 */
export interface SafetyPropertiesPayload {
  reason?: string;
  properties: SafetyProperty[];
}

/**
 * SafetyProperty is one formalized Infrastructure-Safety property. Authored OUT-OF-BAND by
 * KAS via a remote MCP tool; there is no client RPC to create, set or toggle one, so vibekit
 * only ever displays them.
 */
export interface SafetyProperty {
  description: string;
  index?: number;
  enabled?: boolean;
}

/**
 * SafetyStatusPayload is the payload for type="safety_status", translated from the v3 (KAS)
 * _kiro/safety/statusChanged notification and rendered as a transient banner. KAS installs
 * the gate only under an AWS governance flag, off by default on Builder-ID accounts, so this
 * normally never fires. Distinct from supervised mode, which is KAS's autopilot gate.
 */
export interface SafetyStatusPayload {
  status: SafetyStatus;
  detail?: string;
  tool_id?: string;
  blocked_properties?: string[];
}

/**
 * SearchHit is one catalog search result. A projection of
 * toolbelt.CatalogEntry without the embedded install definition (an
 * implementation detail no client needs).
 */
export interface SearchHit {
  name: string;
  description?: string;
  source: string;
  /**
 * Version is the catalog's default pinned version, set only for
 * entries without an upstream version source (manual installs).
 */
  version?: string;
  /**
 * Reason names the registry backend that defeated the compiler, and
 * is set only alongside Unavailable.
 */
  reason?: string;
  /**
 * Match names which field the query hit — see [toolbelt.MatchKind].
 * Empty for the featured set and for an unavailable hit. On the wire
 * because a client cannot derive it: aliases are not projected here,
 * so a hit on `rg` would look like a description match otherwise.
 */
  match?: string;
  featured?: boolean;
  lsp?: boolean;
  /**
 * Unavailable marks a hit the catalog knows about and cannot
 * install, with Reason naming the registry backend that defeated the
 * compiler. Such a hit is informational: a client must not offer an
 * install for it, and the engine refuses one anyway.
 * //
 * Both fields are omitempty, so an installable hit serialises exactly
 * as it did before this pair existed.
 */
  unavailable?: boolean;
  /**
 * Apt marks a Debian package rather than a catalog entry. Version
 * then carries the distro's candidate, which routinely differs from
 * the catalog's version for the same tool, and the row's install lands
 * in the container layer rather than on the persistent volume.
 */
  apt?: boolean;
}

/**
 * SearchResponse is the search route's body: installable hits merged
 * into one relevance order via [toolbelt.Match] (catalog and Debian, not
 * concatenated — a bare concatenation put every catalog hit ahead of
 * every Debian one regardless of score), then the opt-in unavailable
 * block, kept separate and unranked since ranking a dead end above a
 * live option would be wrong.
 * //
 * AptAvailable distinguishes "no Debian package matched" from "the
 * package list could not be consulted" — identical in an empty result,
 * opposite in meaning.
 */
export interface SearchResponse {
  results: SearchHit[];
  apt_available: boolean;
}

/**
 * SecurityProfile is one entry in the picker: the persisted id and the KAS policy
 * preset ids it sends. The presets travel so the UI can say what a profile grants
 * without a second round trip, and so a reader can tell two profiles apart by
 * something more than their names.
 */
export interface SecurityProfile {
  id: string;
  presets: string[];
}

/**
 * SessionEffortLevel is one reasoning-effort tier the running session offers,
 * from the `effortLevel` config option's own `options[]`.
 * //
 * The tiers are NOT a fixed five and NOT a per-model list: kiro-cli 2.18.0 builds
 * its picker from this option and errors when the list is empty, so the list IS
 * the capability. A tier absent here is a level the service rejects.
 */
export interface SessionEffortLevel {
  id: string;
  name?: string;
}

/**
 * SessionListResponse is the GET /api/sessions reply.
 * //
 * The two lists degrade INDEPENDENTLY — separate verbs on the same bridge, so
 * one can fail alone — which is why each carries its own verdict rather than the
 * response carrying one. Neither verdict carries omitempty: a reader must not be
 * able to read an absent field as success.
 */
export interface SessionListResponse {
  sessions_state: ReadState;
  runs_state: ReadState;
  sessions: ResumableSession[];
  runs: WorkflowRun[];
}

/**
 * SessionMode describes one mode the running agent supports, from
 * `modes.availableModes` on session/new or session/load; kept on the chat so the
 * mode pill renders without re-querying the bridge.
 * //
 * The v3 list is unified — bundled workflow modes AND every workspace custom
 * agent, all switchable via session/set_mode — so Source ("bundled" vs
 * "workspace") is what lets the picker group them.
 */
export interface SessionMode {
  id: string;
  name: string;
  description?: string;
  source?: string;
}

/**
 * SessionModel describes one model the running agent can swap to, as declared by
 * kiro-cli's session/new response.
 */
export interface SessionModel {
  id: string;
  name: string;
  description?: string;
  /**
 * DefaultEffortLevel is the level this MODEL defaults to, from
 * `_meta.kiro.defaultEffortLevel`; used for a chat with no session yet.
 * //
 * NOT persisted onto Chat.Effort: seeding a chat's CHOICE from a service
 * default would pin it to every later session through StartOpts.Effort.
 */
  default_effort_level?: string;
  rate_multiplier?: number;
  /**
 * HasEffort reports whether this model offers reasoning-effort tiers, from
 * `_meta.kiro.hasEffort`. `auto` carries false, so a chat on it hides the
 * effort row: KAS builds no effortLevel option for a tierless model and
 * silently drops a level sent to one. Chat.EffortLevels answers the same
 * question from the other side.
 */
  has_effort?: boolean;
}

/**
 * SteerClearedPayload is the payload for type="steer_cleared": the steers named here were
 * dropped from the buffer without reaching the model. KAS clears at every turn boundary and on
 * an explicit steer_clear, so an id appearing after its steer_injected is housekeeping, while
 * one appearing WITHOUT an injected is a message nothing ever read — which is why injected is
 * its own event.
 */
export interface SteerClearedPayload {
  steer_ids: string[];
}

/**
 * SteerInjectedPayload is the payload for type="steer_injected": the model has now READ the
 * steer. Broadcast TWICE for a steer the agent answers, carrying different halves — KAS's
 * steering channel sends Text with no Ack, then the assistant TEXT stream sends Ack with no
 * Text when the `[STEERING steer-<id>: …]` marker closes. Reading a steer and acting on it are
 * separate moments, so the client merges both onto the chip by SteerID.
 */
export interface SteerInjectedPayload {
  steer_id: string;
  text: string;
  /**
 * Ack is the agent's own statement of what it did, lifted out of the acknowledgement
 * marker vibekit hides from the transcript: "read" becomes "read: rebased onto main
 * instead". Empty on the read frame, and empty when the agent emitted no marker.
 */
  ack?: string;
  /**
 * Origin is whose words these are, as on SteerQueuedPayload. On BOTH because an
 * agent-injected steer has no queued frame, so for the case Origin names this frame is
 * the only one.
 */
  origin: SteerOrigin;
}

/**
 * SteerQueuedPayload is the payload for type="steer_queued": a mid-turn steer reached KAS's
 * per-session buffer and is waiting for the next node boundary. Text travels even though the
 * sender has it, because the chip row is a projection of server state and must be
 * reconstructible from the events alone — for every other device and for the sender after a
 * reconnect.
 */
export interface SteerQueuedPayload {
  steer_id: string;
  text: string;
  /**
 * Origin is whose words these are, resolved server-side. NO omitempty: an absent field
 * lets the client invent a fallback, and the one it would pick is wrong for a
 * workflow's report.
 */
  origin: SteerOrigin;
}

/** SystemTool is one image-baked binary surfaced read-only (Config.System). */
export interface SystemTool {
  name: string;
  installed: boolean;
}

/**
 * TabList is the answer to GET /api/tabs: the open set in order, plus the
 * version it reflects.
 * //
 * The two fields travel together because they are ONE fact, captured in one
 * critical section by tabs.Store.List. A caller that read them separately could
 * pair a stale set with a fresh version and then discard the very event the set
 * was missing — which is the defect that killed an earlier revision's SSE-head
 * watermark, where the snapshot and the event hub sat behind different locks.
 * //
 * Tabs is never omitted, even when empty: an empty arrangement is a real state
 * (someone closed the last tab) and a missing field would read as "no answer".
 */
export interface TabList {
  tabs: TabSubject[];
  version: number;
}

/**
 * TabSubject is the SHARED fact about one open tab: what it shows, where it
 * sits, and whether closing it tears the thing down. It is what gets persisted
 * and the only tab shape that crosses the wire.
 * //
 * What is NOT here is the point of the split. The client's TabViewSpec — the
 * view selector, the typed route, onShow, onClose, the local activity dot — is
 * produced from a subject by a total per-kind factory, so nothing about
 * activation or teardown moves server-side, and a subject carries no behaviour.
 * The editor's loaded content, dirty state and line selection stay in
 * fileStates; a singleton's lazy import stays in its factory. A factory needs
 * nothing from a subject beyond (Kind, Ref).
 * //
 * There is NO Order field: the position in tabs.Store's slice IS the order, so
 * there is one representation of it rather than a slice and an integer that can
 * disagree.
 * //
 * Field order is govet fieldalignment's (the pointer-bearing strings lead, the
 * bools trail), not reading order.
 */
export interface TabSubject {
  /**
 * ID is opaque and server-minted (tabs.Store mints it at open). Opaque
 * because nothing should be able to branch on it: Kind and Ref name the
 * subject, so an id encoding its kind in a prefix would be a second
 * representation parsed in three places. It also keeps the API path
 * unambiguous under a reverse proxy that normalizes %2F.
 */
  id: string;
  /**
 * Kind and Ref are the subject's identity: at most one tab exists per
 * (Kind, Ref) pair, which is what makes an open idempotent.
 */
  kind: TabKind;
  /**
 * Ref is a chat id, an absolute path, a run id, or a subagent's
 * `<chatID>/<agentSubtaskID>` pair — empty for a singleton.
 * The store treats it as opaque text: whether it is a VALID chat id or a
 * path inside a granted root is the command boundary's question, because
 * that is where ids.ValidChatID and the file-browser roots live.
 */
  ref: string;
  /**
 * Parent is the tab this one hangs under, empty for a top-level tab.
 * //
 * Set at open and NEVER reassigned, which is what makes a cycle
 * unrepresentable: a child's parent already existed when the child was
 * minted, so no chain can close on itself and no reparent check is needed
 * anywhere.
 */
  parent: string;
  /**
 * Pinned sorts a tab ahead of every unpinned one. The partition is applied
 * by the client when it renders (applyPinOrder); the stored slice keeps the
 * order it was given.
 */
  pinned: boolean;
  /**
 * Owns means closing this tab tears down what it shows, and it exists
 * because two tabs can otherwise be indistinguishable while differing in
 * authority: a run REVIEW opened from History and a launcher-OWNED run share
 * (Kind, Ref), and closing the owned one cancels the run. Set at open, like
 * Parent, so the authority cannot change under a reader.
 */
  owns: boolean;
}

/**
 * TabsChangedPayload is the payload for type="tabs_changed": ONE committed mutation of the
 * open-tab set, workspace-global, so the chat id is empty. REMOVAL IS STATED, never inferred:
 * absence from Order never means closure, and a client holding a tab the order does not name
 * keeps its position and sorts last.
 */
export interface TabsChangedPayload {
  /**
 * Changed is the one tab this mutation added or altered, absent on a close and a
 * reorder. A pointer because "no tab changed" and "a zero-valued tab changed" are
 * different facts the client branches on.
 */
  changed?: TabSubject;
  /**
 * OpID is the client-minted correlation id echoed back so a caller can match the frame
 * to its own dispatch; empty for a mutation no client asked for. Distinct from
 * Idempotency-Key: this has no TTL, no cache and no 409 branch.
 */
  op_id?: string;
  /**
 * RemovedIDs names every tab this mutation closed, per id. Closing a parent with
 * children is one mutation, so this is where the children arrive.
 */
  removed_ids?: string[];
  /**
 * Order is the EXPANDED list, children included, so a client never derives a position
 * from a delta.
 */
  order?: string[];
  /**
 * Version is the client's only watermark, with three exhaustive rules: at or below local
 * is ignored, exactly one past applies, more than one past means re-list. ONLY AN EVENT
 * MAY ADVANCE IT — adopting a response's v+2 would make another device's in-flight v+1
 * read as stale, so no gap could ever be detected.
 */
  version: number;
}

/** TerminalCreatedPayload is the payload for type="terminal_created". */
export interface TerminalCreatedPayload {
  terminal_id: string;
  command: string;
  args: string[];
}

/**
 * TerminalExitedPayload is the payload for type="terminal_exited". A signal-killed process
 * carries Signal with ExitCode omitted; a normal exit carries ExitCode (>=0) with Signal
 * empty. Mirrors KAS's zTerminalExitStatus, so a signal death never reports exit_code:-1.
 */
export interface TerminalExitedPayload {
  exit_code?: number;
  terminal_id: string;
  signal?: string;
}

/**
 * TerminalOutputPayload is the payload for type="terminal_output". Data is PLAIN text with
 * escape sequences parsed off server-side, so the browser never builds HTML out of
 * agent-controlled bytes; Spans style ranges of it. Offset is where this chunk begins in the
 * terminal's accumulated output, in the UTF-16 code units the spans use — and the spans carry
 * ABSOLUTE offsets, so a client painting one chunk must subtract this base.
 */
export interface TerminalOutputPayload {
  terminal_id: string;
  data: string;
  spans?: TextSpan[];
  offset: number;
}

/**
 * TextSpan styles the half-open range [Start,End) of a sibling text field. It
 * mirrors internal/ansitext.Span, and the wire type lives here because that package
 * stays a stdlib-only leaf that knows nothing about the wire.
 * //
 * Attrs matches web-terminal-engine's vt.WireRun.A so both renderers share one
 * attribute vocabulary. The COLOUR encoding deliberately differs: a palette INDEX
 * survives into a persisted chat file without baking today's theme into it.
 */
export interface TextSpan {
  /**
 * Start is the inclusive offset in UTF-16 CODE UNITS, not bytes, because the
 * consumer indexes with JavaScript string offsets: a byte offset would point
 * mid-character the moment output carried a box-drawing glyph or accented name.
 */
  start: number;
  /** End is the exclusive offset into the styled text, in UTF-16 code units. */
  end: number;
  /**
 * FG is the foreground colour: -1 default, 0-255 a palette index, or
 * 0x1000000|RGB for 24-bit.
 */
  fg: number;
  /** BG is the background colour, encoded like FG. */
  bg: number;
  /**
 * Attrs is a bitfield: 1 bold, 2 italic, 4 underline, 8 inverse, 16 strike,
 * 32 dim, 64 hidden, 128 blink, 256 overline, 512 double-underline.
 */
  attrs: number;
}

/**
 * ToolCall is a tool invocation inside an assistant message. Each can be updated
 * in place as status changes (pending → in_progress → completed/failed/aborted).
 */
export interface ToolCall {
  id: string;
  title: string;
  kind: ToolKind;
  status: ToolStatus;
  output?: string;
  /** SubSessionID is the v2 subagent-session attribution (inert on v3). */
  sub_session_id?: string;
  /**
 * AgentSubtaskID is set from a tool call's _meta.kiro.agentSubtaskId. On v3 a
 * subagent surfaces as an ordinary tool_call with _meta.kiro.kind agent-subtask;
 * this id links the card to its nested deltas, which carry the same id.
 */
  agent_subtask_id?: string;
  /**
 * WorkflowID names the run a `run_workflow` invocation started, from the terminal
 * update's `rawOutput.workflowId`. Empty on every other tool call, and on this one
 * until the run is created. It makes the invocation the RUN's card: the client
 * keys a run card on it, and a step's blocks arrive carrying the same id in their
 * `agent_subtask_id`, so the two sides join with no guessing.
 */
  workflow_id?: string;
  /**
 * TerminalID links an execute tool call to the agent terminal running it, from
 * the ACP type:"terminal" content block. It makes the CARD the terminal's
 * rendering surface. Empty on every tool call that spawned no process.
 */
  terminal_id?: string;
  /**
 * Checkpoint is KAS's snapshot mapping for a tool call that wrote a file, from
 * _meta.kiro.checkpoint; nil when it touched no file. Ahead of the slices below
 * for govet fieldalignment: a trailing pointer would extend the GC scan region.
 */
  checkpoint?: ToolCheckpoint;
  /**
 * Disclosed names the skill or steering document a `disclose_context` call
 * loaded, from _meta.kiro.disclosedContext. The only signal that a skill's body
 * reached the model, so the transcript renders it, not a generic tool card.
 */
  disclosed?: ToolDisclosed;
  /**
 * Denial is KAS's structured reason for a call the Cedar policy refused, from
 * _meta.kiro.policyDenial. Present so a refusal reads as a refusal rather than a
 * tool failure, and names the rule, since the user owns the policy.
 */
  denial?: ToolDenial;
  /**
 * Truncated is what the STORE dropped to bound this call on disk, nil on every
 * call that fitted. Grouped with the pointers above for govet fieldalignment.
 */
  truncated?: ToolTruncation;
  input?: unknown;
  locations?: ToolLocation[];
  diffs?: ToolDiff[];
  /**
 * OutputSpans styles ranges of Output. Parsed once server-side by
 * internal/ansitext, so Output stays plain searchable text and the client never
 * builds HTML from agent-controlled bytes.
 */
  output_spans?: TextSpan[];
  ts: number;
  duration_ms?: number;
  /**
 * OutputBytes is the PERSISTED output's length and DiffCount the persisted
 * number of diffs: what the reveal will fetch. Set ONLY alongside HasFull; where
 * the store also cut the call, Truncated carries the size before THAT cut.
 */
  output_bytes?: number;
  diff_count?: number;
  /**
 * HasFull says Input, Output and Diffs here are a PREVIEW, and the whole of what
 * the record kept is at GET /api/chats/{id}/tools/{id}. Set by the transcript
 * read path alone, because only a page load or scroll-up reads a preview.
 */
  has_full?: boolean;
}

/**
 * ToolCallBulk is GET /api/chats/{id}/tools/{toolCallID}: the whole of one tool
 * call's PERSISTED content, for a card whose preview said HasFull. Only the three
 * fields the transcript previews; title, kind and status are on the card already.
 */
export interface ToolCallBulk {
  /**
 * Strings before slices, and no field order here carries meaning: this is
 * betteralign's answer for the smallest GC scan region (govet fieldalignment).
 */
  output?: string;
  id: string;
  diffs?: ToolDiff[];
  output_spans?: TextSpan[];
  input?: unknown;
}

/**
 * ToolCallPayload is the payload for type="tool_call". BlockIndex is the tool_use block's
 * position in the assistant message's Blocks array, so the card lands between the right
 * surrounding text blocks.
 */
export interface ToolCallPayload {
  message_id: string;
  tool_call: ToolCall;
  block_index: number;
}

/**
 * ToolCallUpdatePayload is the payload for type="tool_call_update": a DELTA addressed by
 * id, carrying only what this frame changed. Every field is omitempty and means
 * "unchanged" when absent; OutputDelta's meaning depends on OutputReplace. turn_state
 * remains the whole-object channel — a reconnecting client has no delta base.
 */
export interface ToolCallUpdatePayload {
  /** The three metadata blocks, each sent whole when it changed; none accumulates. */
  checkpoint?: ToolCheckpoint;
  disclosed?: ToolDisclosed;
  denial?: ToolDenial;
  message_id: string;
  tool_call_id: string;
  /** Title and Kind: KAS sends them nullish on most updates, so absent is "keep". */
  title?: string;
  kind?: ToolKind;
  status?: ToolStatus;
  /**
 * OutputDelta is normally the text to APPEND; when OutputReplace is set it is the
 * whole output instead. The replace case is load-bearing: at completion a terminal's
 * full stream wins over the ACP fragments already on the card (adoptTerminalOutput).
 */
  output_delta?: string;
  /** The four late identity attachments: each is adopted once, on at most one frame. */
  terminal_id?: string;
  sub_session_id?: string;
  agent_subtask_id?: string;
  workflow_id?: string;
  /**
 * OutputSpans style the WHOLE output at absolute offsets, so they are sent entire
 * whenever they change. Empty for output carrying no escape sequence.
 */
  output_spans?: TextSpan[];
  /**
 * DiffsAppended are the diffs this frame added; diffs only ever append, so there is
 * no replace case.
 */
  diffs_appended?: ToolDiff[];
  /** Locations are REPLACED wholesale when present. */
  locations?: ToolLocation[];
  /**
 * The two non-pointer scalars last, so the GC scan region stops above them (govet
 * fieldalignment). OutputReplace's meaning is on OutputDelta.
 */
  duration_ms?: number;
  output_replace?: boolean;
}

/**
 * ToolCheckpoint is KAS's pre/post-image mapping for one file write, persisted
 * verbatim so a diff is a snapshot read plus a file read. Original and Modified are
 * opaque `kiro-snapshot-v2://` handles, NOT filesystem paths, deliberately unparsed.
 * //
 * ALL THREE FIELDS ARE INDEPENDENTLY OPTIONAL and a consumer must tolerate any
 * subset: a file CREATE has no pre-image, so code treating this as a fixed triplet
 * breaks on the first file the agent creates. Granularity is per-file-write, so
 * multi-file attribution must not be inferred from it.
 */
export interface ToolCheckpoint {
  /** Original is the pre-image snapshot URI. Empty on a file creation. */
  original?: string;
  /** Modified is the post-image snapshot URI. */
  modified?: string;
  /** Local is the `file://` URI of the live file on disk. */
  local?: string;
}

/**
 * ToolDenial is the policy verdict that refused a tool call. Rule is the
 * load-bearing field — a denial naming its rule is one click from editing it — and
 * Scope plus Source say which `permissions.yaml` to open.
 */
export interface ToolDenial {
  rule?: ToolDenialRule;
  capability: string;
  resource: string;
  scope: string;
  source: string;
}

/**
 * ToolDenialRule is the Cedar rule that produced a denial. Effect is "deny" or
 * "ask" (an unanswered ask that timed out reaches here as a denial).
 */
export interface ToolDenialRule {
  capability: string;
  effect: string;
  match?: string[];
  exclude?: string[];
}

/**
 * ToolDiff is a before/after text change from a write tool call. Path is
 * workspace-relative; agent.relPath normalises it on the way in.
 * //
 * OldText/NewText carry the WHOLE FILE for KAS's edit tools (325 of 413 persisted
 * fragments measured whole-file shaped), and a hunk pair is also accepted, so a
 * consumer must DIFF the two sides rather than count newlines — counting reported a
 * one-line edit as the entire file removed and re-added.
 */
export interface ToolDiff {
  path: string;
  old_text?: string;
  new_text: string;
}

/**
 * ToolDisclosed identifies a skill or steering document loaded into context by
 * the agent's own `disclose_context` call. Type is "skill" or "steering".
 */
export interface ToolDisclosed {
  type: string;
  display_name: string;
  uri: string;
}

/**
 * ToolInfo is one tool row in Inventory: the manifest entry joined with
 * the engine's install state.
 */
export interface ToolInfo {
  name: string;
  source?: string;
  version?: string;
  description?: string;
  origin?: string;
  installed_version?: string;
  latest?: string;
  last_error?: string;
  /**
 * Checksum reports how the INSTALLED artifact's integrity was
 * established (copied from ToolStatus.Checksum): "verified" or
 * "unverified" per the definition's declared checksum source, empty
 * when the question does not apply (not installed, or a source with
 * no artifact to checksum). A "no checksum" badge reads THIS, not
 * the source kind — 252 of the catalog's aqua entries declare no
 * checksum while the other 402 do.
 */
  checksum?: string;
  requires?: string[];
  /**
 * Dependents names the ENABLED entries that require this tool,
 * directly or as the implied backend of their source kind: what a
 * consumer needs BEFORE sending a disable/remove, instead of
 * learning it from a 409. Advisory only — the engine re-derives the
 * set under the manifest lock, so a stale inventory is still refused.
 */
  dependents?: string[];
  pin?: boolean;
  disabled?: boolean;
  /**
 * Essential marks a tool this application NEEDS: the engine
 * refuses to remove it (ErrEssential), so a consumer renders it apart
 * from the tools a user chose and offers no delete control. Disable
 * remains available, which is the honest escape hatch.
 */
  essential?: boolean;
  /**
 * Lsp marks a language-server entry (catalog knowledge); consumers
 * use it for the no-LSP-enabled warning and UI badges.
 */
  lsp?: boolean;
  installed: boolean;
  installing: boolean;
}

/**
 * ToolJobChangedPayload is the payload for type="tool_job_changed", workspace-global, on
 * every job state transition. The job carries no output tail; output streams via
 * tool_job_output.
 */
export interface ToolJobChangedPayload {
  job?: Job;
}

/**
 * ToolJobOutputPayload is the payload for type="tool_job_output": a coalesced batch of
 * output lines from the running tool job.
 */
export interface ToolJobOutputPayload {
  job_id: string;
  lines: string[];
}

/**
 * ToolLocation is a file path, and optional line, the agent is working with. The
 * editor scrolls to it.
 */
export interface ToolLocation {
  path: string;
  line?: number;
}

/**
 * ToolTruncation is what the store DROPPED to bound what one tool call costs the
 * record, each cut field carrying its size BEFORE the cut so a reader renders
 * "truncated, N bytes" instead of showing less than happened. A zero field was
 * not cut.
 */
export interface ToolTruncation {
  /** OutputBytes and InputBytes are each field's original length. */
  output_bytes?: number;
  input_bytes?: number;
  /**
 * DiffBytes is the original diff total and DiffCount the original count. Diffs
 * are dropped WHOLE: a cut before/after pair would describe an edit nobody made.
 */
  diff_bytes?: number;
  diff_count?: number;
}

/** TurnEndedPayload is the payload for type="turn_ended". */
export interface TurnEndedPayload {
  changed_files?: Record<string, FileChange>;
  /**
 * Refusal accompanies stop_reason "refusal"; also persisted on the message, so
 * this copy is for the live render.
 */
  refusal?: RefusalInfo;
  /**
 * Outcome is the turn's RESULT and what a client reads. StopReason travels beside
 * it as the wire's raw text because the enum is OPEN, and no consumer may branch
 * on that text: an unmeasured value maps to `unknown`.
 */
  outcome?: TurnOutcome;
  stop_reason?: StopReason;
  /**
 * Model answered this turn. Persisted on the message too (Message.TurnModel) so the
 * footer survives a reload; empty when the turn produced no buffer.
 */
  model?: string;
  credits_delta?: number;
  elapsed_ms?: number;
  /** Truncated means the model stopped at a bound: completed, answer cut off. */
  truncated?: boolean;
  /**
 * Superseded means this turn was DISPLACED by a replacement starting on the same
 * chat, so its end says nothing about whether the chat is idle. Only
 * closerWireDisplaced sets it; a client reads it as "report, do not settle".
 * //
 * A CLOSER-derived fact rather than a registry read: displaceEngineTurn closes the
 * old turn immediately BEFORE opening its replacement, so a post-hoc hasOpenTurn
 * answers false for both producers and discriminates nothing.
 */
  superseded?: boolean;
  /**
 * WorkflowStep means the ending turn was opened only because a workflow STEP's
 * frames folded onto this chat (TurnSourceWorkflowStep), so it was never this
 * chat's own conversational turn: the reader's own turn may be live right now, and
 * every chat-scoped teardown would tear down THAT turn's state.
 * //
 * Same word TurnStatePayload already uses for the same fact, so a client learns one
 * name for it. Absent means "this chat's own turn", which is what an older server's
 * frame must keep meaning.
 */
  workflow_step?: boolean;
}

/**
 * TurnStatePayload is the payload for type="turn_state": one per busy chat in the SSE
 * OnConnect replay, NEVER broadcast live, so a reconnecting client renders the accumulated
 * turn immediately and learns authoritatively that the chat is busy.
 */
export interface TurnStatePayload {
  /**
 * Message is the in-flight assistant message as accumulated so far. Omitted when the
 * turn has produced no content yet (busy signal only).
 */
  message?: Message;
  /**
 * Status/Description replay the agent's last self-declared chat_status. Authoritative
 * here because the turn is verifiably in flight, unlike the live event, which is
 * cleared on gaps precisely so a bare replay cannot resurrect a stale "in_progress".
 */
  status?: string;
  description?: string;
  /** ChunkSeq is the last delta folded into Message (see MessageChunkPayload.Seq). */
  chunk_seq?: number;
  /**
 * Truncated reports that the connect-time cap withheld part of Message: the payload
 * carries the TAIL of the in-flight turn, and the rest arrives with message_appended.
 * //
 * NEVER `omitempty`: wiregen emits a REQUIRED field without it, so an absent marker
 * can never be read as "complete", which is what makes the cap admissible. A property
 * of this TRANSFER, so it never moves onto Message, which chat files persist verbatim.
 */
  truncated: boolean;
  /**
 * WorkflowStep marks a turn a workflow RUN opened on the launching chat's session.
 * Contract: APPLY the snapshot, do NOT set thinking. The snapshot is the only copy of
 * an in-flight step's transcript, so the event must still be emitted — but the chat's
 * own agent is idle, and a client reading it as busy says so for the whole run.
 */
  workflow_step?: boolean;
}

/**
 * Usage is a chat's last-known context and billing snapshot, plus the percentages at
 * which the SESSION summarizes and truncates its own context. Both thresholds are
 * omitempty because 0 means UNKNOWN — a chat that has never resumed receives neither,
 * and the client applies its own fallback.
 */
export interface Usage {
  metering_items?: MeteringItem[];
  context_pct: number;
  summarization_threshold_pct?: number;
  truncation_threshold_pct?: number;
  context_size: number;
  credits: number;
  turn_count: number;
  last_turn_ms: number;
  has_real_data: boolean;
}

/** User represents the authenticated forge account. */
export interface User {
  login: string;
  name?: string;
  email?: string;
  url?: string;
}

/**
 * UserInputNeededPayload is the payload for type="user_input_needed": the
 * agent asked a structured question and awaits an answer. An empty Options
 * slice means a free-form question (the client renders a text field).
 * RequestID is the JSON-RPC id the user_input_response command echoes back.
 */
export interface UserInputNeededPayload {
  question: string;
  tool_call_id?: string;
  sub_session_id?: string;
  /**
 * RunID/NodeID: as on PermissionNeededPayload — a workflow step's ask,
 * attributed to its run and node from the step-session registry.
 */
  run_id?: string;
  node_id?: string;
  options?: UserInputOption[];
  request_id: number;
}

/**
 * UserInputOption is one selectable answer for a user-input question.
 * Recommended marks the option the agent suggests (rendered as a badge).
 */
export interface UserInputOption {
  title: string;
  description?: string;
  sub_options_label?: string;
  sub_options?: UserInputSubOption[];
  recommended?: boolean;
}

/**
 * UserInputSubOption is one second-level choice under a UserInputOption.
 * Sub-options render as a pre-checked multi-select (the TUI's behavior);
 * the selected titles fold into the answer text as "Parent [Sub1, Sub2]".
 */
export interface UserInputSubOption {
  title: string;
  description?: string;
}

/**
 * WhoamiResponse is the typed wire shape returned by /api/whoami. State is the
 * discriminator; the remaining fields belong to one arm each. Any kiro-cli field
 * not represented here is dropped at the wire boundary, so a compromised or
 * upgraded CLI cannot leak arbitrary attributes into the browser.
 */
export interface WhoamiResponse {
  state: WhoamiState;
  /** Email and the four labels below belong to the signed_in arm. */
  email?: string;
  auth?: string;
  accountType?: string;
  startUrl?: string;
  region?: string;
  /**
 * Reason belongs to the unavailable arm: a server-authored phrase, never
 * CLI output.
 */
  reason?: string;
}

/**
 * WorkflowRun is one previous workflow run, listed beside previous chats in
 * the history surface (GET /api/sessions) and reviewable read-only.
 * //
 * Sourced from _kiro/workflow/list, NOT session/list: that verb's workflow rows
 * are STEP sessions reporting idle whatever the run did, so they can be neither
 * counted nor judged as runs.
 */
export interface WorkflowRun {
  workflow_id: string;
  /**
 * Name is what to DISPLAY: upstream computes it as `runLabel ?? workflowName`,
 * so it stops being the recipe the moment anything stamps a label.
 */
  name: string;
  /**
 * WorkflowName is the RECIPE, and the only field a per-recipe decision may
 * read: an agent launching via `run_workflow` passes a `<recipe>-<topic>`
 * label and KAS stamps `<workflowName>-<targetId>` on a watch node, so keying
 * the single-run rule on Name made that guard fail OPEN.
 */
  workflow_name?: string;
  /** Status is run-level: paused / completed / failed. */
  status?: RunStatus;
  /**
 * ParentChatID is the vibekit chat that launched the run, resolved through the
 * launching session's chain. Empty for a run with no vibekit parent.
 */
  parent_chat_id?: string;
  /**
 * EndReason says why something OTHER than the run stopped it: "overran" (a
 * slot, the idle window or the backstop) or "step_cap". Every bound cancels
 * through the verb the Cancel button reaches, so KAS reports `cancelled`
 * either way and only this separates a bound from a person; a user cancel
 * records nothing. In-memory for the runs THIS process stopped, so one
 * stopped before a restart falls back to the plain status.
 */
  end_reason?: string;
  updated_at: number;
  created_at?: number;
  started_at?: number;
}

