// CODE-GENERATED by cmd/wire-codegen, DO NOT EDIT.

export type ClearReason = "turn_ended" | "cancelled" | "mode_disabled" | "chat_deleted" | "shutdown" | "user_cleared" | "bridge_exited";

export type ErrorCode = "recovery_failed" | "bridge_start_failed" | "prompt_failed" | "agent_not_found" | "agent_config_error" | "rate_limit" | "stream_timeout" | "spawn_failed" | "switch_failed" | "compaction_failed";

export type EventKind = "interrupted" | "cancelled" | "model_switched" | "compacted" | "compaction_failed" | "infra_safety_blocked";

export type ForgeKind = "github" | "gitlab" | "gitea" | "codeberg";

export type PendingAction = "accept" | "reject";

export type PendingChangeKind = "create" | "edit" | "delete";

export type PlanStatus = "pending" | "in_progress" | "completed";

export type Role = "user" | "assistant" | "event";

export type SafetyStatus = "idle" | "formalizing" | "evaluating" | "blocked" | "error";

export type StopReason = "end_turn" | "cancelled" | "interrupted" | "refusal";

export type ToolKind = "execute" | "shell" | "read" | "search" | "fetch" | "edit" | "think" | "hook" | "write" | "delete" | "move" | "command" | "browser" | "switch_mode" | "mcp" | "other";

export type ToolStatus = "pending" | "in_progress" | "completed" | "failed";

export type Transport = "stdio" | "http" | "sse";

/**
 * AccountUsage is the account/subscription usage snapshot for the
 * signed-in identity.
 */
export interface AccountUsage {
  /** PlanName is the subscription title (e.g. "KIRO POWER"). */
  plan_name?: string;
  /** BillingCycleReset is the YYYY-MM-DD reset date, or "" when unknown. */
  billing_cycle_reset?: string;
  /**
 * FetchedAt is the RFC3339 timestamp of the fetch that produced this
 * snapshot, so the client can show freshness.
 */
  fetched_at?: string;
  /**
 * Note carries a human-readable status for degraded states (e.g. an
 * admin-managed plan that returns no breakdowns).
 */
  note?: string;
  /**
 * Breakdowns is the per-resource usage list (typically a single
 * CREDIT entry).
 */
  breakdowns: AccountUsageBreakdown[];
  /** IsEnterprise reports whether the plan is an enterprise/managed plan. */
  is_enterprise?: boolean;
  /** OveragesEnabled reports whether overage billing is enabled. */
  overages_enabled?: boolean;
  /**
 * Stale is true when this snapshot was served from the last-known
 * cache because a fresh fetch failed (no live bridge, rate limit).
 */
  stale?: boolean;
}

/**
 * AccountUsageBreakdown is one resource line of an AccountUsage (e.g.
 * credits). Used/Limit are precision floats as reported by KAS.
 */
export interface AccountUsageBreakdown {
  /** ResourceType is the KAS resource key (e.g. "CREDIT"). */
  resource_type?: string;
  /** DisplayName is the human label (e.g. "Credits"). */
  display_name?: string;
  /** Currency is the ISO currency for monetary fields (e.g. "USD"). */
  currency?: string;
  /** Used is the amount consumed this cycle. */
  used: number;
  /** Limit is the plan allowance; meaningful only when HasLimit is true. */
  limit: number;
  /** CurrentOverages is the amount consumed beyond Limit. */
  current_overages?: number;
  /** OverageCharges is the monetary overage charge in Currency. */
  overage_charges?: number;
  /** Percentage is floor(Used/Limit*100); can exceed 100 on overage. */
  percentage: number;
  /** HasLimit reports whether Limit is a real cap (false = unlimited). */
  has_limit?: boolean;
}

/**
 * AvailableCommand is one entry in the slash-command catalogue surfaced
 * by kiro-cli's _kiro.dev/commands/available notification. The wire
 * shape carries opaque metadata; clients consume only Name and Description.
 */
export interface AvailableCommand {
  meta?: Record<string, unknown>;
  name: string;
  description?: string;
}

/**
 * Block is one entry in an assistant message's chronological content
 * array. Position in Message.Blocks IS the order in which the agent
 * emitted the block — text → tool → text → tool, etc. — so the client
 * renders them inline as they happened rather than concatenating all
 * text into one bubble at the top with tools dumped below.
 * //
 * Replay-compatible: messages persisted before this field existed have
 * Blocks=nil. Renderers fall back to the legacy Content + ToolCalls
 * layout when Blocks is empty.
 */
export interface Block {
  /** Type is the discriminator: text | tool_use | thinking. */
  type: string;
  /**
 * Text carries the markdown text for Type=BlockText. Accumulated
 * across MessageChunkPayload events targeting this block index.
 */
  text?: string;
  /** Thinking carries the reasoning text for Type=BlockThinking. */
  thinking?: string;
  /**
 * ToolCallID references a tool by ID in Message.ToolCalls for
 * Type=BlockToolUse. Empty for other types.
 */
  tool_call_id?: string;
  /**
 * AgentSubtaskID is the subtask id of the agent that produced this
 * block ("" = top-level agent). Set from the emitting event's
 * _meta.kiro.agentSubtaskId; lets the client group a subagent's
 * blocks and render them nested.
 */
  agent_subtask_id?: string;
}

/**
 * CatalogInfo reports the live catalog's provenance and freshness (the
 * Engine.CatalogInfo return and the httpapi GET catalog body).
 */
export interface CatalogInfo {
  /**
 * Refs are the upstream registry refs the catalog was compiled
 * from; Generated its compile timestamp (RFC 3339 UTC). Both are
 * informational pass-throughs of the catalog document.
 */
  refs?: Record<string, string>;
  generated?: string;
  /**
 * Source is where the live catalog came from: baked (the image
 * file), cached (the refresh cache, reloaded at boot), remote
 * (fetched this process lifetime), or none (degraded, no catalog).
 */
  source: string;
  /**
 * URL is the configured refresh source (empty when refresh is not
 * configured).
 */
  url?: string;
  /**
 * LastError is the most recent refresh failure ("" after a
 * successful refresh).
 */
  last_error?: string;
  entries: number;
  /**
 * FetchedAt is the last successful refresh (Unix milliseconds; 0
 * before the first).
 */
  fetched_at?: number;
  /**
 * Scheduled reports whether the engine-owned background refresh
 * loop is running.
 */
  scheduled: boolean;
}

/** ChatDeletedPayload is the payload for type="chat_deleted". */
export interface ChatDeletedPayload {
  id: string;
}

/**
 * ChatHeader is the metadata-only view of a Chat. Field order is driven
 * by fieldalignment packing, not Chat's field order; both structs
 * serialise to JSON independently so the visual mismatch is harmless.
 */
export interface ChatHeader {
  parent_chat_id?: string;
  name: string;
  model?: string;
  acp_session_id?: string;
  current_mode_id?: string;
  id: string;
  compaction_watermark?: string;
  oldest_checkpoint_tag?: string;
  summary?: string;
  available_models?: SessionModel[];
  available_modes?: SessionMode[];
  /**
 * PriorACPSessionIDs mirrors Chat's. Carried on the header because the
 * retention sweep derives its keep-list from header reads rather than
 * loading every chat in full.
 */
  prior_acp_session_ids?: string[];
  usage: Usage;
  created_at: number;
  updated_at: number;
  message_count: number;
  supervised_mode?: boolean;
}

/** Check is a single CI status check for a commit. */
export interface Check {
  name: string;
  status: string;
  conclusion: string;
  url?: string;
}

/**
 * CodeReference is one licensed-code attribution surfaced by the agent
 * (v3/KAS _kiro/code_references). KAS emits it when a completion reproduces
 * a recognizable chunk of a referenced open-source file and the account's
 * code-reference tracker is enabled. The KAS ACP layer maps every reference
 * down to these three fields (licenseName + repository + url); the raw
 * CodeWhisperer recommendationContentSpan and information fields are dropped
 * upstream before we ever see them, so there is no span to map a reference
 * to a specific message region — attributions are turn-scoped and persisted
 * on the assistant Message they arrived during.
 */
export interface CodeReference {
  license_name: string;
  repository?: string;
  url?: string;
}

/**
 * CodeReferencesPayload is the payload for type="code_references". Carries
 * the licensed-code attributions accumulated on the in-flight assistant
 * turn (v3/KAS). MessageID targets that turn's assistant message so the
 * client attaches the chip to it; References is the full deduped list so
 * the client can render idempotently (a later notification replaces rather
 * than appends). Also persisted on the Message so the chip survives reload.
 */
export interface CodeReferencesPayload {
  message_id: string;
  references: CodeReference[];
}

/** CommandsUpdatedPayload is the payload for type="commands_updated". */
export interface CommandsUpdatedPayload {
  commands: AvailableCommand[];
  prompts?: AvailableCommand[];
}

/**
 * ConfiguredForge is one connected forge backend, discovered through
 * the CLIs' own status subcommands (see discover.go).
 */
export interface ConfiguredForge {
  id: string;
  kind: ForgeKind;
  host: string;
  username?: string;
  email?: string;
  last_error?: string;
  last_probed?: number;
  connected: boolean;
  /**
 * CLIMissing marks a connection whose backing CLI binary is absent
 * (uninstalled/disabled in Settings → Tools, or a fresh tools volume
 * against a kept config volume) while a configuration for it still
 * exists. The row renders as a warning with a reinstall pointer; it
 * is never probed and cannot be disconnected until the CLI returns.
 */
  cli_missing?: boolean;
}

/** ConflictPayload is what the broadcaster receives per conflict. */
export interface ConflictDetectedPayload {
  path: string;
  other_chat: string;
  expected_sha: string;
  actual_sha: string;
  tag: string;
  ts: number;
}

/**
 * ConnectedPayload is the payload for type="connected", the SSE handshake
 * event. Floor is the oldest event ID still in the replay ring; Head is
 * the newest. Clients with last-seen-id < Floor know they missed events
 * and should refetch authoritative state.
 */
export interface ConnectedPayload {
  floor: number;
  head: number;
}

/** DeviceFlowResponse describes a started OAuth device flow. */
export interface DeviceFlowResponse {
  user_code: string;
  verification_uri: string;
  device_code: string;
  interval: number;
  expires_in: number;
}

/**
 * ElicitationNeededPayload is the SSE payload for type="elicitation_needed".
 * Mirrors PermissionNeededPayload's role: it carries everything the
 * client needs to render the dialog plus the RequestID to echo back in
 * the elicitation_response command. Mode is "form" or "url"; URL-mode
 * elicitations carry URL and no RequestedSchema.
 */
export interface ElicitationNeededPayload {
  requested_schema?: ElicitationRequestSchema;
  mode?: string;
  message?: string;
  url?: string;
  tool_call_id?: string;
  sub_session_id?: string;
  request_id: number;
}

/**
 * ElicitationPropertySchema describes one field in an elicitation form.
 * Type is the discriminator ("string" | "number" | "integer" |
 * "boolean" | "array"); the other fields are populated as relevant to
 * that type. Unset fields are omitted on the wire.
 */
export interface ElicitationPropertySchema {
  default?: unknown;
  minLength?: number;
  maxLength?: number;
  type: string;
  title?: string;
  description?: string;
  format?: string;
  pattern?: string;
  enum?: string[];
}

/**
 * ElicitationRequestSchema is the JSON-schema-shaped object describing a
 * form: a map of property name to its schema, plus the required set.
 */
export interface ElicitationRequestSchema {
  type?: string;
  title?: string;
  description?: string;
  properties?: Record<string, ElicitationPropertySchema>;
  required?: string[];
}

/**
 * ErrorPayload is the payload for type="error". Code lets clients react
 * per-class without string-matching.
 */
export interface ErrorPayload {
  code: ErrorCode;
  message: string;
}

/** FileChange tracks per-file change stats during a turn. */
export interface FileChange {
  lines_added: number;
  lines_removed: number;
  is_new_file?: boolean;
}

/**
 * GovernanceFeatures is the org/account feature-flag set carried by the v3
 * (KAS) _kiro/governance/state notification (KAS's GovernanceFeatures object,
 * verified against the KAS 2.12 acp-server bundle + a live probe). Every field
 * is the RESOLVED effective value: MCPEnabled/WebToolsEnabled/AutonomousAgents
 * are the negation of a "…GovernanceDisabled" flag; the analytics/logging/
 * tracker fields are direct "…GovernanceEnabled" flags. On an individual /
 * Builder-ID login these resolve to a permissive default (mcp/webTools/
 * autonomousAgents on; analytics/promptLogging/codeReferenceTracker off;
 * contentCollection on) with isEnterprise=false and no disabledReason.
 * //
 * NOTE: Infrastructure-Safety (infraSafetyMonitor/infraSafetyEnforce) is NOT
 * here — it is a separate modelConfigProvider.isFeatureEnabled channel, not a
 * governance feature (verified: absent from _kiro/governance/state). So the
 * safety banner (translate/safety.go) is gated by KAS's own emission, not by
 * any field on this struct.
 */
export interface GovernanceFeatures {
  /**
 * MCPEnabled reports whether the MCP subsystem is permitted. When false,
 * enterprise governance has suppressed MCP entirely (vibekit disables the
 * add-server affordance and shows a disabled state in Settings → Tools).
 */
  mcp_enabled: boolean;
  /** WebToolsEnabled reports whether built-in web tools are permitted. */
  web_tools_enabled: boolean;
  /** UsageAnalytics reports whether usage analytics collection is enabled. */
  usage_analytics: boolean;
  /** ContentCollection reports whether content collection is enabled. */
  content_collection: boolean;
  /** PromptLogging reports whether prompt logging is enabled. */
  prompt_logging: boolean;
  /**
 * CodeReferenceTracker reports whether licensed-code reference tracking is
 * enabled — the flag that governs whether KAS emits _kiro/code_references
 * (the attribution chip in code-refs.ts is dormant unless this is true).
 */
  code_reference_tracker: boolean;
  /** AutonomousAgents reports whether autonomous agent runs are permitted. */
  autonomous_agents: boolean;
}

/**
 * GovernanceStatePayload is the payload for type="governance_state", translated
 * from the v3 (KAS) _kiro/governance/state notification (buildNotification:
 * {sessionId, isEnterprise, features, disabledReason}). The account/workspace
 * feature-flag policy KAS pushes on every session/new + session/load, and
 * re-pushes on a prompt when it changes; vibekit caches the latest hub-side and
 * also serves it at GET /api/governance so a fresh page load can read it with
 * no chat open. The wire sessionId is used only for subagent-copy dedup and is
 * dropped from this payload — governance is account-global, so the SSE is
 * broadcast with an empty chat id (every client receives it).
 * //
 * Known distinguishes "the server has told us the real policy" (Known=true, on
 * every SSE broadcast and a warm REST snapshot) from "not yet observed"
 * (Known=false, a cold REST snapshot before any bridge has started). Clients
 * MUST only gate/annotate affordances when Known is true — the all-false zero
 * value would otherwise read as "everything disabled" when we simply don't know
 * yet.
 */
export interface GovernanceStatePayload {
  /**
 * DisabledReason is a human-readable reason surfaced by enterprise
 * governance (e.g. why MCP is off); empty/absent on a normal account.
 */
  disabled_reason?: string;
  /** Features is the resolved effective feature-flag set. */
  features: GovernanceFeatures;
  /** Known is true once the real policy has been observed (see the type doc). */
  known: boolean;
  /** IsEnterprise reports whether this is an enterprise/managed account. */
  is_enterprise?: boolean;
}

/**
 * Inventory is the full read-side snapshot: every manifest entry joined
 * with state, the system group, and the active job.
 */
export interface Inventory {
  job?: Job;
  tools: ToolInfo[];
  system: SystemTool[];
}

/** Issue represents a forge issue. */
export interface Issue {
  title: string;
  body?: string;
  state: string;
  author?: string;
  url?: string;
  labels?: string[];
  number: number;
  created_at?: number;
  updated_at?: number;
}

/** Job is one queued/running/finished unit of engine work. */
export interface Job {
  id: string;
  kind: string;
  state: string;
  error?: string;
  names?: string[];
  /**
 * OutputTail carries the job's most recent output lines; populated
 * by Jobs() snapshots only (live output streams via the
 * Config.OnJobOutput callback).
 */
  output_tail?: string[];
  /** Timestamps are Unix milliseconds. */
  created_at: number;
  started_at?: number;
  ended_at?: number;
}

/** JobResponse is the 202 body of every mutating route. */
export interface JobResponse {
  job?: Job;
}

/**
 * JobsResponse is the jobs route's body: the active job (with output
 * tail) and recent history.
 */
export interface JobsResponse {
  active?: Job;
  recent: Job[];
}

/**
 * KnowledgeIndexingPayload is the payload for type="knowledge_indexing".
 * Translated from the KAS _kiro/knowledge/indexingStarted (Status="started",
 * carries FileCount) and _kiro/knowledge/indexingCompleted (Status="success"
 * or a failure string, carries ItemCount on success) notifications. Emitted
 * globally (no chat_id) because the knowledge store is workspace-global; the
 * client refetches GET /api/knowledge on receipt. Note: these fire only for
 * agent-declared knowledge_bases sync at session start — a user-initiated add
 * reports progress through the `show` active-operations list instead (verified
 * live), so the client also polls while an entry is still indexing.
 */
export interface KnowledgeIndexingPayload {
  name: string;
  status: string;
  file_count?: number;
  item_count?: number;
}

/** Label is a forge label (used on PRs and issues). */
export interface Label {
  name: string;
  color?: string;
  description?: string;
}

/**
 * MCPConnectedPayload is the payload for type="mcp_connected", emitted
 * when kiro-cli reports _kiro.dev/mcp/server_initialized.
 */
export interface MCPConnectedPayload {
  server: string;
}

/**
 * MCPDisconnectedPayload is the payload for type="mcp_disconnected".
 * Emitted when the hub's last bridge exits: kiro-cli's MCP subprocesses
 * shut down with it, so no configured server is currently live.
 * Clients use this to clear their runtime-state map.
 */
export interface MCPDisconnectedPayload {
  server: string;
}

/**
 * MCPFailedPayload is the payload for type="mcp_failed", emitted
 * when kiro-cli reports _kiro.dev/mcp/server_init_failure.
 */
export interface MCPFailedPayload {
  server: string;
  error: string;
}

/**
 * MCPOAuthPayload is the payload for type="mcp_oauth_needed", emitted
 * when kiro-cli reports _kiro.dev/mcp/oauth_request. URL is the
 * provider's authorisation endpoint; the user completes the flow in a
 * new tab.
 */
export interface MCPOAuthPayload {
  server: string;
  url: string;
}

/**
 * Message is one entry in a chat transcript. Tool calls are embedded in
 * assistant messages (not standalone messages). Event messages carry an
 * EventKind for inline rendering (compression, cancellation, restart).
 */
export interface Message {
  /**
 * ChangedFiles is part of the per-turn summary (credits · elapsed · files
 * changed) shown in the assistant turn's footer, set on the final assistant
 * message at turn_ended so the footer survives reload. It was previously an
 * un-keyed direct DOM write in the client, which double-rendered on SSE
 * replay and vanished on refresh. Mirrors the turn_ended SSE payload shape.
 * (Field order in this struct is govet-fieldalignment-optimal, not logical.)
 */
  changed_files?: Record<string, FileChange>;
  role: Role;
  content?: string;
  /**
 * Reasoning is the agent's "thinking" trace for this turn —
 * extended-thinking models emit it as a parallel stream alongside
 * Content. Persisted on the same message so the one-message-per-turn
 * invariant holds; rendered above the content bubble in the UI.
 */
  reasoning?: string;
  /**
 * CheckpointTag is the REAL checkpoint tag the server allocated for
 * this turn (set only on the user message that started a turn whose
 * agent produced at least one file snapshot). It is the turn-canonical
 * tag ("N", never "N.K") the client passes verbatim to
 * restore_checkpoint. Empty when the turn produced no snapshot;
 * persisted so it survives reload.
 */
  checkpoint_tag?: string;
  event_kind?: EventKind;
  id: string;
  tool_calls?: ToolCall[];
  /**
 * Blocks is the chronologically-ordered content array — text / tool_use /
 * thinking blocks in the order the agent emitted them, each stamped with an
 * agent_subtask_id (empty for the parent agent, set for a subagent). It is
 * the canonical render model; the client normalizes legacy Content/ToolCalls
 * into Blocks on replay so there is a single render path.
 */
  blocks?: Block[];
  /**
 * CodeReferences carries licensed-code attributions the agent flagged
 * during this turn (v3/KAS _kiro/code_references). Turn-scoped: the wire
 * carries no span, so it annotates the whole assistant turn. Persisted here
 * so the chip survives reload.
 */
  code_references?: CodeReference[];
  /**
 * Refusal marks this assistant turn as a model refusal (kiro-cli 2.13
 * contract): the message content IS the refusal explanation, and this
 * carries the category + recommended-model metadata the client uses to
 * render the distinct refusal callout (chip + rewind / switch-model CTAs).
 */
  refusal?: RefusalInfo;
  plan?: PlanEntry[];
  /**
 * TurnCredits / TurnElapsedMs complete the turn footer summary alongside
 * ChangedFiles (above). The values also ride the turn_ended SSE for the
 * live render; omitempty drops the zero cases (a read-only turn has none).
 */
  turn_credits?: number;
  turn_elapsed_ms?: number;
  ts: number;
}

/**
 * MessageChunkPayload is the payload for type="message_chunk" (assistant
 * streaming deltas). IsReasoning distinguishes reasoning deltas from
 * regular content deltas — both flow through the same SSE event but
 * land on different fields client-side (Message.Reasoning vs Content).
 * BlockIndex addresses the chronological content block this delta
 * belongs to (Anthropic's content_block_delta.index): consecutive text
 * chunks share an index; a tool_call between text segments bumps the
 * next text chunk to a new index. Clients use this to accumulate
 * deltas into the right block in Message.Blocks.
 */
export interface MessageChunkPayload {
  /**
 * Refusal tags this delta as the model-refusal explanation (kiro-cli
 * 2.13 _meta.kiro.refusal on the chunk). Set on at most one chunk per
 * turn, right before the turn ends with stop_reason "refusal"; lets the
 * live renderer style the refusal callout without waiting for
 * turn_ended.
 */
  refusal?: RefusalInfo;
  message_id: string;
  delta: string;
  agent_subtask_id?: string;
  block_index: number;
  /**
 * Seq is the delta's 1-based sequence number within the turn
 * (assigned by the buffer under its lock). A client that ingested
 * a connect-time turn_state snapshot drops chunks with
 * seq <= the snapshot's chunk_seq watermark — they are already
 * folded into the snapshot — instead of double-appending them.
 */
  seq?: number;
  is_reasoning?: boolean;
}

/**
 * MeteringItem is one usage dimension reported by kiro-cli's
 * meteringUsage array. UnitPlural is the canonical identifier
 * ("credits", "tokens", "requests"); UnitSingular is its singular form.
 */
export interface MeteringItem {
  unit_singular: string;
  unit_plural: string;
  value: number;
}

/**
 * OpenExternalURLPayload is the payload for type="open_external_url".
 * The agent (v3/KAS) asks the client to open a URL for the user, most
 * often an MCP server's OAuth authorization page. Browsers popup-block a
 * window.open() not driven by a user gesture, so the client surfaces a
 * clickable affordance (a banner link) the user activates rather than
 * auto-opening. Only http/https URLs are broadcast (server-side scheme
 * guard in hub/bridge_v3_auth.go; the client re-checks before rendering).
 */
export interface OpenExternalURLPayload {
  url: string;
}

/** PR represents a pull/merge request. */
export interface PR {
  title: string;
  body?: string;
  state: string;
  author?: string;
  source_branch: string;
  target_branch: string;
  url?: string;
  number: number;
  created_at?: number;
  updated_at?: number;
  mergeable?: boolean;
  draft?: boolean;
}

/**
 * PendingChange is one staged file operation awaiting user approval in
 * Supervised mode. Key is ToolCallID (kiro-cli's id; unique per call);
 * the Kind discriminates between writes, creates (no OldText), and
 * deletes (no NewText).
 * //
 * OldText and NewText are capped at pendingTextCap on the server side
 * (4 MiB). When truncated, the client's "View diff" tab falls back to
 * a file fetch for the full content; the staged payload only carries
 * enough for the pill-popover summary and the inline diff preview.
 */
export interface PendingChange {
  tool_call_id: string;
  chat_id: string;
  path: string;
  kind: PendingChangeKind;
  old_text?: string;
  new_text?: string;
  created_at: number;
  truncated?: boolean;
}

/**
 * PendingChangeAddedPayload is the payload for type="pending_change_added".
 * Emitted when the Supervised-mode fs handler has received a write from
 * kiro-cli and is blocking the agent until the user resolves it. Clients
 * render a tool-card-level Accept/Reject pair and surface the op in the
 * Supervised pill's popover.
 */
export interface PendingChangeAddedPayload {
  change: PendingChange;
}

/**
 * PendingChangeResolvedPayload is the payload for
 * type="pending_change_resolved". Emitted after the user accepts or
 * rejects a staged change, after the fs handler has unblocked and the
 * disk state reflects the decision. Clients drop the op from the pending
 * pill and update the source tool card's status.
 */
export interface PendingChangeResolvedPayload {
  tool_call_id: string;
  action: PendingAction;
  path?: string;
}

/**
 * PendingChangesClearedPayload is the payload for
 * type="pending_changes_cleared". Emitted when a turn is cancelled or
 * the chat's Supervised mode is disabled while ops are outstanding;
 * every pending op for the chat is rejected server-side and the client
 * flushes its pending list.
 */
export interface PendingChangesClearedPayload {
  reason?: ClearReason;
}

/** PermissionNeededPayload is the payload for type="permission_needed". */
export interface PermissionNeededPayload {
  tool_call_id?: string;
  title?: string;
  /**
 * Kind forwards the ACP toolCall.kind so the client can style
 * distinctive permission prompts (switch_mode gets a different
 * dialog vs an execute_bash prompt).
 */
  kind?: ToolKind;
  sub_session_id?: string;
  options: PermissionOption[];
  request_id: number;
}

/** PermissionOption is one selectable response in a permission dialog. */
export interface PermissionOption {
  option_id: string;
  name: string;
  kind: string;
}

/**
 * PermissionsChangedPayload is the SSE payload for type="permissions_changed"
 * (translated from _kiro/policy/changed). Clients refetch GET /api/permissions
 * on receipt. Status is "success" or "failed"; Errors carries any non-fatal
 * warnings or the fatal parse error.
 */
export interface PermissionsChangedPayload {
  status?: string;
  errors?: PolicyErrorItem[];
}

/** PlanEntry is one item in an agent-authored plan. */
export interface PlanEntry {
  content: string;
  priority: string;
  status: PlanStatus;
}

/**
 * PolicyErrorItem is one entry in a policy/changed or policy/error
 * notification's errors array (from KAS).
 */
export interface PolicyErrorItem {
  scope?: string;
  source?: string;
  message: string;
  fatal?: boolean;
}

/**
 * PolicyErrorPayload is the SSE payload for type="policy_error" (translated
 * from _kiro/policy/error). Surfaced as a banner so a bad hand-edit or a
 * rejected rule is visible without hunting the logs.
 */
export interface PolicyErrorPayload {
  errors?: PolicyErrorItem[];
}

/** PolicyExplainResult mirrors _kiro/permissions/explain (a pure simulation). */
export interface PolicyExplainResult {
  capability: string;
  resource?: string;
  effect: string;
  matched_rule?: PolicyRuleCore;
  scope?: string;
  source?: string;
  is_explicit_ask: boolean;
}

/**
 * PolicyRule is one native policy rule as reported by _kiro/permissions/list.
 * Capability + effect are always present; match/exclude are optional glob
 * lists; scope + source carry provenance (source is a file path for
 * user/workspace rules, or a synthetic tag like "kiro-scope"/"agent-profile").
 */
export interface PolicyRule {
  capability: string;
  effect: string;
  scope: string;
  source: string;
  match?: string[];
  exclude?: string[];
}

/**
 * PolicyRuleCore is the rule shape without provenance, used inside an
 * explain result's matched_rule.
 */
export interface PolicyRuleCore {
  capability: string;
  effect: string;
  match?: string[];
  exclude?: string[];
}

/**
 * PolicyView is the GET /api/permissions response: the native policy rule
 * set plus the metadata the editor needs. Available is false when no bridge
 * could answer (the view falls back to reading the editable files directly).
 */
export interface PolicyView {
  rules: PolicyRule[];
  writable_scopes: string[];
  capabilities: string[];
  available: boolean;
}

/** PollResult is the per-poll status during the device flow. */
export interface PollResult {
  status: string;
  error?: string;
}

/**
 * RefusalInfo is the structured refusal metadata KAS attaches when the model
 * declines to continue a conversation (modelStopReason "content_filtered";
 * kiro-cli 2.13+). It rides the refusal explanation chunk's update-level
 * _meta.kiro.refusal and the turn ends with stopReason "refusal". The
 * explanation text itself streams as ordinary assistant content, so only the
 * classification fields are kept here; persisted on the assistant Message so
 * the refusal callout survives reload. RecommendedModel, when set, names a
 * model the service suggests switching to.
 */
export interface RefusalInfo {
  category?: string;
  recommended_model?: string;
}

/** Release represents a tagged release. */
export interface Release {
  tag_name: string;
  name?: string;
  body?: string;
  url?: string;
  published_at?: number;
  draft?: boolean;
  prerelease?: boolean;
}

/**
 * RemoveResponse rides a 409-free DELETE alongside the job (dependents
 * is populated on forced cascades so the client can report what else
 * was removed).
 */
export interface RemoveResponse {
  job?: Job;
  dependents?: string[];
}

/** Repo is a remote repository accessible via the authenticated forge. */
export interface Repo {
  owner: string;
  name: string;
  full_name: string;
  default_branch?: string;
  url?: string;
  clone_url?: string;
  description?: string;
  private?: boolean;
  archived?: boolean;
  fork?: boolean;
  updated_at?: number;
}

/**
 * SafetyPropertiesPayload is the payload for type="safety_properties",
 * translated from the v3 (KAS) _kiro/safety/propertiesChanged notification.
 * Reason is the KAS PropertyChangeReason (formalized/toggled/expired). Same
 * gating + authoring caveats as SafetyStatusPayload.
 */
export interface SafetyPropertiesPayload {
  reason?: string;
  properties: SafetyProperty[];
}

/**
 * SafetyProperty is one formalized Infrastructure-Safety property. Properties
 * are authored OUT-OF-BAND: KAS "formalizes" them via a remote MCP tool
 * (evaluate_infrastructure_safety at runtime.us-east-1.kiro.dev) from the
 * agent's own infrastructure work — there is no client RPC to create, set, or
 * toggle one, so vibekit only ever displays them, never authors them.
 */
export interface SafetyProperty {
  description: string;
  index?: number;
  enabled?: boolean;
}

/**
 * SafetyStatusPayload is the payload for type="safety_status", translated from
 * the v3 (KAS) _kiro/safety/statusChanged notification. It surfaces the
 * Infrastructure-Safety gate's live state so the client can show a transient
 * status banner. Defensive/forward-looking: KAS only installs the gate (and so
 * only emits this) when the client declares the infrastructureSafety capability
 * AND an AWS governance flag (infraSafetyMonitor/infraSafetyEnforce) is on — off
 * by default on individual/Builder-ID accounts, so this normally never fires.
 * Distinct from vibekit's own Supervised write-gate (see vibekit-supervised.md).
 */
export interface SafetyStatusPayload {
  status: SafetyStatus;
  detail?: string;
  tool_id?: string;
  blocked_properties?: string[];
}

/**
 * SearchHit is one catalog search result. A projection of
 * toolbelt.CatalogEntry without the embedded install definition (an
 * implementation detail no client needs).
 */
export interface SearchHit {
  name: string;
  description?: string;
  source: string;
  /**
 * Version is the catalog's default pinned version, set only for
 * entries without an upstream version source (manual installs).
 */
  version?: string;
  featured?: boolean;
  lsp?: boolean;
}

/** SearchResponse is the search route's body. */
export interface SearchResponse {
  results: SearchHit[];
}

/**
 * SessionMode describes one mode the running agent supports. Populated
 * from the `modes.availableModes` field of kiro-cli's session/new or
 * session/load response; kept on the chat so the UI can render a mode
 * pill without re-querying the bridge.
 * //
 * On v3 (KAS) the availableModes list is unified: it carries both the
 * bundled workflow modes (vibe/spec/quick-spec/bug-fix/plan/autonomous)
 * AND every workspace custom agent (.kiro/agents/*), each switchable via
 * session/set_mode. Source distinguishes them ("bundled" vs "workspace")
 * so the picker can group built-in modes above custom agents.
 */
export interface SessionMode {
  id: string;
  name: string;
  description?: string;
  source?: string;
}

/**
 * SessionModel describes one model the running agent can swap to, as
 * declared by kiro-cli's session/new response. Replaces our prior
 * shell-out to `kiro-cli chat --list-models`.
 */
export interface SessionModel {
  id: string;
  name: string;
  description?: string;
  rate_multiplier?: number;
  /**
 * HasEffort reports whether this model supports a reasoning-effort level.
 * KAS's config_option_update stamps _meta.kiro.hasEffort on each model
 * choice (true when the model has effort levels). The model picker hides
 * the effort row for the current model when the catalog carries
 * has_effort:true on some model but not the current one; a catalog with no
 * has_effort anywhere (e.g. the pre-session REST list) safely shows it. A
 * non-effort model omits the field (client reads it as undefined), which is
 * why the client's gate keys off "any model advertises effort" rather than
 * a per-model false.
 */
  has_effort?: boolean;
}

/** SystemTool is one image-baked binary surfaced read-only (Config.System). */
export interface SystemTool {
  name: string;
  installed: boolean;
}

/**
 * ToolCall is a tool invocation inside an assistant message. One assistant
 * message may have multiple tool calls; each can be updated in place as
 * status changes (pending → in_progress → completed/failed).
 */
export interface ToolCall {
  id: string;
  title: string;
  kind: ToolKind;
  status: ToolStatus;
  output?: string;
  /**
 * SubSessionID is the v2 subagent-session attribution (inert on v3;
 * all subagent updates ride the parent session id there).
 */
  sub_session_id?: string;
  /**
 * AgentSubtaskID is set from a tool call's _meta.kiro.agentSubtaskId.
 * On v3 (KAS) a subagent surfaces as an ordinary tool_call with
 * _meta.kiro.kind=="agent-subtask"; this id links the subagent card
 * to its nested agent_message_chunk / agent_thought_chunk deltas
 * (which carry the same id) so the client can render them nested.
 */
  agent_subtask_id?: string;
  /**
 * Checkpoint is KAS's snapshot mapping for a tool call that wrote a
 * file, taken from _meta.kiro.checkpoint. Nil for every tool call that
 * touched no file — which is most of them. Placed ahead of the slices
 * below to keep govet fieldalignment happy: a trailing pointer would
 * extend the GC scan region past a slice's non-pointer len/cap words.
 */
  checkpoint?: ToolCheckpoint;
  input?: unknown;
  locations?: ToolLocation[];
  diffs?: ToolDiff[];
  duration_ms?: number;
  ts: number;
}

/**
 * ToolCallPayload is the payload for type="tool_call". BlockIndex is
 * the position of the tool_use block in the assistant message's
 * chronological Blocks array — the client uses it to insert the tool
 * card at the right spot relative to surrounding text blocks.
 */
export interface ToolCallPayload {
  message_id: string;
  tool_call: ToolCall;
  block_index: number;
}

/** ToolCallUpdatePayload is the payload for type="tool_call_update". */
export interface ToolCallUpdatePayload {
  message_id: string;
  tool_call: ToolCall;
}

/**
 * ToolCheckpoint is KAS's pre/post-image mapping for one file write,
 * persisted verbatim so a diff is a snapshot read plus a file read with no
 * derivation. vibekit captures no snapshots of its own; KAS does it
 * unconditionally and hands the addresses over on the wire.
 * //
 * Original and Modified are `kiro-snapshot-v2://<sessionId>:<snapshotId>/?originalPath=<relpath>`
 * URIs — opaque handles, NOT filesystem paths, deliberately stored
 * unparsed. Local is a `file://` URI for the live file.
 * //
 * **All three fields are independently optional and a consumer must
 * tolerate any subset** (probed 2026-08-02, kiro-cli 2.16.0): a file
 * CREATE has no pre-image, so it arrives as {Modified, Local} with Original
 * empty, while overwriting an existing file yields all three. Code that
 * treats this as a fixed triplet breaks on the first file the agent
 * creates.
 * //
 * Granularity is per-file-write, not per-turn, and a multi-file tool
 * (semantic_rename) carries no per-file mapping at all — KAS's
 * checkpoint.fileChanges has zero occurrences in the corpus — so
 * multi-file attribution is not recoverable from this field and must not
 * be inferred from it.
 */
export interface ToolCheckpoint {
  /** Original is the pre-image snapshot URI. Empty on a file creation. */
  original?: string;
  /** Modified is the post-image snapshot URI. */
  modified?: string;
  /** Local is the `file://` URI of the live file on disk. */
  local?: string;
}

/**
 * ToolDiff is a before/after text change from a write tool call. Sent
 * by kiro-cli in tool_call notifications for edit operations. Path is
 * workspace-relative (absolute paths from kiro-cli are normalised via
 * hub.relPath before being stored here); OldText/NewText are the
 * changed fragments, not full-file contents.
 */
export interface ToolDiff {
  path: string;
  old_text?: string;
  new_text: string;
}

/**
 * ToolInfo is one tool row in Inventory: the manifest entry joined with
 * the engine's install state.
 */
export interface ToolInfo {
  name: string;
  source?: string;
  version?: string;
  description?: string;
  origin?: string;
  installed_version?: string;
  latest?: string;
  last_error?: string;
  requires?: string[];
  pin?: boolean;
  disabled?: boolean;
  /**
 * Lsp marks a language-server entry (catalog knowledge); consumers
 * use it for the no-LSP-enabled warning and UI badges.
 */
  lsp?: boolean;
  installed: boolean;
  installing: boolean;
}

/**
 * ToolJobChangedPayload is the payload for type="tool_job_changed".
 * Broadcast (workspace-global — no chat_id) on every tool-job state
 * transition: enqueued, started, done, failed, cancelled. The job
 * carries no output tail; output streams via tool_job_output.
 */
export interface ToolJobChangedPayload {
  job?: Job;
}

/**
 * ToolJobOutputPayload is the payload for type="tool_job_output":
 * a coalesced batch of output lines from the running tool job.
 */
export interface ToolJobOutputPayload {
  job_id: string;
  lines: string[];
}

/**
 * ToolLocation is a file path (and optional line) the agent is working
 * with. Sent by kiro-cli in tool_call and tool_call_update notifications.
 * Used by the editor to scroll to the file the agent is accessing or
 * modifying.
 */
export interface ToolLocation {
  path: string;
  line?: number;
}

/** TurnEndedPayload is the payload for type="turn_ended". */
export interface TurnEndedPayload {
  changed_files?: Record<string, FileChange>;
  /**
 * Refusal accompanies stop_reason "refusal": the model declined to
 * continue and the final assistant chunk carried this metadata
 * (also persisted on the message; here for the live render).
 */
  refusal?: RefusalInfo;
  stop_reason?: StopReason;
  credits_delta?: number;
  elapsed_ms?: number;
}

/**
 * TurnStatePayload is the payload for type="turn_state": the
 * connect-time synthesis of a chat's in-flight turn (P6). Synthesized
 * per busy chat in the SSE OnConnect replay — never broadcast live —
 * so a reconnecting or freshly-loaded client renders the accumulated
 * turn immediately instead of waiting for the next chunk or
 * turn_ended, and learns authoritatively that the chat is busy
 * (replacing the gap handler's eager thinking-clear guess).
 */
export interface TurnStatePayload {
  /**
 * Message is the in-flight assistant message as accumulated so
 * far — the hub's turn mirror, byte-equivalent to what a
 * never-disconnected client would have rendered. Omitted when the
 * turn hasn't produced content yet (busy signal only).
 */
  message?: Message;
  /**
 * Status/Description replay the agent's last self-declared
 * chat_status for the busy chat. Authoritative here — the turn is
 * verifiably in flight — unlike the live event, which stays
 * ephemeral and is cleared on gaps precisely because a bare
 * replay could resurrect a stale "in_progress".
 */
  status?: string;
  description?: string;
  /**
 * ChunkSeq is the sequence number of the last delta folded into
 * Message (see MessageChunkPayload.Seq).
 */
  chunk_seq?: number;
}

/** Usage is a chat's last-known context and billing snapshot. */
export interface Usage {
  metering_items?: MeteringItem[];
  context_pct: number;
  context_size: number;
  credits: number;
  turn_count: number;
  last_turn_ms: number;
  has_real_data: boolean;
}

/** User represents the authenticated forge account. */
export interface User {
  login: string;
  name?: string;
  email?: string;
  url?: string;
}

/**
 * UserInputNeededPayload is the payload for type="user_input_needed": the
 * agent asked a structured question and awaits an answer. An empty Options
 * slice means a free-form question (the client renders a text field).
 * RequestID is the JSON-RPC id the user_input_response command echoes back.
 */
export interface UserInputNeededPayload {
  question: string;
  tool_call_id?: string;
  sub_session_id?: string;
  options?: UserInputOption[];
  request_id: number;
}

/**
 * UserInputOption is one selectable answer for a user-input question.
 * Recommended marks the option the agent suggests (rendered as a badge).
 */
export interface UserInputOption {
  title: string;
  description?: string;
  sub_options_label?: string;
  sub_options?: UserInputSubOption[];
  recommended?: boolean;
}

/**
 * UserInputSubOption is one second-level choice under a UserInputOption.
 * Sub-options render as a pre-checked multi-select (the TUI's behavior);
 * the selected titles fold into the answer text as "Parent [Sub1, Sub2]".
 */
export interface UserInputSubOption {
  title: string;
  description?: string;
}

/**
 * WhoamiResponse is the typed response from /api/whoami; see the block
 * comment above for the full field semantics and security rationale.
 */
export interface WhoamiResponse {
  email?: string;
  auth?: string;
  accountType?: string;
  startUrl?: string;
  region?: string;
  error?: string;
}

